//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Billing.rc
//
#define IDC_SAVE                        3
#define IDC_CALCULATE                   3
#define IDC_PREVIEW_DRAWER              3
#define IDC_PRINT                       50
#define IDD_CHOOSE_ID_DLG               129
#define IDD_FINANCIAL_DLG               228
#define IDD_BILLING_DLG                 230
#define IDD_PAYMENT_DLG                 233
#define IDD_BILLING_MODULE_DLG          240
#define IDD_FINANCIAL_APPLY_DLG         242
#define IDD_QUOTES_DLG                  258
#define IDD_INSURANCE_BILLING           273
#define IDD_MULTI_FEE_ADJUSTMENT        278
#define IDD_LAUNCHSTATEMENTS            283
#define IDD_QUOTE_NOTES                 316
#define IDD_APPLY_MANAGER_DLG           360
#define IDD_PRINT_ALIGN_DLG             382
#define IDD_QUOTE_ADMIN                 423
#define IDD_DIALOG3                     424
#define IDD_CHARGE_DISCOUNT_DLG         424
#define IDD_DLG_CREDITCARD              538
#define IDD_SUPERBILL_APPLY_PROMPT      616
#define IDD_APPLIED_SUPERBILL_DLG       618
#define IDC_PRINTLIST                   1000
#define IDC_ALLPROVIDERS                1000
#define IDC_LAST_NAME_BOX               1000
#define IDC_EXPORT                      1001
#define IDC_SELECT_PROVIDER_RADIO       1001
#define IDC_INSPLAN1                    1001
#define IDC_INSPLAN2                    1002
#define IDC_REF_PHYS                    1003
#define IDC_REMOVEBUTTON                1006
#define IDC_DELETE                      1006
#define IDC_OPENBUTTON                  1007
#define IDC_EDIT_PAY_CAT                1007
#define IDC_FIRST_NAME_BOX              1007
#define IDC_ALLDATES                    1008
#define IDC_EDIT_PAY_DESC               1008
#define IDC_MIDDLE_NAME_BOX             1008
#define IDC_DATERANGE                   1009
#define IDC_PRINTBATCH                  1009
#define IDC_EDIT_CARD_NAME              1009
#define IDC_RESET                       1010
#define IDC_EDIT_CASH_DRAWERS           1010
#define IDC_ADDRESS1_BOX                1011
#define IDC_BTN_FILTER_REASON_CODES     1011
#define IDC_ADDRESS2_BOX                1012
#define IDC_CITY_BOX                    1013
#define IDC_STATE_BOX                   1014
#define IDC_CANCEL_BTN                  1015
#define IDC_QUANTITY                    1015
#define IDC_NAMELIST                    1015
#define IDC_ZIP_BOX                     1015
#define IDC_BIRTH_DATE_BOX              1017
#define IDC_AGE_BOX                     1018
#define IDC_BTN_PROCESS                 1021
#define IDC_COMBO_AUTHORIZER            1022
#define IDC_EDIT_NUMBER                 1023
#define IDC_ADD                         1024
#define IDC_BILL_DATE                   1024
#define IDC_EDIT_AMOUNT                 1025
#define IDC_PAY_DATE                    1025
#define IDC_EDIT_CC_STATUS              1026
#define IDC_QUOTE_NOTES_COMBO           1026
#define IDC_DOWN                        1027
#define IDC_TOTALNUM                    1027
#define IDC_EDIT_AUTHCODE               1027
#define IDC_STATEMENT_NOTE_COMBO        1028
#define IDC_EDIT_STATEMENT_NOTES        1029
#define IDC_PACKAGE_CHECK               1030
#define IDC_BALANCE_FILTER_COMBO        1030
#define IDC_PACKAGE_COUNT               1031
#define IDC_PACKAGE_COUNT_LABEL         1032
#define IDC_PACKAGE_ORIGINAL_CURRENT_COUNT_LABEL 1033
#define IDC_LOCFILTER                   1034
#define IDC_PACKAGE_TOTAL_COUNT_LABEL   1034
#define IDC_BILLFILTER                  1035
#define IDC_PACKAGE_ORIGINAL_CURRENT_COUNT 1035
#define IDC_QUOTE_EXP_DAY_LABEL         1036
#define IDC_NEW_BILL                    1037
#define IDC_PACKAGE_TOTAL_COUNT         1037
#define IDC_NEW_PAYMENT                 1038
#define IDC_PACKAGE_TOTAL_COST_LABEL    1038
#define IDC_PRINT_HISTORY               1039
#define IDC_OPEN_FORM                   1039
#define IDC_PACKAGE_TOTAL_COST          1039
#define IDC_PREVIEW_STATEMENT           1040
#define IDC_PRINT_FORM                  1040
#define IDC_PACKAGE_CURRENT_BALANCE_LABEL 1040
#define IDC_APPLY_MANAGER               1041
#define IDC_NEW_QUOTE                   1041
#define IDC_PACKAGE_CURRENT_BALANCE     1041
#define IDC_SHOW_INS_BALANCE            1042
#define IDC_QUOTE_EXPIRE_DATE_LABEL     1042
#define IDC_SHOW_PACKAGES               1043
#define IDC_PACKAGE_ORIGINAL_CURRENT_AMOUNT_LABEL 1043
#define IDC_OUTSIDE_LAB_CHECK           1044
#define IDC_RESPONSIBLE_PARTY           1044
#define IDC_PACKAGE_ORIGINAL_CURRENT_AMOUNT 1044
#define IDC_SHOW_QUOTES                 1045
#define IDC_PACKAGE_SHOW_INITIAL_VALUES 1045
#define IDC_FROM                        1046
#define IDC_PTS_TO_BE_BILLED            1046
#define IDC_EMNS_TO_BE_BILLED           1046
#define IDC_TO                          1047
#define IDC_GLASSES_ORDER_HISTORY       1047
#define IDC_SEARCH_BILLING              1048
#define IDC_RUNCONFIG                   1049
#define IDC_STMTPREVIEW                 1050
#define IDC_LABEL_POS                   1050
#define IDC_LABEL_DESIG                 1051
#define IDC_LABEL1                      1052
#define IDC_LABEL2                      1053
#define IDC_LABEL3                      1054
#define IDC_LABEL4                      1055
#define IDC_LABEL5                      1056
#define IDC_CLEAR                       1056
#define IDC_LABEL6                      1057
#define IDC_LABEL8                      1059
#define IDC_LABEL10                     1061
#define IDC_LABEL11                     1062
#define IDC_LABEL12                     1063
#define IDC_LABEL13                     1064
#define IDC_LABEL14                     1065
#define IDC_LABEL18                     1069
#define IDC_LABEL19                     1070
#define IDC_LABEL22                     1073
#define IDC_FROM_LABEL                  1073
#define IDC_TO_LABEL                    1074
#define IDC_LOCATION_LABEL              1081
#define IDC_COMBO_CATEGORY              1083
#define IDC_CASH_DRAWER_LIST            1084
#define IDC_CHECK_DEFAULT               1087
#define IDC_RADIO_PAPER                 1087
#define IDC_CHECK_DEFAULT_FOR_ME        1088
#define IDC_EDIT_PAYMENT                1090
#define IDC_EDIT_YSHIFT                 1090
#define IDC_EXTRA_TEXT                  1090
#define IDC_EDIT_ANESTH_MINUTES         1090
#define IDC_EDIT_YSCALE                 1091
#define IDC_EDIT_FACILITY_MINUTES       1091
#define IDC_EDIT_ASSISTING_MINUTES      1092
#define IDC_EDIT_STATE                  1093
#define IDC_COORDINATOR_COMBO           1094
#define IDC_COMBO                       1095
#define IDC_COMBO_BILLS                 1095
#define IDC_COMBO_CHARGES               1096
#define IDC_EDIT_DESCRIPTION            1097
#define IDC_PROGRESS                    1097
#define IDC_EDIT_FONT                   1097
#define IDC_SHOW_ALL                    1097
#define IDC_EDIT_C                      1098
#define IDC_EDIT_CURRENT_DATE           1098
#define IDC_EDIT_MINI                   1098
#define IDC_EDIT_ACCTNUM_OR_CCNAMEONCARD 1098
#define IDC_EDIT_A                      1099
#define IDC_EDIT_FIRST_DATE             1099
#define IDC_RIGHT                       1099
#define IDC_SHOW_PACKAGE_INFO           1099
#define IDC_EDIT_CHECKNUM_OR_CCEXPDATE  1099
#define IDC_EDIT_ID                     1100
#define IDC_EDIT_NOTES                  1100
#define IDC_EDIT_TOTAL                  1100
#define IDC_CASHSELECTONE               1100
#define IDC_EDIT_SPECIFIC               1100
#define IDC_EDIT_MEDICAID_CODE          1100
#define IDC_PCC_TITLE                   1100
#define IDC_LEFT                        1100
#define IDC_QUOTE_EXP_DAYS              1100
#define IDC_REMEMBER_QUOTE_COL_WIDTHS   1100
#define IDC_EDIT_ANESTH_HOURS           1100
#define IDC_HL7_BILL_PREVIEW            1100
#define IDC_EDIT_PATIENT_ID             1101
#define IDC_EDIT_AUTHORIZATION          1101
#define IDC_CASHUNSELECTALL             1101
#define IDC_EDIT_PRE_DETAIL             1101
#define IDC_EDIT_UNABLE_TO_WORK_FROM    1101
#define IDC_STATEMENT_NOTES             1101
#define IDC_DETAILED                    1101
#define IDC_QUOTE_USE_EXP_CHECK         1101
#define IDC_EDIT_FACILITY_HOURS         1101
#define IDC_EDIT_BANKNUM_OR_CCAUTHNUM   1101
#define IDC_EDIT_B                      1102
#define IDC_CASHUNSELECTONE             1102
#define IDC_EDIT_POST_DETAIL            1102
#define IDC_EDIT_HOSPITALIZED_FROM      1102
#define IDC_SUMMARY                     1102
#define IDC_EDIT_ASSISTING_HOURS        1102
#define IDC_EDIT_BANKNAME_OR_CCCARDNUM  1102
#define IDC_CHECKSELECTALL              1103
#define IDC_EDIT_REFERENCE_NUMBER       1103
#define IDC_REPORT_TITLE                1103
#define IDC_BYPATIENT                   1103
#define IDC_CASH_RECEIVED               1103
#define IDC_EDIT_DATE                   1104
#define IDC_CHECKSELECTONE              1104
#define IDC_EDIT_AUTHORIZATION_NUMBER   1104
#define IDC_SUBREP_TITLE                1104
#define IDC_BYLOCATION                  1104
#define IDC_CHANGE_GIVEN                1104
#define IDC_EDIT_PATIENT_NAME           1105
#define IDC_DEFAULT_EXPDAYS             1105
#define IDC_EDIT_BOX_19                 1105
#define IDC_BYPROVIDER                  1105
#define IDC_CHECKUNSELECTONE            1106
#define IDC_EDIT_UNABLE_TO_WORK_TO      1106
#define IDC_PRAC_OTHER_PHONE            1106
#define IDC_CREDITSELECTALL             1107
#define IDC_EDIT_HOSPITALIZED_TO        1107
#define IDC_DELETE_PAYMENT              1107
#define IDC_INSURANCE_COMPANIES         1107
#define IDC_CREDITSELECTONE             1108
#define IDC_EDIT_CHARGES                1108
#define IDC_DESCRIPTION_COMBO           1108
#define IDC_CREDITUNSELECTALL           1109
#define IDC_PROVIDER_COMBO              1109
#define IDC_CREDITUNSELECTONE           1110
#define IDC_PAY_CATEGORY                1110
#define IDC_EDIT_XSHIFT                 1111
#define IDC_LOCATIONS                   1111
#define IDC_EDIT_ADMISSION_TIME         1111
#define IDC_EDIT_XSCALE                 1112
#define IDC_EDIT_DISCHARGE_TIME         1112
#define IDC_BATCH_PAYMENTS_COMBO        1116
#define IDC_RADIO_ALL_PATIENTS          1117
#define IDC_RADIO_INDIV_PATIENT         1118
#define IDC_SELECTED_PATIENT_COMBO      1119
#define IDC_PAY_AMOUNT                  1120
#define IDC_REM_AMOUNT                  1121
#define IDC_USELETTERHEAD               1122
#define IDC_CALC_PERCENT_BKG            1123
#define IDC_BILL_PREVIEW_BTN            1124
#define IDC_BTN_APPLY_NEW               1124
#define IDC_BTN_ADD                     1124
#define IDC_LABEL_ORIGINAL_AMT          1124
#define IDC_ORIGINAL_AMOUNT             1125
#define IDC_LABEL_PERCENT               1126
#define IDC_PERCENT                     1127
#define IDC_EDIT_CALCULATED_AMOUNT      1128
#define IDC_EDIT_PERCENTAGE             1129
#define IDC_CALCULATED_TOTAL            1130
#define IDC_CALC_PERCENT                1131
#define IDC_CURRENCY_SYMBOL             1132
#define IDC_CURRENCY_SYMBOL_APPLY       1133
#define IDC_CURRENCY_SYMBOL_RECEIVED    1133
#define IDC_FORM_TYPE_COMBO             1134
#define IDC_CURRENCY_SYMBOL_GIVEN       1134
#define IDC_SHOW_QUOTE_DESC             1135
#define IDC_SEPARATE_QUOTE_TAX          1136
#define IDC_QUICKBOOKS_BTN              1137
#define IDC_DEFAULT_EXPIRES_CHECK       1137
#define IDC_CLAIM_HISTORY               1138
#define IDC_SHOW_PROC_DESCRIPTIONS      1138
#define IDC_REMIT                       1139
#define IDC_LOCLIST                     1140
#define IDC_PAYMENTDESC                 1141
#define IDC_LIST_DISC_BY_CATEGORY       1141
#define IDC_ADJUSTMENTDESC              1142
#define IDC_SUPERBILL_LIST              1142
#define IDC_REFUNDDESC                  1143
#define IDC_INCLUDE_APPLIES             1143
#define IDC_BILLID_TEXT                 1145
#define IDC_HIDEPREPAYS                 1146
#define IDC_SHOW_LAST_PAY               1147
#define IDC_CURRENCY_LABEL1             1148
#define IDC_SHOW_BILLING_NOTES_ESTATE   1148
#define IDC_CURRENCY_LABEL2             1149
#define IDC_PROV_FORMAT_LIST            1150
#define IDC_BTN_EDIT_PRIOR_AUTH_NUM     1151
#define IDC_HEADER_PROV_FORMAT_LIST     1151
#define IDC_BTN_SHIFT                   1152
#define IDC_BTN_EDIT_CLAIM_DATES        1152
#define IDC_LABEL_DEST_RESP             1153
#define IDC_LABEL_SOURCE_RESP           1154
#define IDC_LABEL_AMOUNT_TO_SHIFT       1155
#define IDC_EDIT_SHIFT_AMOUNT           1156
#define IDC_LABEL_DEST_RESP_AMOUNT      1157
#define IDC_LABEL_SOURCE_RESP_AMOUNT    1158
#define IDC_CURRENCY_SYMBOL_SHIFT       1159
#define IDC_LABEL_DATE_OF_SHIFT         1160
#define IDC_DATE_OF_SHIFT               1161
#define IDC_CRDETAIL_LIST               1163
#define IDC_CHARGE_LIST                 1164
#define IDC_CLOSE_CHRESP                1165
#define IDC_QUOTE_CUSTOM_REPORT_LIST    1166
#define IDC_QUOTE_CUSTOM_REPORT_MAKE_DEFAULT 1167
#define IDC_RESP_COMBO                  1169
#define IDC_MINI_FONT_LABEL             1174
#define IDC_DESCRIPTION                 1175
#define IDC_RADIO_ELECTRONIC            1176
#define IDC_PAT_NAME_LABEL              1176
#define IDC_RADIO_NO_BATCH              1177
#define IDC_USE_OTHER_PHONE             1177
#define IDC_LAST_PAT_PAY_DATE           1181
#define IDC_QUOTE_EXPIRE_DATE           1182
#define IDC_LAST_INS_PAY_DATE           1182
#define IDC_SELECT_PCP                  1186
#define IDC_SELECT_REF_PHYS             1187
#define IDC_GLOBAL_PERIOD_LIST          1188
#define IDC_CUSTOM_DATE1                1189
#define IDC_HIDE_CPT_CODES              1189
#define IDC_USE_QUOTE_DATE              1190
#define IDC_SEARCH_CHECKS               1191
#define IDC_SEARCH_CC                   1192
#define IDC_FILTER_BG                   1193
#define IDC_LIST_BG                     1194
#define IDC_PAY_LIST                    1195
#define IDC_PATIENT_FILTER              1196
#define IDC_PATIENT_FILTER_LIST         1197
#define IDC_TEXT_FILTER                 1198
#define IDC_TEXT_FILTER_SEARCH          1199
#define IDC_CLOSE_BUTTON                1200
#define IDC_TEXT_FILTER_GO              1201
#define IDC_SHOW_ALL_QUOTES             1202
#define IDC_CHECK_SWAP_INS_COS          1203
#define IDC_CHECK_BATCH_CLAIM           1204
#define IDC_BATCH_LIST                  1205
#define IDC_BTN_EDIT_POS_CODES          1206
#define IDC_PURCHASE_DATE               1217
#define IDC_ACCOUNT_LABEL               1219
#define IDC_FROM_ACCOUNT_LABEL          1220
#define IDC_FROM_ACCOUNT_COMBO          1221
#define IDC_TO_ACCOUNT_COMBO            1222
#define IDC_WHAT_TO_ADD_COMBO           1222
#define IDC_TO_ACCOUNT_LABEL            1223
#define IDC_CASH_RECEIVED_LABEL         1223
#define IDC_CHANGE_GIVEN_LABEL          1224
#define IDC_RESPONSIBILITY_LIST         1225
#define IDC_TARGET_TEXT                 1226
#define IDC_ACCEPT_VISA                 1227
#define IDC_ACCEPT_MSTRCARD             1228
#define IDC_ACCEPT_AMEX                 1229
#define IDC_ACCEPT_DISCOVER             1230
#define IDC_STMT_AR_NOTES               1231
#define IDC_THIRTY_DAY_NOTE             1232
#define IDC_SIXTY_DAY_NOTE              1233
#define IDC_NINETY_DAY_NOTE             1234
#define IDC_NINETY_PLUS_NOTE            1235
#define IDC_PURCH_PAT_LIST              1241
#define IDC_REC_TYPE_PAT                1251
#define IDC_REC_PAT_LIST                1253
#define IDC_PURCH_COLOR                 1263
#define IDC_CERT_NUMBER                 1264
#define IDC_CERT_AMOUNT                 1265
#define IDC_CERT_PRICE_EDIT             1265
#define IDC_EXP_DATE                    1266
#define IDC_GC_TYPE_LIST                1267
#define IDC_GENDER_LIST                 1268
#define IDC_PREVIEW_GC                  1268
#define IDC_SINGLEDAY_DATE_BOX          1269
#define IDC_REC_TYPE_UNKNOWN            1269
#define IDC_GC_CANCEL_TRANSFER          1269
#define IDC_PURCH_COLOR2                1270
#define IDC_GC_PROVIDER_LIST            1271
#define IDC_SEARCH_PURCH_DATE           1272
#define IDC_GC_LOCATIONS_LIST           1272
#define IDC_SEARCH_EXP_DATE             1273
#define IDD_HL7_TO_BE_BILLED_DLG        1273
#define IDC_DATA_DATE                   1275
#define IDC_RES_LIST_DATE               1276
#define IDC_TOTAL_TIP_AMT               1277
#define IDC_ADD_TIP_BTN                 1278
#define IDC_BOTTOM_RIGHT_NORMAL         1279
#define IDC_BOTTOM_RIGHT_EXTENDED       1280
#define IDC_SHOW_TIPS_BTN               1281
#define IDC_TIP_LIST                    1282
#define IDC_BTN_SAVE_AND_ADD_NEW        1284
#define IDC_OPEN_GC_TYPES               1285
#define IDC_PURCH_BY                    1290
#define IDC_REC_BY                      1291
#define IDC_GC_AMT                      1292
#define IDC_GC_USED                     1293
#define IDC_GC_BALANCE                  1294
#define IDC_BTN_PRINT                   1295
#define IDC_GC_TYPE                     1295
#define IDC_BTN_CANCEL                  1297
#define IDC_GC_SEARCH_COLOR1            1297
#define IDC_GC_SEARCH_COLOR3            1298
#define IDC_BTN_UNAPPLY                 1299
#define IDC_NEW_GC_TYPE                 1299
#define IDC_GC_CERTIFICATE_NUMBER       1299
#define IDC_DELETE_GC_TYPE              1301
#define IDC_GC_TYPE_NAME                1303
#define IDC_GC_TYPE_VALUE_EDIT          1304
#define IDC_GC_TYPE_EXP                 1305
#define IDC_GC_TYPE_DAYS                1306
#define IDC_ADD_NEW_PURCHASER           1307
#define IDC_GC_TYPE_RECHARGE            1307
#define IDC_ADD_NEW_RECEIVER            1308
#define IDC_EXP_DATE_CHECK              1309
#define IDC_RECHARGE_FILTER             1311
#define IDC_GC_RECHARGE_LIST            1312
#define IDC_GC_INCLUDE_OTHERS           1314
#define IDC_FILTER_HIDE_BALANCES        1316
#define IDC_FILTER_HIDE_EXPIRED         1317
#define IDC_LIST                        1321
#define IDC_DRAWER_LIST                 1321
#define IDC_NEW_DRAWER                  1322
#define IDC_CLOSE_DRAWER                1323
#define IDC_SYS_CASH                    1325
#define IDC_X                           1326
#define IDC_CANCEL                      1326
#define IDC_SYS_CHECK                   1326
#define ID_CANCEL                       1327
#define IDC_SYS_CHARGE                  1327
#define IDC_BTN_APPLY                   1328
#define IDC_CHECK                       1328
#define IDC_ADD_PAYMENT                 1328
#define IDC_SYS_GIFT                    1328
#define IDC_DRAWER_NAME_LABEL           1329
#define IDC_USER_CASH                   1330
#define IDC_USER_CHECK                  1331
#define IDC_BTN_PREVIEW                 1332
#define IDC_USER_CHARGE                 1332
#define IDC_USER_GIFT                   1333
#define IDC_SYS_TOTAL                   1334
#define IDC_COLOR                       1335
#define IDC_FINANCIAL_BKG               1335
#define IDC_USER_TOTAL                  1335
#define IDC_OPEN_AMT_LABEL              1336
#define IDC_USER_DRAWER_COLOR1          1337
#define IDC_CASH_DRAWER_LABEL           1338
#define IDC_LABEL_BALANCE_DUE           1339
#define IDC_LABEL_PREPAYMENTS           1340
#define IDC_LINKED_PREPAY_LIST          1340
#define IDC_LABEL_TOTAL_BALANCE         1341
#define IDC_BTN_NEW_PREPAY              1341
#define IDC_LABEL_CHARGES               1342
#define IDC_CHECK_SHOW_UNLINKED_PREPAYS 1342
#define IDC_LABEL_ADJUSTMENTS           1343
#define IDC_PREPAY_LINK_BTN             1343
#define IDC_INCLUDE_CLOSED              1343
#define IDC_LABEL_PRI_ADJ               1344
#define IDC_LABEL_NET_CHARGES           1344
#define IDC_EDIT_DRAWER                 1344
#define IDC_LABEL_PAYMENTS              1345
#define IDC_GO_TO_PURCHASER             1345
#define IDC_LABEL_REFUNDS               1346
#define IDC_EXPORTSTYLE                 1346
#define IDC_COMBO_DESCRIPTION           1346
#define IDC_PROVSELECTOR                1346
#define IDC_COMBO_PRINTERS              1346
#define IDC_GO_TO_RECEIVER              1346
#define IDC_LABEL_PRI_REF               1347
#define IDC_LABEL_NET_PAYMENTS          1347
#define IDC_COMBO_PROVIDER              1347
#define IDC_LABEL_SEC_ADJ               1348
#define IDC_COMBO_INSURANCE             1348
#define IDC_LABEL_TER_ADJ               1349
#define IDC_COMBO_CARD_NAME             1349
#define IDC_LABEL_SEC_REF               1350
#define IDC_COMBO_PLACEOFSERVICE        1351
#define IDC_LABEL_TER_REF               1351
#define IDC_TIPS_IN_DRAWER              1351
#define IDC_COMBO_LOCATION              1352
#define IDC_ANESTH_START_TIME           1352
#define IDC_ANESTH_END_TIME             1353
#define IDC_BTN_TOGGLE_INDIV_BATCH      1353
#define IDC_COMBO_SRGY                  1354
#define IDC_CODE_LABEL                  1354
#define IDC_FACILITY_START_TIME         1354
#define IDC_COMBO_CPT                   1355
#define IDC_FACILITY_END_TIME           1355
#define IDC_COMBO_PRODUCTS              1356
#define IDC_ASSISTING_START_TIME        1356
#define IDC_NXCOLORCTRL2                1357
#define IDC_COMBO_BILL_TO               1357
#define IDC_ASSISTING_END_TIME          1357
#define IDC_NXCOLORCTRL3                1358
#define IDC_LABEL_TOTAL                 1359
#define IDC_NXCOLORCTRL6                1359
#define IDC_LABEL_TOTAL_OUTSIDE         1360
#define IDC_NXCOLORCTRL10               1360
#define IDC_MFC42_DATE                  1360
#define IDC_NXCOLORCTRL7                1361
#define IDC_MSVCRT_DATE                 1361
#define IDC_MSVCRT40_DATE               1362
#define IDC_COMBO_GIFT                  1362
#define IDC_COMBO_QUOTE                 1363
#define IDC_RADIO_PAYMENT               1363
#define IDC_DATCN20_DATE                1363
#define IDC_RADIO_ADJUSTMENT            1364
#define IDC_COMBO_CASE_HISTORY          1364
#define IDC_RADIO_REFUND                1365
#define IDC_COMBO_EMR                   1365
#define IDC_BTN_OK                      1366
#define IDC_CHECK_PREPAYMENT            1367
#define IDC_RADIO_NONE_REQUIRED         1367
#define IDC_RADIO_CASH                  1368
#define IDC_RADIO_PERCENT_REQUIRED      1368
#define IDC_RADIO_CHECK                 1369
#define IDC_RADIO_FLAT_FEE_REQUIRED     1369
#define IDC_RADIO_CHARGE                1370
#define IDC_FILTER_CODES                1370
#define IDC_EDIT_DEPOSIT_PERCENTAGE     1370
#define IDC_RADIO_GIFT_CERT             1371
#define IDC_LABEL_DISCOUNTS             1371
#define IDC_EDIT_DEPOSIT_FLAT_FEE       1371
#define IDC_TOP_LABEL                   1371
#define IDC_START_LABEL                 1372
#define IDC_BTN_APPLY_DISCOUNT_TO_ALL   1372
#define IDC_END_LABEL                   1373
#define IDC_COMBO_APPOINTMENTS          1373
#define IDC_NXCOLORCTRL5                1374
#define IDC_BILLING_2_COLOR_1           1374
#define IDC_BTN_ADVANCED_DISCOUNTING    1374
#define IDC_COMBO_GLASSES_ORDERS        1375
#define IDC_LABEL_D                     1376
#define IDC_EDIT_TOTAL_ANESTH_MINUTES   1376
#define IDC_LABEL_BANKNAME_OR_CCCARDNUM 1376
#define IDC_LABEL_B                     1377
#define IDC_EDIT_TOTAL_ASSISTING_MINUTES 1377
#define IDC_LABEL_ACCTNUM_OR_CCNAMEONCARD 1377
#define IDC_NXCOLORCTRL9                1378
#define IDC_LABEL_BOX_19                1378
#define IDC_LABEL_C                     1379
#define IDC_RADIO_REPEAT_PACKAGE        1379
#define IDC_LABEL_BANKNUM_OR_CCAUTHNUM  1379
#define IDC_LABEL_A                     1380
#define IDC_EDIT_TOTAL_FACILITY_MINUTES 1380
#define IDC_RADIO_MULTIUSE_PACKAGE      1380
#define IDC_PACKAGE_LIST                1380
#define IDC_LABEL_UB92_BOX44_OVERRIDE   1380
#define IDC_LABEL_CHECKNUM_OR_CCEXPDATE 1380
#define IDC_LABEL_E                     1381
#define IDC_CHECK_SEND_CORRESPONDENCE   1381
#define IDC_LABEL_CCCARDTYPE            1381
#define IDC_NXCOLORCTRL16               1382
#define IDC_REPORT_LIST                 1382
#define IDC_LABEL_HCFA_BOX_13           1382
#define IDC_NXCOLORCTRL1                1383
#define IDC_NXCOLORCTRL17               1383
#define IDC_NXCOLORCTRL8                1384
#define IDC_NXCOLORCTRLST4              1384
#define IDC_REC_COLOR                   1384
#define IDC_NXCOLORCTRL19               1384
#define IDC_GC_SEARCH_COLOR2            1384
#define IDC_USER_DRAWER_COLOR2          1384
#define IDC_NXCOLORCTRL11               1385
#define IDC_ADJ_GROUPCODE_LABEL         1385
#define IDC_NXCOLORCTRL12               1386
#define IDC_VOID_GC                     1386
#define IDC_ADJ_REASON_LABEL            1386
#define IDC_NXCOLORCTRL13               1387
#define IDC_TRANSFER_GC_BALANCE         1387
#define IDC_QUOTE_LIST                  1388
#define IDC_NXCOLORCTRL14               1388
#define IDC_QUOTES_BKG                  1389
#define IDC_NXCOLORCTRL15               1389
#define IDC_NXCOLORCTRL18               1390
#define IDC_FILTER_HIDE_VOIDED          1391
#define IDC_BILL_EDIT_BTN               1392
#define IDC_RECHARGE_EXPIRED            1392
#define IDC_BILL_MERGE_BTN              1393
#define IDC_EDITEXP                     1393
#define IDC_CHECK_HIDE_ZERO_BALANCES    1394
#define IDC_CHECK_HIDE_VOIDED_ITEMS     1395
#define IDC_BILL_DELETE_BTN             1397
#define IDC_PRINT_MULTI_RESP            1399
#define IDC_UB92_BOX_44_LIST            1406
#define IDC_ADJ_GROUPCODE               1407
#define IDC_ADJ_REASON                  1408
#define IDC_DISCHARGE_STATUS_COMBO      1408
#define IDC_LABEL_UB_BOX_14             1408
#define IDC_BTN_EDIT_DISCHARGE_STATUS   1409
#define IDC_EDIT_UB_BOX_14              1409
#define IDC_DISCHARGE_STATUS_LIST       1410
#define IDC_LABEL_UB_BOX_15             1410
#define IDC_LABEL_INFO1                 1411
#define IDC_BTN_ADD_DISCHARGE_STATUS    1411
#define IDC_EDIT_UB_BOX_15              1411
#define IDC_LABEL_INFO2                 1412
#define IDC_BTN_DELETE_DISCHARGE_STATUS 1412
#define IDC_DEDUCT_LEFT_TO_MEET         1413
#define IDC_LABEL_INFO3                 1413
#define IDC_LABEL_BILLA                 1414
#define IDC_PAT_CO_INSURANCE            1414
#define IDC_OOP_LEFT_TO_MEET            1415
#define IDC_DEDUCT_LEFT_TO_MEET_STATIC  1416
#define IDC_PAT_CO_INSURANCE_STATIC     1417
#define IDC_OOP_LEFT_TO_MEET_STATIC     1418
#define IDC_CHECK_BATCH                 1419
#define IDC_CHECK_SHIFT                 1419
#define IDC_USE_SIGNATURE               1419
#define IDC_USE_GUARANTOR               1419
#define IDC_LABEL_RESP                  1419
#define IDC_OPEN_CARE_CREDIT            1419
#define IDC_REWARD_POINTS_TOTAL_STATIC  1419
#define IDC_SHOW_REFUNDS                1420
#define IDC_USE_WITSIGNATURE            1420
#define IDC_CHECK_ADJUST                1420
#define IDC_SHOW_FOOTER                 1420
#define IDC_REWARD_POINTS_TOTAL_EDIT    1420
#define IDC_CHECK_INCREASE              1421
#define IDC_USE_70_VERSION              1421
#define IDC_AFFIL_AMT                   1421
#define IDC_USE_EMAIL                   1422
#define IDC_OPEN_CARECREDIT             1422
#define IDC_COMBINE_BILL_BALANCES       1422
#define IDC_AFFIL_NOTES                 1422
#define IDC_AFFIL_DATE                  1423
#define IDC_RADIO_EMPLOYMENT            1425
#define IDC_RADIO_AUTO_ACCIDENT         1426
#define IDC_RADIO_OTHER_ACCIDENT        1427
#define IDC_EMN_CHARGE_LIST             1427
#define IDC_RADIO_NONE                  1428
#define IDC_QUOTE_COMBO                 1428
#define IDC_LABEL_BILL_ID               1429
#define IDC_QUOTE_CHARGE_LIST           1429
#define IDC_LABEL_BILL_DATE             1430
#define IDC_RADIO_BILL_QUOTE_AND_EMN    1430
#define IDC_RADIO_BILL_QUOTE_ONLY       1431
#define IDC_RADIO_BILL_EMN_CHARGES_ONLY 1432
#define IDC_RADIO_BILL_EMN_CHARGES_NO_QUOTE 1433
#define IDC_QUOTE_LABEL                 1434
#define IDC_REPORT_LABEL                1436
#define IDC_COMBO_REPORT                1437
#define IDC_SALES_RECEIPT_CHARGES       1439
#define IDC_SALES_RECEIPT_PAYMENTS      1440
#define IDC_SALES_RECEIPT_PRINT         1441
#define IDC_DISCOUNT_CATEGORY_LIST      1443
#define IDC_USE_CUSTOM                  1444
#define IDC_CUSTOM_DISCOUNT_CAT         1445
#define IDC_COUPON_SELECT_LIST          1448
#define IDD_APPLY_LIST_DLG              1450
#define IDC_APPLY_LIST                  1451
#define IDC_SHOW_EXPIRED                1451
#define IDC_BTN_SHOW_SUGGESTED_SALES    1452
#define IDC_LABEL_BALANCE               1454
#define IDC_DATALIST_SUGGESTED_SALES    1454
#define IDC_TAB_SUGGESTED_SALES         1455
#define IDC_PATIENT_TOTAL_LABEL         1456
#define IDC_DATALIST_SUGGESTED_SALES_ALL 1456
#define IDC_PAID_OUTSIDE_LABEL          1457
#define IDC_SUGGESTED_SALES_REASON      1457
#define IDC_DISCOUNT_TOTAL_LABEL        1458
#define IDC_LABEL_AVAILABLE_APPLY       1459
#define IDC_DISCOUNT_BILL_PERCENT_OFF   1460
#define IDC_DISCOUNT_BILL_DOLLAR_DISCOUNT 1461
#define IDC_BILL_DISCOUNT_USE_CUSTOM    1462
#define IDC_BILL_DISCOUNT_CATEGORY_LIST 1463
#define IDC_BILL_CUSTOM_DISCOUNT_CAT    1464
#define IDC_GC_TYPE_REWARDS_CHECK       1465
#define IDC_GC_TYPE_REWARD_POINTS_EDIT  1466
#define IDC_GC_TYPE_REWARDS_CATEGORY_LIST 1467
#define IDC_GC_TYPE_EDIT_DISCOUNT_CATEGORIES 1468
#define IDC_COMBO_DESIGNATION           1469
#define IDC_LABEL_LINE                  1469
#define IDC_INFO_TEXT                   1471
#define IDC_EDIT_QUOTE_NOTES            1472
#define IDC_BTN_UP                      1474
#define IDC_LABEL_QUOTE_NOTE_1          1474
#define IDC_CREDIT_CARD_SETUP           1475
#define IDC_ADD_CARD                    1477
#define IDC_REMOVE_CARD                 1478
#define IDC_EDIT_CARD_COLOR             1480
#define IDC_CC_COLOR                    1481
#define IDC_CC_AUTH_EXP_DATE            1482
#define IDC_CARD_TYPE_LIST              1483
#define IDC_CC_AUTH_NUMBER              1484
#define IDC_NOTES_EDIT                  1485
#define IDC_CC_AUTH_NAME                1485
#define IDC_CC_COLOR2                   1486
#define IDC_LABEL                       1487
#define IDC_CC_COLOR3                   1487
#define IDC_BTN_EDIT_TEXT               1488
#define IDC_LABEL29                     1488
#define IDC_LABEL142                    1488
#define IDC_TOTAL_TRANS_AMT             1488
#define IDC_LABEL30                     1489
#define IDC_BTN_SAVE_COPY               1489
#define IDC_PROCESS_CC_CARD             1489
#define IDC_LABEL31                     1490
#define IDC_CC_COLOR4                   1490
#define IDC_ALIGN                       1491
#define IDC_LABEL32                     1491
#define IDC_CC_AUTH_TIP_LIST            1491
#define IDC_LABEL33                     1492
#define IDC_MESSAGE_LABEL               1492
#define IDC_RELOAD                      1493
#define IDC_LABEL34                     1493
#define IDC_AUTHORIZE_MANUALLY          1493
#define IDC_RESTORE                     1494
#define IDC_AUTHORIZATION_NUMBER        1494
#define IDC_AUTH_NUMBER_LABEL           1496
#define IDC_AVAL_PAYS_LIST              1498
#define IDC_AVAIL_PAYS_LIST             1498
#define IDC_CASH_DRAWER_ALL_LOCATIONS   1499
#define IDC_CASH_DRAWER_CURRENT_LOCATION 1500
#define IDC_SEND_PAPERWORK_CHECK        1501
#define IDC_PWK_TYPE                    1502
#define IDC_PWK_TX                      1503
#define IDC_PWK_TX_LABEL                1504
#define IDC_EBILLINGCOLOR               1505
#define IDC_PWK_TYPE_LABEL              1505
#define IDC_OPEN_PHYSICAL_CASH_DRAWER   1506
#define IDC_SEND_TEST_RESULT_CHECK      1506
#define IDC_ADVANCED_SETTINGS_GROUPBOX  1507
#define IDC_TEST_RESULTS_ID_LABEL       1507
#define IDC_DISCOUNT_CATEGORY_GROUPBOX  1508
#define IDC_TEST_RESULTS_TYPE_LABEL     1508
#define IDC_EXTRA_CHARGE_BKG            1508
#define IDC_TEST_RESULT_ID_COMBO        1509
#define IDC_TEST_RESULT_TYPE_COMBO      1510
#define IDC_EDIT_TEST_RESULT            1511
#define IDC_TEST_RESULT_LABEL           1512
#define IDC_BTN_EXTRA_CHARGE_INFO       1512
#define IDC_NXDL_ITEM_LIST              1514
#define ID_BTN_CLOSE                    1516
#define IDC_LBL_INFO                    1517
#define IDC_NXCOLOR_BG                  1518
#define IDC_PAYMENT_CATEGORY_LABEL      1520
#define IDC_SUPERVISING_PROV_COMBO      1521
#define IDC_SUPERVISING_PROVIDER_LABEL  1522
#define IDC_RADIO_ADD_DISCOUNTS         1523
#define IDC_CASE_HISTORY_BILL_LABEL     1523
#define IDC_RADIO_REPLACE_DISCOUNTS     1524
#define IDC_CASE_HISTORY_BILL_COMBO     1524
#define IDC_UP                          1525
#define IDC_RADIO_SKIP_DISCOUNTS        1525
#define IDC_AFFIL_LIST_LABEL            1525
#define IDC_CASHSELECTEDLIST            1526
#define IDC_EXISTING_DISCOUNT_LABEL     1526
#define IDC_AFFIL_STATUS_LABEL          1526
#define IDC_CHECKAVAILLIST              1527
#define IDC_EXISTING_DISCOUNT_CATEGORY_LABEL 1527
#define IDC_AFFIL_AMT_LABEL             1527
#define IDC_CHECKSELECTEDLIST           1528
#define IDC_CHECK_MANUAL_REVIEW         1528
#define IDC_AFFIL_NOTE_LABEL            1528
#define IDC_CREDITAVAILLIST             1529
#define IDC_CREDITSELECTEDLIST          1530
#define IDC_DATE_FILTER_TYPE_LIST       1531
#define IDC_CHARGE_DISCOUNT_LIST        1531
#define IDC_CDD_ADD_DISCOUNT            1532
#define IDC_NEW_DISCOUNT_PERCENT_OFF    1533
#define IDC_NEW_DISCOUNT_DOLLAR_DISCOUNT 1534
#define IDC_CDD_DELETE_DISCOUNT         1535
#define IDC_NEW_DISCOUNT_DISCOUNT_CATEGORY 1536
#define IDC_NEW_DISCOUNT_CUSTOM_DESC    1537
#define IDC_NEW_DISCOUNT_USE_CUSTOM     1539
#define IDC_OK                          1541
#define IDC_DIAG_CODE_UNSELECTED_LIST   1546
#define IDC_ADV_DISCOUNT_CATEGORY_LIST  1550
#define IDC_ADV_DISCOUNT_DISCOUNT_LIST  1551
#define IDC_ADV_DISCOUNT_DELETE_ALL     1552
#define IDC_DISCOUNT_BILL_APPLY_USE_UNIT_COST 1554
#define IDC_DISCOUNT_BILL_USE_LINE_TOTAL 1555
#define IDC_NEW_DISCOUNT_CALCULATE_UNIT_COST 1556
#define IDC_NEW_DISCOUNT_CALCULATE_LINE_TOTAL 1557
#define ID_OK_BTN                       1558
#define IDC_CC_SECURITY_CODE            1558
#define IDC_CASHAVAILLIST               1560
#define IDC_CASHSELECTALL               1561
#define IDC_CHECKUNSELECTALL            1562
#define IDC_CC_BILLING_ZIP              1563
#define IDC_OS_VERSION                  1564
#define IDC_CHECK_GC_TYPE_INACTIVE      1565
#define IDC_CASH_SEL                    1566
#define IDC_CC_BILLING_ADDRESS          1566
#define IDC_CASH_AVAIL                  1567
#define IDC_LABEL_RESPONSIBILITY        1568
#define IDC_CHECK_SEL                   1568
#define IDC_SAVE_AND_PROCESS_LATER      1568
#define IDC_CHECK_AVAIL                 1569
#define IDC_CARD_IS_PRESENT             1569
#define IDC_CREDIT_SEL                  1570
#define IDC_CARD_SWIPED                 1570
#define IDC_CREDIT_AVAIL                1571
#define IDC_PROCESS_CC                  1571
#define IDC_TOTAL_SEL                   1572
#define IDC_CASE_HISTORY_LINK_LABEL     1572
#define IDC_TOTAL_AVAIL                 1573
#define IDC_CLAIM_TYPE_COMBO            1573
#define IDC_LABEL_PRI_PAY               1574
#define IDC_CLAIM_TYPE_LABEL            1574
#define IDC_LABEL_SEC_PAY               1575
#define IDC_STMT_DETAILED               1575
#define IDC_LABEL_TER_PAY               1576
#define IDC_STMT_SUMMARY                1576
#define IDC_PRIOR_AUTH_TYPE_COMBO       1576
#define IDC_LABEL_TTL_PATRESP           1577
#define IDC_BILLING_TAB_LIST            1577
#define IDC_CONDITION_DATE_COMBO        1577
#define IDC_LABEL_TTL_PRIRESP           1578
#define IDC_HCFA_BOX_13_COMBO           1578
#define IDC_LABEL_TTL_SECRESP           1579
#define IDC_BTN_CLOSE_DISCOUNT_OVERVIEW_DLG 1579
#define IDC_LABEL_TTL_TERRESP           1580
#define IDC_GROUP1                      1581
#define IDC_TAB                         1582
#define IDC_LABEL_PATRESP               1583
#define IDC_LABEL_PRIRESP               1584
#define IDC_LABEL_SECRESP               1585
#define IDC_LABEL_TERRESP               1586
#define IDC_DISPLAY_APPLIES             1587
#define IDC_DISPLAY_PAYMENTS            1588
#define IDC_BTN_EDIT_CODES              1589
#define IDC_LABEL_OUTSIDE_DISCOUNTS     1590
#define IDC_OUTSIDE_DISCOUNT_TOTAL_LABEL 1591
#define IDC_BILLINGTAB_REMCOLWIDTH      1592
#define IDC_ACCOUNTS_LIST               1593
#define IDC_CLOSE_HISTORY_LIST          1594
#define IDC_REF_PHYS_LIST               1594
#define IDC_FIN_CLOSE_BKG               1595
#define IDC_BTN_CLOSE_DIALOG            1596
#define IDC_BTN_PERFORM_CLOSE           1597
#define IDC_LABEL_CURRENT_CLOSE_DATE    1598
#define IDC_SHOWESTATEMENTPATIENTSELECT 1599
#define IDC_INCLUDEPAIDCHARGES_ON_BILLS 1601
#define IDC_DIAG_CODE_SELECTED_LIST     1603
#define IDC_DIG_CODE_LABEL              1604
#define IDC_BILL_CHANGE_SERVICE_CODE_LIST 1605
#define IDC_COLOR_BILL_CHANGE_SERVICE_CODE 1606
#define IDC_PERCENT_LABEL               1606
#define IDC_BILL_AFFILIATE_LIST         1607
#define IDC_AFFIL_STATUS                1608
#define IDC_KEYBOARD_CARD_SWIPE         1608
#define IDC_CARD_INPUT                  1609
#define IDC_TEXT_SWIPE                  1613
#define IDC_NXCOLOR_CARD_SWIPE          1614
#define IDC_ASSISTING_TIME_LABEL1       1615
#define IDC_ASSISTING_TIME_LABEL2       1616
#define IDC_ASSISTING_TIME_LABEL3       1617
#define IDC_ASSISTING_TIME_LABEL4       1618
#define IDC_ASSISTING_TIME_LABEL5       1619
#define IDC_ASSISTING_TIME_LABEL6       1620
#define IDC_ASSISTING_TIME_LABEL7       1621
#define IDC_CHARGE_RESP_LIST            1622
#define IDC_CHARGESPLITNXCOLOR          1623
#define IDC_CHG_SPLIT_INS_LABEL         1624
#define IDC_VERIFY_BILL                 1625
#define IDC_USE_PRACNAME                1637
#define IDC_USE_PROVNAME                1638
#define IDC_USE_PATCOMMA                1639
#define IDC_USE_PATFORWARD              1640
#define IDC_USE_DIAGCODES               1641
#define IDC_NO_USE_DIAGCODES            1642
#define IDC_USE_PRACADDRESS             1643
#define IDC_USE_PROVADDRESS             1644
#define IDC_LABEL_BILLORPAYMENT         1685
#define IDC_LABEL_CHARGE                1686
#define IDC_RADIO_PAPER_BATCH           1786
#define IDC_RADIO_ELECTRONIC_BATCH      1787
#define IDC_EDIT_AGE                    1788
#define IDC_RADIO_UNBATCHED             1789
#define IDC_DAYS_OLD                    1789
#define IDC_ADMINISTRATOR               1791
#define IDC_PATIENT_COORD               1800
#define IDC_PAID_TO_OTHERS              1801
#define IDC_DISCOUNT                    1802
#define IDC_PATIENT_COORD_FORMAT        1803
#define IDC_TRANSACTION                 1812
#define IDC_LOCFILTERCHK                1813
#define IDC_BILL_FILTER_CHECK           1814
#define IDC_AVERY2                      1834
#define IDC_DEFAULTFORMAT               1835
#define IDC_ESTATEMENTFORMAT            1836
#define IDC_CAP_ON_PRINT                1850
#define IDC_PRACTICE_DATE               1861
#define IDD_PACKAGE_DLG                 1862
#define IDC_SEARCH_BILLING_TAB_INFO_ICON 2257
#define IDD_HCFA                        2464
#define IDD_STATEMENT_SETUP             2481
#define IDD_CALCULATE_PERCENTAGE_DLG    2485
#define IDD_SHIFT_INS_RESPS_DLG         2581
#define IDD_EDIT_CHARGERESP_DLG         2600
#define IDD_SEARCH_CHECKS_DLG           2601
#define IDR_BILLING_POPUP               2602
#define IDD_PENDING_QUOTES_DLG          2604
#define IDD_CHOOSE_TWO_QB_ACCTS_DLG     2608
#define IDD_STATEMENT_AR_NOTES_DLG      2612
#define IDD_CHOOSE_DRAG_RESP_DLG        2616
#define IDD_GC_ENTRY_DLG                2617
#define IDD_GC_SEARCH_DLG               2618
#define IDR_PAYMENT_TIPS                2621
#define IDD_GC_TYPE_DLG                 2623
#define IDD_GC_RECHARGE_DLG             2625
#define IDD_EDIT_DRAWERS_DLG            2631
#define IDD_USER_DRAWER_DLG             2633
#define IDD_MANAGE_QUOTE_PREPAYS_DLG    2635
#define IDD_ANESTHESIA_TIME_PROMPT_DLG  2637
#define IDD_BILLING_2_DLG               2671
#define IDD_PACKAGE_USE_SELECTION_DLG   2673
#define IDD_EDIT_DISCHARGE_STATUS_DLG   2675
#define IDB_CARE_CREDIT_LOGO            2678
#define IDD_CARE_CREDIT_MARKING_DLG     2680
#define IDB_CARE_CREDIT_LOGO_SMALL      2682
#define IDD_EMN_QUOTE_SELECTION_DLG     2683
#define IDD_SALES_RECEIPT_CONFIG        2685
#define IDD_DISCOUNT_CATEGORIES         2687
#define IDD_COUPON_SELECT               2689
#define IDD_BILLING_SUGGESTED_SALES     2691
#define IDD_DISCOUNT_BILL_DLG           2695
#define IDD_EDIT_CREDITCARDS_DLG        2703
#define IDD_PAYMENTECH_PROCESS_CC_DLG   2705
#define IDD_APPLY_TO_REFUND             2707
#define IDD_BILLING_EXTRA_CHARGE_INFO_DLG 2709
#define IDD_SERIALIZED_ITEMS            2711
#define IDD_NEW_DISCOUNT_DLG            2719
#define IDD_ADV_DISCOUNT_DLG            2817
#define IDD_PROCESS_CC_DLG              2823
#define IDD_BILL_DISCOUNT_OVERVIEW_DLG  2920
#define IDD_FINANCIAL_CLOSE_DLG         2925
#define IDD_CHANGE_BILL_SEVICE_CODE_DLG 2930
#define IDD_BILL_SELECT_DIGs_CODE_DLG   2932
#define IDD_KEYBOARD_CARD_SWIPER        2934
#define IDD_CHARGE_SPLIT_DLG            2936
#define IDD_INSURANCE_REVERSAL_DLG      2938
#define IDD_BILL_CLAIM_FIELDS_DLG       2940
#define IDD_BILL_DIAG_SEARCH_DLG        2942
#define IDD_EDIT_BILL_LAB_TEST_CODES_DLG 2944
#define IDD_SEARCH_BILLING_TAB_DLG      2946
#define IDD_ICCP_PAYMENT_PROFILE        2948
#define IDD_CREDIT_CARD_RECEIPT_PROMPT  2950
#define IDD_UB04_ADD_FIELDS             2956
#define IDD_INSURANCE_CLAIM_DATES_DLG   2957
#define IDC_HL7_BILL_RELOAD             3004
#define IDC_NXDL_BATCH_PAYMENTS         6210
#define IDC_REVERSAL_SHOW_ALL_DATES     6211
#define IDC_EDIT_INVOICE_NUMBER         6212
#define IDC_LABEL_INVOICE_NUMBER        6213
#define IDC_RESUBMISSION_CODE_LABEL     6214
#define IDC_BTN_CLAIM_FIELDS            6215
#define IDC_CLAIM_FIELD_LIST            6216
#define IDC_HIDE_CHARGEBACKS            6226
#define IDC_BILL_STATUS_NXCOLOR         6235
#define IDC_BILL_STATUS_STATIC          6236
#define IDC_BILL_STATUS_COMBO           6237
#define IDC_BILL_STATUS_CONFIG_BTN      6238
#define IDC_BILL_STATUS_NOTE_STATIC     6239
#define IDC_BILL_STATUS_NOTE_COMBO      6240
#define IDC_BILL_STATUS_NOTE_EDIT       6241
#define IDC_BILL_STATUS_NOTE_CONFIG_BTN 6242
#define IDC_BILLING_DIAG_SEARCH         6244
#define IDC_BILLING_DIAG_LIST           6245
#define IDC_BILLING_DIAG_UP             6246
#define IDC_BILLING_DIAG_DOWN           6247
#define IDC_BILLING_DIAG_QUICKLIST      6248
#define IDC_BILLING_DIAG_NEXCODE        6249
#define IDC_BILLING_DIAG_COLOR          6250
#define IDC_EDIT_TEST_CODES_BACKGROUND_NXCOLOR 6251
#define IDC_EDIT_TEST_CODES_LIST        6252
#define IDC_EDIT_TEST_CODES_ADD_BTN     6253
#define IDC_EDIT_TEST_CODES_DELETE_BTN  6254
#define IDC_EDIT_TEST_CODES_HIDE_INACTIVE_CHECK 6255
#define IDC_SEARCH_GC_LIST              6256
#define IDC_EDIT_BILLING_SEARCH_TEXT    6257
#define IDC_BTN_SEARCH_BILLING          6258
#define IDC_SEARCH_RESULTS_LABEL        6259
#define IDC_SEARCH_BKG                  6260
#define IDC_BTN_FIND_PREV               6261
#define IDC_BTN_FIND_NEXT               6262
#define IDC_GC_TYPE_PRICE_STATIC        6263
#define IDC_GC_TYPE_PRICE_EDIT          6264
#define IDC_GC_TYPE_VALUE_STATIC        6265
#define IDC_CERT_VALUE_STATIC           6266
#define IDC_CERT_VALUE_EDIT             6267
#define IDC_CERT_PRICE_STATIC           6268
#define IDC_GC_SEARCH_LIST              6269
#define IDC_LABEL_GIFT_CERT_NUMBER      6270
#define IDC_LABEL_GC_VALUE              6271
#define IDC_LABEL_GC_BALANCE            6272
#define IDC_LABEL_GC_PURCH_DATE         6273
#define IDC_LABEL_GC_EXP_DATE           6274
#define IDC_EDIT_GIFT_CERT_NUMBER       6275
#define IDC_EDIT_GC_VALUE               6276
#define IDC_EDIT_GC_BALANCE             6277
#define IDC_EDIT_GC_PURCH_DATE          6278
#define IDC_EDIT_GC_EXP_DATE            6279
#define IDC_BTN_CLEAR_GC                6280
#define IDC_GC_HISTORY_LIST             6281
#define IDC_REFUND_TO_EXISTING_GC_RADIO 6282
#define IDC_REFUND_TO_NEW_GC_RADIO      6283
#define IDC_GC_SEARCH_LABEL             6284
#define IDC_ICCP_PAYMENT_PROFILE_BACKGROUND 6285
#define IDC_ADD_ICCP_PAYMENT_PROFILE    6286
#define IDC_DELETE_ICCP_PAYMENT_PROFILE 6287
#define IDC_ICCP_PAYMENT_PROFILE_LIST   6288
#define IDC_PAYMENT_PROFILE_HIDE_EXPIRED 6289
#define IDC_MERCHANT_COPY_CHECK         6292
#define IDC_CUSTOMER_COPY_CHECK         6293
#define IDC_LABEL_CC_TRANSACTION_TYPE   6294
#define IDC_RADIO_SWIPE_CARD            6295
#define IDC_RADIO_CARD_NOT_PRESENT      6296
#define IDC_RADIO_DO_NOT_PROCESS        6297
#define IDC_RADIO_CC_REFUND_TO_ORIGINAL_CARD 6298
#define IDC_LABEL_CC_MERCHANT_ACCT      6299
#define IDC_EDIT_CC_ZIPCODE             6300
#define IDC_LABEL_CC_CARD_ON_FILE       6301
#define IDC_LABEL_CC_ZIPCODE            6302
#define IDC_LABEL_CC_LAST4              6303
#define IDC_EDIT_CC_LAST4               6304
#define IDC_CHECK_ADD_CC_TO_PAYMENT_PROFILE 6305
#define IDC_CC_MERCHANT_ACCT_COMBO      6306
#define IDC_CC_CARD_ON_FILE_COMBO       6307
#define IDC_HL7_BILLS                   6308
#define IDC_PROVIDER_LIST_FILTER        6309
#define IDC_LOCATION_LIST_FILTER        6310
#define IDC_ENABLE_FILTERS              6311
#define IDC_UB04_OCCURENCE              6312
#define IDC_UB04_CONDITIONAL            6313
#define IDC_UB04_VALUECODE              6314
#define IDC_UB04_OCCURENCESPAN          6315
#define IDC_UB04_REMARK                 6317
#define IDC_UB04_BOX80_LABEL            6318
#define IDC_UB04_REMARK_LABEL           6318
#define IDC_UB04_VALUECODE_LABEL        6319
#define IDC_UB04_OCCURENCE_LABEL        6320
#define IDC_UB04_CONDITION_LABEL        6321
#define IDC_UB04_OCCURENCESPAN_LABEL    6323
#define IDC_IC_FIRST_VISIT_DATE         6323
#define IDC_IC_INITIAL_TREATMENT_DATE   6324
#define IDC_LABEL_ORIGINAL_REFNO        6324
#define IDC_IC_LAST_SEEN_DATE           6325
#define IDC_IC_CHRONIC_CONDITION_DATE   6326
#define IDC_IC_LAST_XRAY_DATE           6327
#define IDC_IC_HEARING_PRESC_DATE       6328
#define IDC_IC_ASSUMED_CARE_DATE        6329
#define IDC_IC_RELINQUISHED_CARE_DATE   6330
#define IDC_IC_RELINQUISHED_CARE_DATE2  6331
#define IDC_IC_ACCIDENT_DATE            6331
#define ID_SEARCHCHECKS_GOTOPATIENT     40001
#define ID_SEARCHCHECKS_GOTOPAYMENT     40002
#define ID_PAYMENTTIPS_ADD              40003
#define ID_PAYMENTTIPS_DELETE           40004

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        2961
#define _APS_NEXT_COMMAND_VALUE         40005
#define _APS_NEXT_CONTROL_VALUE         6325
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
