//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Contacts.rc
//
#define IDD_ADDRESS                     103
#define IDR_MAINFRAME                   128
#define IDD_CHANGE_TYPE                 130
#define IDD_USER_CHANGE_PASS_DLG        251
#define IDD_USER_PERMISSION_DLG         486
#define IDR_COMMISSION_POPUP            610
#define IDD_ATTENDANCE_USER_SETUP       622
#define IDD_ATTENDANCE_CUSTOM_DATE_RANGE_SETUP 624
#define IDD_ATTENDANCE_OPTIONS          626
#define IDD_PASSWORD_CONFIG_DLG         629
#define IDD_CONFIGURE_PERMISSION_TEMPLATES 631
#define IDD_NEXERX_REGISTER_PRESCRIBER_DLG 634
#define IDD_CONFIGURE_PROVIDER_TYPES    636
#define IDD_REF_PHYS_PROCS_DLG          699
#define IDD_COMMISSION_SETUP_DLG        799
#define IDC_LAST_NAME_BOX               1000
#define IDC_DUPLICATES                  1005
#define IDC_NEW                         1005
#define IDC_DELETE                      1006
#define IDC_FIRST_NAME_BOX              1007
#define IDC_CURRENT_LIST                1007
#define IDC_MIDDLE_NAME_BOX             1008
#define IDC_DETACH                      1008
#define IDC_CHANGES_LIST                1008
#define IDD_USERGROUP_SECURITY          1009
#define IDC_CURRENT_FOLDER              1009
#define IDD_GROUP_SECURITY              1010
#define IDC_ADDRESS1_BOX                1011
#define IDC_ADDRESS2_BOX                1012
#define IDC_CITY_BOX                    1013
#define IDC_STATE_BOX                   1014
#define IDC_ZIP_BOX                     1015
#define IDC_PROVIDERLOCATION_COMBO      1016
#define IDC_CONTACTLOCATION_COMBO       1016
#define IDC_EMPLOYER_BOX                1019
#define IDC_ADD                         1024
#define IDC_HOME_PHONE_BOX              1027
#define IDC_EXT_PHONE_BOX               1028
#define IDC_CELL_PHONE_BOX              1029
#define IDC_PAGER_PHONE_BOX             1030
#define IDC_ATTENDANCE_ENTRY_NOTES      1030
#define IDC_EMAIL_BOX                   1032
#define IDC_WORK_PHONE_BOX              1033
#define IDC_EMERGENCY_FIRST_NAME        1034
#define IDC_RELATION_BOX                1035
#define IDC_EMERGENCY_LAST_NAME         1036
#define IDC_OTHERWORK_BOX               1037
#define IDC_OTHERHOME_BOX               1038
#define IDC_NATIONALNUM_BOX             1039
#define IDC_ACCOUNT_BOX                 1040
#define IDC_REFPHYSID_BOX               1041
#define IDC_UPIN_BOX                    1042
#define IDC_OTHER_PHONE_BOX             1043
#define IDC_FEDID_BOX                   1044
#define IDC_MEDICARE_BOX                1045
#define IDC_BCBS_BOX                    1046
#define IDC_MEDICAID_BOX                1047
#define IDC_WORKCOMP_BOX                1048
#define IDC_DEA_BOX                     1049
#define IDC_LICENSE_BOX                 1050
#define IDC_OTHERID_BOX                 1051
#define IDC_CON_CUSTOM1_BOX             1052
#define IDC_DATE                        1052
#define IDC_ATTENDANCE_DATE_START       1052
#define IDC_CON_CUSTOM2_BOX             1053
#define IDC_ATTENDANCE_DATE_END         1053
#define IDC_LABEL3                      1054
#define IDC_TAXONOMY_CODE               1054
#define IDC_LABEL4                      1055
#define IDC_NPI_BOX                     1055
#define IDC_LABEL5                      1056
#define IDC_LABEL6                      1057
#define IDC_LABEL7                      1058
#define IDC_ACCOUNT_NAME                1058
#define IDC_LABEL8                      1059
#define IDC_LABEL9                      1060
#define IDC_LABEL10                     1061
#define IDC_OHIP_SPECIALTY              1062
#define IDC_GROUP_NPI_BOX               1063
#define IDC_LABEL19                     1070
#define IDC_ID_LABEL12                  1072
#define IDC_LABEL22                     1073
#define IDC_LABEL23                     1074
#define IDC_MOVE_PREVIOUS_YEAR          1074
#define IDC_LABEL26                     1075
#define IDC_MOVE_NEXT_YEAR              1075
#define IDC_CLAIM_PROV_LABEL            1076
#define IDC_EDIT_CUSTOM_DATE_RANGE      1076
#define IDC_LABEL28                     1077
#define IDC_MOVE_PREVIOUS_USER          1077
#define IDC_LABEL27                     1078
#define IDC_MOVE_NEXT_USER              1078
#define IDC_LABEL35                     1079
#define IDC_CON_CUSTOM3_BOX             1080
#define IDC_CON_CUSTOM4_BOX             1081
#define IDC_FAX_BOX                     1082
#define IDC_LABEL_TAXONOMY_CODE         1083
#define IDC_DEFAULT_COST_EDIT           1084
#define IDC_INCOMPLETE                  1085
#define IDC_LABEL_NPI                   1085
#define IDC_COMPLETED                   1086
#define IDC_LABEL_OHIP_SPECIALTY        1086
#define IDC_SAVE_PASSWORD_CHK           1087
#define IDC_LABEL_GROUP_NPI             1087
#define IDC_INACTIVITY_CHK              1088
#define IDC_ADMINISTRATOR_CHECK         1089
#define IDC_EDIT                        1090
#define IDC_CHECK_PASSWORD_EXPIRES_NEXT_LOGIN 1090
#define IDC_PHONE_BKG                   1091
#define IDC_ALL                         1091
#define IDC_EMERG_BKG                   1092
#define IDC_CUSTOM_BKG                  1093
#define IDC_DEMOGRAPHICS_BKG            1094
#define IDC_EXTRAINFO_BKG               1095
#define IDC_NUM_PATIENTS_REF_BOX        1096
#define IDC_NUM_PROSPECTS_REF_BOX       1097
#define IDC_CONTACTS_BKG6               1098
#define IDC_ACCRUED_ROW_COLOR           1099
#define IDC_USER_NAME_BOX               1100
#define IDC_AVAILABLE_ROW_COLOR         1100
#define IDC_USER_PASS_BOX               1101
#define IDC_TOTAL_USED_ROW_COLOR        1101
#define IDC_USER_PASS_VER_BOX           1102
#define IDC_BALANCE_ROW_COLOR           1102
#define IDC_MARRIAGE_OTHER_BOX          1103
#define IDC_CUSTOM4_LABEL               1106
#define IDC_CUSTOM3_LABEL               1107
#define IDC_DEFAULT_COST_LABEL          1108
#define IDC_CUSTOM2_LABEL               1109
#define IDC_CUSTOM1_LABEL               1110
#define IDC_NOTES                       1111
#define IDC_DATE_OF_HIRE                1115
#define IDC_DATE_OF_TERM                1116
#define IDC_BTN_ADD                     1124
#define IDC_STATIC_SUN                  1136
#define IDC_STATIC_MON                  1137
#define IDC_STATIC_TUE                  1138
#define IDC_STATIC_WED                  1139
#define IDC_STATIC_THU                  1140
#define IDC_STATIC_FRI                  1141
#define IDC_PREFIX_LIST                 1142
#define IDC_STATIC_SAT                  1142
#define IDC_INTERESTS_BKG               1191
#define IDC_INTERESTS_BKG2              1193
#define IDC_FOLLOWUP_BKG3               1194
#define IDC_HISTORY_BKG                 1266
#define IDC_REMOVE_PROV                 1292
#define IDC_LIST_TODO                   1311
#define IDC_LIST                        1321
#define IDC_CANCEL                      1326
#define IDC_BACK                        1327
#define IDC_REFERRED_PATS               1376
#define IDC_REFERRED_PROSPECTS          1377
#define IDC_SELECT_ONE_USER             1426
#define IDC_SELECT_ALL_USERS            1427
#define IDC_UNSELECT_ONE_USER           1428
#define IDC_UNSELECT_ALL_USERS          1429
#define IDC_ENABLE_UNATTACHED           1435
#define IDC_NAME_LABEL                  1477
#define IDC_LABEL29                     1488
#define IDC_LABEL30                     1489
#define IDC_LABEL31                     1490
#define IDC_LABEL32                     1491
#define IDC_LABEL33                     1492
#define IDC_CONTACT_IMAGE               1492
#define IDC_LABEL34                     1493
#define IDC_LABEL_DEFLOCATION           1494
#define IDC_SSN_BOX                     1562
#define IDC_BDATE_BOX                   1563
#define IDC_EDIT_PREFIXES               1566
#define IDC_TITLE_BOX                   1655
#define IDC_ATTENDANCE_OPTION_COLOR_CHOOSER_CTRL 1759
#define IDC_DOCUMENTS                   1918
#define IDC_CREATE                      1948
#define IDC_CONTACT_TYPE                1958
#define IDC_PATCOORD_CHECK              1964
#define IDC_LABEL24                     1965
#define IDC_DEFAULT_CHECK               1966
#define IDC_TYPE_BKG                    1967
#define IDC_REFPHYS_BTN                 1968
#define IDC_EMPLOYEE_BTN                1969
#define IDC_SUPPLIER_BTN                1970
#define IDC_OTHER_BTN                   1971
#define IDC_MAIN_BTN                    1972
#define IDC_PERMISSIONS_BTN             1973
#define IDC_PROPERTIES_BTN              1974
#define IDC_EDITSECURITYGROUPS_BTN      1975
#define IDC_ATTENDANCE_SETUP            1976
#define IDC_FAX_LABEL                   1979
#define IDC_EMAIL_BTN                   1980
#define IDC_METHOD_LABEL                1982
#define IDC_METHOD_BOX                  1983
#define IDC_ACCOUNT_NAME_LABEL          1984
#define IDC_PROVIDER_BTN                1985
#define IDC_USER_BTN                    1986
#define IDC_SHOW_COMMISSION             1990
#define IDC_MALE                        1991
#define IDC_FEMALE                      1992
#define IDC_COMBO_PALMSYNC              1993
#define IDC_SAVE_AND_EDIT               1994
#define IDC_AMA_SPECIALTY_LIST          1994
#define IDC_SAVE_AND_RESUME             1995
#define IDC_VIEW                        2001
#define IDC_INACTIVITY_BOX              2005
#define IDC_TREE_SECURITY               2007
#define IDC_LIST_PERMISSIONS            2008
#define IDC_EDIT_SECURITYOBJECT_DESCRIPTION 2011
#define IDC_MEMBEROF_LIST               2012
#define IDC_BTN_EDITGROUPPERMISSIONS    2013
#define IDC_BTN_USERGROUP_HELP          2016
#define IDC_BTN_GROUPSECURITY_HELP      2018
#define IDC_BTN_NEW_TEMPLATE            2019
#define IDC_BTN_DELETE_TEMPLATE         2020
#define IDC_BTN_COPY_FROM               2021
#define IDC_EDIT_NEWPERMTEMP_NAME       2022
#define IDC_EDIT_NEWPERMTEMP_DESCRIPTION 2023
#define IDC_LIST_CP_COPYFROM            2024
#define IDC_LIST_NPT_COPYFROM           2025
#define IDD_NEW_PERMISSION_TEMPLATE     2026
#define IDC_BTN_IMPORT_PERMS_FROM       2026
#define IDD_COPY_PERMISSIONS            2027
#define IDC_NURSE_CHECK                 2027
#define IDC_ANESTHESIOLOGIST            2028
#define IDC_ATTENDANCE_DATE_OF_HIRE     2030
#define IDC_CHECK_CONTACT_INACTIVE      2032
#define IDC_CONTACTS_NOTES_SHOW_GRID    2033
#define IDC_CHECK_SEND_COMPANY_ON_CLAIM 2033
#define IDC_CONTACTS_FOLLOWUP_SHOW_GRID 2034
#define IDC_EXPIRE_CHK                  2035
#define IDC_EDIT_PW_EXPIRES             2036
#define IDC_SELECT_ONE_CITEM            2043
#define IDC_SELECT_ALL_CITEMS           2044
#define IDC_REMOVE_ONE_CITEM            2045
#define IDC_REMOVE_ALL_CITEMS           2046
#define IDC_COMM_COLOR                  2048
#define IDC_QUICK_COMM                  2050
#define IDC_QUICK_COMM_AMOUNT           2051
#define IDC_APPLY_QUICK_COMM            2052
#define IDC_COMM_COLOR2                 2053
#define IDC_APPLY_PERCENTAGE            2054
#define IDC_COMM_COLOR5                 2054
#define IDC_APPLY_SELECTED              2055
#define IDC_SHOW_PROCS                  2056
#define IDC_CLEAR_SELECTED              2056
#define IDC_COMM_COLOR3                 2057
#define IDC_REF_PHYS_PROCS              2058
#define IDC_APPLY_QUICK_RULE            2058
#define IDC_COMM_COLOR4                 2058
#define IDC_PROC_LIST_CAPTION           2059
#define IDC_CLEAR_SELECTED_RULES        2059
#define IDC_HIDESHOW_RULES              2059
#define IDC_SHOW_PROC_WARNING           2060
#define IDC_REMOVE_SELECTED_RULE        2060
#define IDC_PROC_WARNING_TEXT           2061
#define IDC_APPLY_SELECTED_RULE         2061
#define IDC_DATE_OF_HIRE_LABEL          2062
#define IDC_APPLY_AMOUNT                2062
#define IDC_BTN_CLEAR_PERMISSIONS       2063
#define IDC_DATE_OF_TERM_LABEL          2063
#define IDC_BTN_CONFIGURE_PASSWORD_STRENGTH 2064
#define IDC_PERM_COUPLING_CHECK         2065
#define IDC_NUM_PATIENTS_REF_LABEL      2068
#define IDC_NUM_PROSPECTS_REF_LABEL     2069
#define IDC_CLAIM_PROVIDER              2070
#define IDC_WND_PLACEHOLDER             2071
#define IDC_ADV_SETUP                   2072
#define IDC_COMM_RULE_SETUP             2073
#define IDC_AVAIL_PROV_LIST             2075
#define IDC_AVAIL_LIST                  2076
#define IDC_ADD_PROV                    2077
#define IDC_ADD_RULE                    2078
#define IDC_REMOVE_RULE                 2079
#define IDC_RULE_NAME                   2080
#define IDC_START_APPLY_DATE            2081
#define IDC_END_APPLY_DATE              2082
#define IDC_START_BASED_DATE            2083
#define IDC_END_BASED_DATE              2084
#define IDC_COMMISSION_PERCENTAGE       2085
#define IDC_DOLLAR_THRESSHOLD           2086
#define IDC_MONEY_THRESHOLD             2086
#define IDC_COMMISSION_RULE_LIST        2087
#define IDC_COMMISSION_PERCENTAGE2      2088
#define IDC_COMMISSION_AMOUNT           2088
#define IDC_SHOW_OUTDATED               2090
#define IDC_SHOW_OUTDATED_RULES         2091
#define IDC_SHOW_OUT_DATED_RULES        2092
#define IDC_SHOW_INACTIVE_PROV          2093
#define IDC_COMMISSION_TITLE            2093
#define IDC_EDIT_BIOGRAPHY              2094
#define IDC_SELECT_IMAGE                2095
#define IDC_RICH_TEXT_CTRL              2095
#define IDC_CONTACT_BIOGRAPHY_COLOR     2096
#define IDC_CLEAR_IMAGE                 2096
#define IDC_ATTENDANCE_BKG              2097
#define IDC_DEPARTMENT_FILTER           2098
#define IDC_ATTENDANCE_BKG2             2099
#define IDC_ATTENDANCE_USER_LIST        2101
#define IDC_USERS_COMBO                 2102
#define IDC_ATTENDANCE_LIST             2105
#define IDC_RADIO_YEAR                  2106
#define IDC_RADIO_MONTH                 2107
#define IDC_RADIO_CUSTOM                2108
#define IDC_RADIO_DAY                   2109
#define IDC_ATTENDANCE_YEAR             2110
#define IDC_CONFIGURE_DEPARTMENTS       2111
#define IDC_DEPARTMENT_LIST             2112
#define IDC_REQUEST_VACATION            2112
#define IDC_ADD_DEPARTMENT              2113
#define IDC_USER_SETUP                  2113
#define IDC_DELETE_DEPARTMENT           2114
#define IDC_ATTENDANCE_OPTIONS          2114
#define IDC_ASSIGN_USERS_TO_DEPARMENTS  2115
#define IDC_LOCK_PAYROLL                2115
#define IDC_USERS_NOT_IN_DEPARTMENT     2116
#define IDC_USERS_IN_DEPARTMENT         2117
#define IDC_ASSIGN_USERS_BACKGROUND     2121
#define IDC_CONFIGURE_DEPARTMENTS_BACKGROUND 2122
#define IDC_USER_SETUP_BACKGROUND       2124
#define IDC_VACATION_ALLOWANCE          2125
#define IDC_SICK_ALLOWANCE              2126
#define IDC_ATTENDANCE_ENTRY_BACKGROUND 2127
#define IDC_EFFECTIVE_YEAR              2127
#define IDC_APPROVED_BY                 2128
#define IDC_VACATION_BONUS              2128
#define IDC_RAD_PER_MONTH               2129
#define IDC_ATTENDANCE_ENTRY_BACKGROUND2 2129
#define IDC_RAD_WEEKLY                  2130
#define IDC_NUMBER_OF_WEEKS             2131
#define IDC_NUMBER_OF_TIMES_PER_MONTH   2132
#define IDC_VACATION_HOURS              2133
#define IDC_OTHER_HOURS                 2134
#define IDC_DATE_FILTER_START           2134
#define IDC_DATE_FILTER_END             2135
#define IDC_RESET_DATE_FILTER           2136
#define IDC_HOURS_WORKED                2136
#define IDC_SAVE_ATTENDANCE_APPOINTMENT 2137
#define IDC_DATE_CURRENT_PAY_PERIOD     2137
#define IDC_REQUEST_ATTENDANCE_APPOINTMENT 2138
#define IDC_ATTENDANCE_USER_TYPE        2138
#define IDC_ATTENDANCE_TODAY_BTN        2138
#define IDC_DEPARTMENT_SELECT           2139
#define IDC_UNPAID_HOURS                2139
#define IDC_STATIC_YEAR                 2141
#define IDC_VACATION_AVAILABLE          2142
#define IDC_DEFAULT_VACATION_ALLOWANCE  2143
#define IDC_VACATION_USED               2144
#define IDC_DEFAULT_SICK_ALLOWANCE      2144
#define IDC_VACATION_BALANCE            2145
#define IDC_SHOW_ATTENDANCE_GRID        2145
#define IDC_VACATION_ACCRUED            2146
#define IDC_ATTENDANCE_OPTIONS_BKG      2146
#define IDC_STATIC_HOURS_WORKED         2150
#define IDC_STATIC_VACATION             2151
#define IDC_DEPARTMENT_LABEL            2152
#define IDC_EMAIL_ON_APPROVE            2155
#define IDC_EMAIL_MANAGERS              2155
#define IDC_EMAIL_ON_DENY               2156
#define IDC_ATTENDANCE_TODO_CATEGORY    2157
#define IDC_FLOATING_HOLIDAY            2158
#define IDC_ATTENDANCE_VACATION_TYPE    2158
#define IDC_ATTENDANCE_SICK_TYPE        2159
#define IDC_ATTENDANCE_OTHER_TYPE       2160
#define IDC_ATTENDANCE_INPUT_DATE       2160
#define IDC_DATE_THROUGH_LABEL          2161
#define IDC_ATTENDANCE_PAID_TYPE        2161
#define IDC_ATTENDANCE_UNPAID_TYPE      2162
#define IDC_ATTENDANCE_USER_NOTES       2164
#define IDC_EDIT_PASSWORD_MIN_CHARACTERS 2165
#define IDC_EDIT_PASSWORD_MIN_LETTERS   2166
#define IDC_EDIT_PASSWORD_MIN_NUMBERS   2167
#define IDC_EDIT_PASSWORD_MIN_UPPERCASE 2168
#define IDC_EDIT_PASSWORD_MIN_LOWERCASE 2169
#define IDC_PASS_CONFIG_BKG             2170
#define IDC_SAMPLE_PASSWORD_LABEL       2171
#define IDC_ATTENDANCE_USER_SETUP_OK    2172
#define IDC_EDIT_LOGIN_BANNER           2172
#define IDC_PROV_SPI                    2173
#define IDC_SPI_LABEL                   2175
#define IDC_AMA_SPECIALTY_LABEL         2176
#define IDC_NPI_LABEL                   2177
#define IDC_UNLOCK_USER                 2179
#define IDC_UNLOCK_LABEL                2180
#define IDC_CHECK_PREVENT_REUSE_PASSWORDS 2181
#define IDC_EDIT_LAST_PASSWORD_COUNT    2182
#define IDC_RADIO_TIERED_COMMISSIONS    2183
#define IDC_RADIO_BASIC_COMMISSIONS     2184
#define IDC_CHECK_IGNORE_SHOP_FEE       2185
#define IDC_COMMISSION_QUICK_SETUP_LABEL 2186
#define IDC_SET_COMMISSION_LABEL_1      2187
#define IDC_SET_COMMISSION_LABEL_2      2188
#define IDC_CURRENT_COMMISSION_LABEL    2189
#define IDC_TIERED_RULE_LIST            2190
#define IDC_ADV_NOTE_LABEL              2191
#define IDC_AMOUNT_SOLD_LABEL           2192
#define IDC_RADIO_THIS_TIER_ONLY        2193
#define IDC_RADIO_ALL_LOWER_TIERS       2194
#define IDC_APPLY_COMMISSION_LABEL      2195
#define IDC_BASED_ON_DATE_RANGE_LABEL   2196
#define IDC_BASED_ON_DATE_START_LABEL   2197
#define IDC_BASED_ON_DATE_TO_LABEL      2198
#define IDC_BASED_ON_DATE_END_LABEL     2199
#define IDC_APPLY_DATE_RANGE_LABEL      2200
#define IDC_SUMMARY_LIST                2201
#define IDC_PERMS_AVAIL_LIST            2202
#define IDC_PERMS_SEL_LIST              2203
#define IDC_PERMS_ONE_RIGHT             2208
#define IDC_PERMS_ONE_LEFT              2209
#define IDC_PERMS_PICK_LIST             2214
#define IDC_USER_SEC_CONFIGURE_GROUPS   2216
#define IDC_PERMS_CLEAR                 2217
#define IDC_CONGIFURE_GROUPS            2219
#define IDC_GOTO_OTHER                  2221
#define IDC_TECHNICIAN_CHECK            2222
#define IDC_AFFILIATE_PHYS              2225
#define IDC_OPTICIAN_CHECK              2226
#define IDC_COMBO_PROVID                2228
#define IDC_BTN_REGISTER_PRESCRIBER     2230
#define IDC_NXC_REGISTER_PRESCRIBER_TOP 2231
#define IDC_NXC_REGISTER_PRESCRIBER_BOTTOM 2232
#define IDC_STATIC_PRESCRIBER_REGISTRATION_INFO 2233
#define IDC_FIRST_NAME_BOX_REG          2234
#define IDC_MIDDLE_NAME_BOX_REG         2235
#define IDC_LAST_NAME_BOX_REG           2236
#define IDC_NPI_BOX_REG                 2237
#define IDC_LICENSE_BOX_REG             2238
#define IDC_EMAIL_BOX_REG               2239
#define IDC_WORK_PHONE_BOX_REG          2240
#define IDC_EXT_PHONE_BOX_REG           2241
#define IDC_FAX_BOX_REG                 2242
#define IDC_NXDL_REGISTER_PRESCRIBER_LOCATIONS 2243
#define IDC_CHECK_ALL_RX_LOCATIONS      2244
#define IDC_NXDL_APPLY_SERVICELEVEL     2245
#define IDC_STATIC_APPLY_SERVICELEVEL   2246
#define IDC_DEA_BOX_REG                 2247
#define IDC_DIRECT_ADDRESS_EDIT         2248
#define IDC_DIRECT_ADDRESS_USERS_BUTTON 2249
#define IDC_DIRECT_ADDRESS_LABEL        2250
#define IDC_CONTACTS_BKG7               2251
#define IDC_CONTACT_PROVIDER_TYPES_LABEL 2252
#define IDC_CONTACT_REFERRING_PROVIDER_CHECK 2253
#define IDC_CONTACT_ORDERING_PROVIDER_CHECK 2254
#define IDC_CONTACT_SUPERVISING_PROVIDER_CHECK 2255
#define IDC_CONTACT_CONFIGURE_PROVIDER_TYPES_BUTTON 2256
#define IDC_BTN_SEL_ALL                 2256
#define IDC_STATIC_PROVIDER_TYPE        2257
#define IDC_CONTACTS_PROVIDER_TYPE_INFO 2257
#define IDC_DL_PROVIDER_TYPE            2258
#define IDC_NXCOLOR_CPT                 2259
#define IDC_DL_UNSELECTED_PROVIDERS     2260
#define IDC_DL_SELECTED_PROVIDERS       2261
#define IDC_BTN_SEL_ONE                 2262
#define IDC_BTN_UNSEL_ONE               2263
#define IDC_BTN_UNSEL_ALL               2264
#define IDC_STATIC_CPT_SEL_PROVS        2265
#define IDC_STATIC_CPT_UNSEL_PROVS      2266
#define IDC_CB_AFF_PHYSICIAN_OPTICIAN   2267
#define IDC_CB_REF_PROVIDER             2268
#define IDC_CB_ORD_PROVIDER             2269
#define IDC_CB_SUP_PROVIDER             2270
#define IDC_BTN_APPLY_CHANGES           2271
#define IDC_BTN_CLOSE_CPT_DLG           2272
#define IDC_BTN_CLEAR_TYPES             2273
#define IDC_STATIC_CPT_APPLY_AS         2274
#define IDC_CONFIG_PROVIDER_TYPES_INFO  2275
#define IDC_SEND_REF_PHYS_TO_HL7        2276
#define IDC_ADDTO_ALL_LOCS_CHECK        2277
#define IDC_APPLY_LABEL                 2277
#define IDC_COMMISSION_LABEL            2278
#define IDC_CAPITATION_DISTRIBUTION_TEXT 2278
#define IDC_DOLLAR_TIER_COMMISSION_LABEL 2279
#define IDC_CAPITATION_DISTRIBUTION_EDIT 2279
#define IDC_CAPITATION_TEXT             2281
#define IDD_CONTACTS_GENERAL            2486
#define IDD_CONTACTS_FOLLOW_UP          2487
#define IDD_CONTACTS_NOTES              2488
#define IDD_NEW_CONTACT                 2489
#define IDD_CONTACT_DUPLICATE           2580
#define IDD_COMMISSION_SETUP_WND        6204
#define IDC_COMMISSION_PROV_LIST        6205
#define IDC_COMM_ITEM_TYPE              6206
#define IDC_SEL_PROV_LIST               6206
#define IDC_RULE_ITEM_TYPE              6207
#define IDC_QUICK_RULE_LIST             6208
#define IDC_ADD_RULE_LIST               6209
#define IDC_REMOVE_RULE_LIST            6210
#define IDD_ADV_COMMISSION_SETUP_DLG    6211
#define IDD_COMMISSION_RULE_SETUP_DLG   6212
#define IDD_CONTACT_BIOGRAPHY           6213
#define IDD_CONTACT_SELECT_IMAGE        6214
#define IDD_ATTENDANCE                  6215
#define IDD_ATTENDANCE_ENTRY            6216
#define IDD_CONFIGURE_DEPARMENTS        6217
#define IDD_ASSIGN_USER_DEPARTMENTS     6218
#define ID_COMMISSIONPOPUP_CLEARCOMMISSION 32772
#define ID_COMMISSIONPOPUP_REMOVERULE   32773
#define ID_COMMISSIONPOPUP_ADDRULE_COMMISSIONRULESETUP 32774

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        639
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         2282
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
