//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Emr.rc
//
#define IDC_BACK_TO_EMN                 2
#define IDC_SELECT_SIGNATURE_IMAGE      3
#define IDC_BTN_CLOSE_PROBLEM_DELETE_DLG 3
#define IDC_SAVE_DEFAULT_SIGNATURE      4
#define IDC_ERASE_SIGNATURE_INK         5
#define IDC_CLOSE_SIGNATURE_DIALOG      6
#define IDC_USE_DEFAULT_SIGNATURE       8
#define IDC_PRINT                       50
#define IDC_PRINT_REPORT                51
#define IDC_PATEMR_EDIT_TEMPLATES       52
#define IDD_EMR_TEXT_DLG                663
#define IDD_EMR_SELECT_SERVICE_DLG      687
#define IDR_EMR_POPUP                   871
#define IDD_ACTIVE_EMR_DLG              872
#define IDD_EMR_AUDIT_HISTORY_DLG       876
#define IDD_EMR_MERGE_PRECEDENCE_DLG    886
#define IDD_EMR_MERGE_CONFLICT_DLG      888
#define IDD_EMR_ITEM_ADV_POPUP_DLG      892
#define IDD_PATIENT_NEXEMR              912
#define IDD_EMN_MORE_INFO_DLG           920
#define IDR_NEXEMR_POPUP                921
#define IDD_CONFIGURE_NEXEMR_GROUPS_DLG 922
#define IDD_EMR_CHOOSE_TEMPLATE_DLG     928
#define IDD_EMN_TO_BE_BILLED_DLG        940
#define IDD_EMR_SUMMARY_DLG             955
#define IDD_EMR_WORD_DOCUMENT_LIST_DLG  962
#define IDD_EMR_MOVE_EMN                965
#define IDD_EMR_PROBLEM_LIST_DLG        967
#define IDD_EMR_PROBLEM_EDIT_DLG        969
#define IDD_LOCKMANAGER                 988
#define IDD_LOCK_REMINDER               990
#define IDD_EMR_SEARCH                  992
#define IDC_DIAGS                       1000
#define IDC_BILL                        1001
#define IDD_CONFIGURE_EMR_TABS          1001
#define IDC_MEDICATIONS                 1002
#define IDC_BTN_ADD_CHARGE              1003
#define IDC_BTN_CREATE_BILL             1004
#define IDD_CHOOSE_EMN_CATEGORY_DLG     1004
#define IDC_CUSTOM_RECORDS_LIST         1005
#define IDC_PROCEDURE_COMBO             1005
#define IDC_INFO_LIST                   1005
#define IDC_EMR_LOCK_LIST               1005
#define IDC_NEXEMR_COLUMNS              1005
#define IDC_EXISTING_LIST               1005
#define IDC_EMR_WRITABLE_LIST           1005
#define IDC_EMR_WORD_DOCUMENT_LIST      1005
#define IDC_EMR_SUMMARY_LIST            1005
#define IDC_CONFIG_CATEGORY_LIST        1005
#define IDC_DATEFILTER_TYPE             1005
#define IDC_LIST_EMR_PROBLEMS           1005
#define IDC_LIST_PROBLEM_STATUS         1005
#define IDC_LIST_TEMPLATES              1005
#define IDC_DETAIL_LIST                 1005
#define IDC_EM_CHECKLIST                1005
#define IDC_EM_CONTRIBUTING_DETAIL_LIST 1005
#define IDC_LIST_EMR_TODO_ALARMS        1005
#define IDC_ADD_CHARGE_LIST             1005
#define IDC_EMR_AUDIT_LIST              1005
#define IDC_EMR_ANALYSIS_CONFIG_COMBO   1005
#define IDC_EMN_PROVIDER                1005
#define IDC_EMN_OTHER_PROV_LIST         1005
#define IDC_CONFIGURE_PREFERRED_PROC_LIST 1005
#define IDC_EMR_PROVIDER_COMBO          1006
#define IDC_DATA_LIST                   1006
#define IDC_LIST_UNRESOLVED_DELETED_TODO_ALARMS 1006
#define IDC_EMR_PATIENT_SUMMARY_LIST    1006
#define IDC_LIST_EMR_PROBLEM_HISTORY    1006
#define IDC_EMR_LIST                    1006
#define IDC_LIST_COLLECTIONTEMPLATES    1006
#define IDC_EM_CATEGORY_LIST            1006
#define IDD_EMR_CHARGE_PROMPT_DLG       1006
#define IDC_EMR_ANALYSIS_LIST           1006
#define IDC_EMN_LOCATION                1006
#define IDC_EMN_GROUP_TEMPLT_COMBO      1006
#define IDC_BTN_WRITE_PRESCRIPTIONS     1007
#define IDC_EMN_GROUPS_LIST             1007
#define IDC_MOVE_TO_PATIENT_LIST        1007
#define IDC_BTN_ADD_MEDICATION          1008
#define IDC_LIST_PROBLEM_CHRONICITY     1008
#define IDC_EMN_GROUP_TEMPLT_LIST       1008
#define IDC_STATUS                      1009
#define IDC_BTN_MERGE                   1010
#define IDC_EMN_STATUS                  1010
#define IDC_CHECK_FU                    1011
#define IDC_EMN_SECONDARY               1011
#define IDC_EDIT_FU_NUMBER              1012
#define IDD_NEXEMR_CONFIGURE_COLUMNS    1012
#define IDC_EMN_CHART                   1012
#define IDC_FU_INCREMENT                1013
#define IDC_EMN_AGE                     1013
#define IDC_BTN_MERGE_TO_OTHER          1014
#define IDR_EMR_CSS                     1014
#define IDC_EDIT_EMR_NOTES              1015
#define IDD_EMR_PREVIEW_POPUP           1015
#define IDC_EMN_CATEGORY                1016
#define IDC_VISIT_TYPE                  1017
#define IDC_BTN_EDIT_SERVICES           1019
#define IDC_CHECK_PROCEDURE             1021
#define IDC_PROCEDURE_SCH_LIST          1022
#define IDC_DATE                        1052
#define IDD_CONFIGURE_PREVIEW_DLG       1055
#define IDC_NEW_EMR                     1070
#define IDC_PATIENT_NAME                1073
#define IDC_DATA_TEXTBOX                1075
#define IDC_AGE                         1082
#define IDC_GENDER                      1083
#define IDC_STATUS_LABEL                1084
#define IDC_CLEAR_DETAILS               1086
#define IDC_STATUS_OPEN                 1087
#define IDC_STATUS_FINISHED             1088
#define IDC_EMR_LOCATIONS_COMBO         1089
#define IDC_STATUS_LOCKED               1089
#define IDC_DIAG_DROPDOWN               1090
#define IDC_INK_CTRL_PLACEHOLDER        1090
#define IDC_STATUS_OTHER                1090
#define IDC_AUTO_PROMPT_FOR_SIGNATURE   1091
#define IDC_BKG                         1092
#define IDC_ADD_EMR_ITEMS               1093
#define IDC_BKG2                        1094
#define IDC_BKG3                        1095
#define IDC_BKG4                        1096
#define IDC_BKG5                        1097
#define IDC_RESULT_PROGRESS             1097
#define IDC_BKG8                        1098
#define IDC_DATEFILTER_QUICK            1099
#define IDC_BKG9                        1099
#define IDC_BKG10                       1100
#define IDC_TEMPLATE_LIST               1106
#define IDC_BKG6                        1107
#define IDC_BKG7                        1108
#define IDC_EMN_FROM_DATE               1113
#define IDC_EMN_TO_DATE                 1114
#define IDC_MOVE_EMN_CAT_PRIORITY_UP_BTN 1124
#define IDC_MOVE_EMN_CHART_PRIORITY_UP_BTN 1125
#define IDC_RESULT_PROGRESS_BAR_STATUS  1184
#define IDC_PROBLEM_DATE_FROM           1283
#define IDC_PROBLEM_DATE_TO             1284
#define IDC_NOTES_LABEL                 1307
#define IDC_APPLY                       1325
#define IDC_CPT_CODE_COMBO              1355
#define IDC_EMR_QUOTE_COMBO             1356
#define IDC_NXCOLORCTRL1                1383
#define IDC_NXC_DETAILS                 1384
#define IDC_MOVE_EMN_CAT_PRIORITY_DOWN_BTN 1392
#define IDC_MOVE_EMN_CHART_PRIORITY_DOWN_BTN 1393
#define IDC_EDIT_EMR_TEXT               1527
#define IDC_EMR_TEXT_TITLE              1528
#define IDC_BTN_ZOOM_EMR_TEXT           1529
#define IDC_VISIONWEB_ORDER_STATUS_LIST 1534
#define IDC_DELETE_EMN_COLOR            1570
#define IDC_DIAGCODES_LABEL             1707
#define IDC_EMR_MAKE_DEFAULT            1713
#define IDC_EMR_DEFAULT_FOR             1714
#define IDC_ACTIVE_EMR_LIST             1721
#define IDC_ACTIVE_EMR_PROVIDER_COMBO   1722
#define IDC_ACTIVE_RECORD_COUNT         1723
#define IDC_LIST_COLLECTION_CONFLICTS   1736
#define IDC_STATIC_MERGECONFLICT_DESCRIPTION 1737
#define IDC_BTN_PREV_EMN                1739
#define IDC_BTN_NEXT_EMN                1740
#define IDC_RADIO_SERVICE_CODE          1745
#define IDC_RADIO_PRODUCT               1746
#define IDC_RADIO_QUOTES                1747
#define IDC_EMR_SAVE_DOCS_IN_HISTORY_CHECK 1781
#define IDC_NXC_BUTTONS                 1825
#define IDC_NXC_BUTTONS3                1827
#define IDC_NXC_EMR_BOTTOM              1827
#define IDC_EMR_TREE                    1828
#define IDC_NEW_LIST                    1831
#define IDC_NEXEMR_CONFIGURE_GROUPS     1832
#define IDC_PREFERRED_BG                1833
#define IDC_NEXEMR_LOCK_MANAGER         1833
#define IDC_PREFERRED_BG2               1834
#define IDC_EDIT_EMN_TEMPLATE           1836
#define IDC_EMN_DATE                    1841
#define IDC_EMN_PATIENT_NAME            1843
#define IDC_EMN_GENDER                  1845
#define IDC_EMN_PROCEDURE_COMBO         1846
#define IDC_EMN_PROCEDURE_LIST          1847
#define IDC_EMR_BUTTON_HEADER           1849
#define IDC_NXL_PATIENT_CHART           1851
#define IDC_NXL_NEW_MEDICAL_NOTE        1852
#define IDC_MERGE_TO                    1858
#define IDC_CONFIGURE_BACKGROUND        1862
#define IDC_BTN_PATIENTS_TO_BE_BILLED   1865
#define IDC_MORE_TEMPLATES              1875
#define IDC_BTN_CONFIGURE_TABS          1876
#define IDC_PRODUCT_COMBO               1883
#define IDC_EMNLIST                     1883
#define IDC_STATIC_WORDTEMP             1887
#define IDOK2MERGE                      1888
#define IDCANCEL2MERGE                  1890
#define IDC_PLACEHOLDER                 1892
#define IDC_BTN_EMR_SUMMARY             1893
#define IDC_BTN_EMR_PROBLEM_LIST        1894
#define IDC_BTN_PT_SUMMARY              1895
#define IDC_LIST_PROCEDURE              1911
#define IDC_LIST_PROBLEMS               1913
#define IDC_LIST_PROVIDER               1914
#define IDC_LIST_LOCATION               1915
#define IDC_LIST_EMRFILTER              1916
#define IDC_LIST_SEC_PROVIDER           1917
#define IDC_LIST_OTHER_STATUS           1918
#define IDC_COMBO_CHART                 1919
#define IDC_COMBO_CATEGORIES            1920
#define IDC_BTN_TOGGLE_VIEW_TYPE        1923
#define IDC_EMR_SUMMARY_PREVIEW         1924
#define IDC_BTN_CONFIGURE_SUMMARY       1925
#define IDC_EMR_DOCUMENT_LABEL          1932
#define IDC_MOVE_EMN_INSTRUCTIONS       1933
#define IDC_NXC_PROBLEM_LIST            1938
#define IDC_EDIT_PROBLEM_DESCRIPTION    1939
#define IDC_BTN_EDIT_STATUS_LIST        1940
#define IDC_NXC_PROBLEM_EDIT            1941
#define IDC_BTN_EDIT_CHRONICITY_LIST    1942
#define IDC_CHECK_SHOW_DETAIL_NAME      1943
#define IDC_BTN_EDIT_SNOMED_LIST        1943
#define IDC_CHECK_SHOW_TOPIC_NAME       1944
#define IDC_CHECK_SHOW_EMN_NAME         1945
#define IDC_CHECK_SHOW_EMR_NAME         1946
#define IDC_CHECK_SHOW_PROBLEM_DESC     1947
#define IDC_CHECK_SHOW_DETAIL_DATA      1948
#define IDC_CHECK_SHOW_DIAGNOSIS        1949
#define IDC_CHECK_SHOW_CHRONICITY       1950
#define IDC_BUTTON_SAVE                 1970
#define IDC_EMRLOCK_STATUS              1974
#define IDC_AGED                        1978
#define IDC_DATE_GROUP                  1980
#define IDC_EMNDATE_FROM                1981
#define IDC_EMNDATE_TO                  1982
#define ID_EMRSEARCH_CLOSE              1983
#define IDC_EMRSEARCH_EDIT_FILTER       1984
#define IDC_REMEMBERCOLUMNS             1985
#define ID_EMRSEARCH_PREVIEW            1986
#define IDC_REFRESH_WHEN_FILTERS_CHANGE 1987
#define IDC_EMRSEARCH_REFRESH           1988
#define IDC_STATIC_FROM                 1989
#define IDC_STATIC_TO                   1990
#define IDC_STATIC_PROC                 1991
#define IDC_STATIC_DIAG                 1992
#define IDC_STATIC_PROB                 1993
#define IDC_STATIC_PROV                 1994
#define IDC_STATIC_LOC                  1995
#define IDC_STATIC_FILTER               1996
#define IDC_EMRGROUP_1                  1997
#define IDC_EMRGROUP_2                  1998
#define IDC_EMRGROUP_STATUS             1999
#define IDC_EMR_SHOW_ADVANCED           2000
#define IDC_BTN_EMR_SEENTODAY           2001
#define IDC_STATIC_SEC_PROV             2001
#define IDC_STATUSLABEL                 2002
#define IDC_BTN_EMR_ANALYSIS            2003
#define IDC_EMRSEARCH_SIGN_SELECTED     2003
#define IDC_BTN_PATIENT_WELLNESS        2004
#define IDC_STATIC_CHART                2004
#define IDC_STATIC_CATEGORIES           2005
#define IDC_BTN_EDIT_PROBLEM            2006
#define IDC_REFRESH_WHEN_WINDOW_RESTORED 2006
#define IDC_BTN_DELETE_PROBLEM          2007
#define IDC_BTN_PREVIEW_PROBLEM_LIST    2008
#define IDC_BTN_NEW_PROBLEM             2012
#define IDC_SELECT_EMN_PROVIDERS        2020
#define IDC_TAB_VIEW_CHECK              2021
#define IDC_SELECT_EMN_SECONDARY_PROVIDERS 2021
#define IDC_SHOW_HISTORY                2022
#define IDC_EMN_TABS                    2023
#define IDC_ADD_EMN_CATEGORY            2025
#define IDC_DELETE_EMN_CATEGORY         2026
#define IDC_EMN_TAB_CAT_LIST            2027
#define IDC_ADD_EMN_CHART_TYPE          2028
#define IDC_BTN_MOVE_DIAG_UP            2028
#define IDC_EMN_CAT_LIST                2029
#define IDC_DELETE_EMN_CHART_TYPE       2029
#define IDC_BTN_MOVE_DIAG_DOWN          2029
#define IDC_EMN_CHART_TYPES             2030
#define IDC_BTN_MOVE_DIAG_UP2           2030
#define IDC_BTN_SEARCHQUEUE             2030
#define IDC_HISTORY_CAT_LIST            2031
#define IDC_EDIT_CURRENT_TIME_OPEN      2031
#define IDC_SHOW_SEENPATIENTS           2033
#define IDC_SHOW_SEENPATIENTS_WITH      2034
#define IDC_EDIT_TOTAL_TIME_OPEN        2034
#define IDC_SHOW_CURRENT_PATIENT        2035
#define IDC_CHART_TABS                  2038
#define IDC_CONFIGURE_NEXEMR_COLUMNS    2040
#define IDC_NEXEMR_SHOW_PREVIEW         2041
#define IDC_ADD_EMN_GROUP               2044
#define IDC_DELETE_EMN_GROUP            2045
#define IDC_MOVE_EMN_GROUP_PRIORITY_UP_BTN 2047
#define IDC_MOVE_EMN_GROUP_PRIORITY_DOWN_BTN 2048
#define IDC_MOVE_GROUP_TEMPLATE_PRIORITY_UP_BTN 2049
#define IDC_MOVE_GROUP_TEMPLATE_PRIORITY_DOWN_BTN 2050
#define IDC_SHOW_PREFERRED_PROC         2051
#define IDC_BTN_CONFIG_PREVIEW          2055
#define IDC_MIP_NOTES                   2056
#define IDC_MIP_PROVIDERS               2057
#define IDC_MIP_SECONDARY               2058
#define IDC_MIP_DIAGS                   2059
#define IDC_MIP_SERVICES                2060
#define IDC_MIP_MEDICATIONS             2061
#define IDC_MIP_PROCEDURES              2062
#define IDC_NXCOLORCTRL_CONFIG_PREVIEW  2063
#define IDC_EMRP_HIDE_EMPTY             2064
#define IDC_CHECK_ALL_TOPICS            2065
#define IDC_EMRP_HIDE_EMPTY_PRINT       2065
#define IDC_EMRP_HIDE_NARRATIVE         2066
#define IDC_EDIT_EMN_NAME               2067
#define IDC_EMRP_HIDE_NARRATIVE_PRINT   2067
#define IDC_CHECK_ALL_DETAILS           2068
#define IDC_EMRP_HIDE_EMPTY_TOPICS      2068
#define IDC_CHECK_TREE                  2069
#define IDC_EMRP_HIDE_EMPTY_TOPICS_PRINT 2069
#define IDC_MIP_ASTOPICS                2070
#define IDC_MIP_SHOWEMPTY               2071
#define IDC_EMRP_ALWAYS_HIDE_IF_INDIRECT 2072
#define IDC_MIP_ASC_TIMES               2073
#define IDC_MIP_ASC_STATUS              2074
#define IDC_BTN_UPDATE_PAT_INFO         2075
#define IDC_CHECK_8300                  2076
#define IDC_BTN_USE_EM_CHECKLIST        2077
#define IDC_EDIT_CODING_LEVEL           2078
#define IDC_RADIO_EMRDEBUG_CONSOLE      2079
#define IDC_RADIO_EMRDEBUG_TEXT         2080
#define IDC_EDIT_FILE_PATH              2082
#define IDC_CHECK_RUN_DIFF              2084
#define IDC_EDIT_DIFF_FILE              2085
#define IDC_EDIT_DIFF_APP               2086
#define IDC_CHECK_INCLUDE_ADDRESS       2087
#define IDC_CODING_LEVEL_DESC           2090
#define IDC_RULE_DESC                   2091
#define IDC_DETAIL_LIST_LABEL           2092
#define IDC_CATEGORY_LIST_LABEL         2093
#define IDC_RULE_PASSED_LABEL           2094
#define IDC_NO_CATEGORIES_LABEL         2095
#define IDC_CHECK_NARRATIVE_FIELD_LISTS 2096
#define IDC_ITEM_PLACEHOLDER            2138
#define IDC_PREVIOUS_DETAIL             2139
#define IDC_NEXT_DETAIL                 2140
#define IDC_EMR_MULTIPOP_COLOR          2141
#define IDC_SHOW_LIST                   2145
#define IDC_INFO_GROUPBOX               2174
#define IDC_FILTERS_GROUPBOX            2175
#define IDC_OUTPUT_GROUPBOX             2176
#define IDC_COMPARISONS_GROUPBOX        2177
#define IDC_UNBILLED_EMN_LIST           2185
#define IDC_EMR_ALERT_TEXT              2194
#define IDC_SEND_YAK                    2195
#define IDC_NXCOLOR_EMRALERT            2196
#define IDC_RETRY_WRITE_ACCESS          2197
#define IDC_CHECK_EXPROPRIATE           2198
#define IDC_EMR_SUMMARY_BKG             2199
#define IDC_PT_IMAGE                    2200
#define IDC_EMR_SUMMARY_BKG2            2200
#define IDC_PT_IMAGE_LAST               2201
#define IDC_PT_IMAGE_NEXT               2202
#define IDC_PT_IMAGE_LEFT               2203
#define IDC_PT_IMAGE_RIGHT              2204
#define IDC_PT_IMAGE_UPPER_LEFT         2205
#define IDC_PT_IMAGE_LOWER_LEFT         2206
#define IDC_PT_IMAGE_UPPER_RIGHT        2207
#define IDC_PT_IMAGE_LOWER_RIGHT        2208
#define IDC_PRINT_PRESCRIPTIONS_TO_PRINTER 2209
#define IDC_BTN_MOVE_CATEGORY_UP        2210
#define IDC_BTN_MOVE_CATEGORY_DOWN      2211
#define IDC_CHECK_SHOW_ALLERGIES        2212
#define IDC_CHECK_CURRENT_MEDICATIONS   2213
#define IDC_CHECK_PRESCRIBED_MEDICATIONS 2214
#define IDC_CHECK_LABS                  2215
#define IDC_CHECK_PROBLEM_LIST          2216
#define IDC_CHECK_EMR_DOCUMENTS         2217
#define IDC_BTN_ADD_EMR_CATEGORY        2218
#define IDC_EMR_WRITABLE_LABEL          2219
#define IDC_BTN_REMOVE_EMR_CATEGORY     2219
#define IDC_EMR_WRITABLE_REFRESH_BTN    2220
#define IDC_HISTORY_CAT_LABEL           2221
#define IDC_CHECK_PATIENT_EMR_PROBLEMS  2221
#define IDC_CHECK_PATIENT_NONEMR_PROBLEMS 2222
#define IDC_EMRP_LOCATIONLOGO           2223
#define IDC_WAIT_INFO                   2224
#define IDC_EMRP_DASH                   2224
#define IDC_WAIT_TIMER                  2225
#define IDC_EMRP_OVERRIDEFONT           2225
#define IDC_EMRP_ENABLENARRATIVELINKS   2226
#define IDC_BTN_FORCE_NOW               2227
#define IDC_EMN_TODO_LIST               2232
#define IDC_RADIO_MORE_INFO_TODO_COMPLETED 2236
#define IDC_RADIO_MORE_INFO_TODO_ALL    2237
#define IDC_RADIO_MORE_INFO_TODO_INCOMPLETE 2238
#define IDC_LIST_UNRESOLVED_CREATED_TODO_ALARMS 2252
#define IDC_PROBLEM_STATUS_FILTER       2253
#define IDC_PROBLEM_OBJECT_TYPE_FILTER  2254
#define IDC_LIST_COPY_EMR_TODO_ALARMS   2254
#define IDC_DATE_ONSET                  2255
#define IDC_PROBLEM_DATE_FILTER         2256
#define IDC_NXC_PROBLEM_DELETE          2256
#define IDC_LIST_EMR_DELETING_PROBLEMS  2257
#define IDC_BTN_EMN_TO_BE_BILLED_PREVIEW 2259
#define IDC_BTN_CLOSE_EMRWRITABLE       2260
#define IDC_BTN_EMN_TO_BE_BILLED_REFRESH 2260
#define IDC_STATIC_TOP_CAPTION          2261
#define IDC_BTN_SEND_BILL_TO_HL7        2261
#define IDC_STATIC_SECOND_CAPTION       2262
#define IDC_EDIT_HEADERLEFT             2285
#define IDC_BTN_EMR_ANALYSIS_CLOSE      2286
#define IDC_EDIT_HEADERRIGHT            2286
#define IDC_EMR_ANALYSIS_BKG            2287
#define IDC_EDIT_HEADER2LEFT            2287
#define IDC_BTN_ADD_EMR_ANALYSIS_CONFIG 2288
#define IDC_EMR_ANALYSIS_CONFIG_BKG     2288
#define IDC_EDIT_HEADER2RIGHT           2288
#define IDC_BTN_DELETE_EMR_ANALYSIS_CONFIG 2289
#define IDC_EDIT_FOOTERLEFT             2289
#define IDC_BTN_EDIT_EMR_ANALYSIS_CONFIG 2290
#define IDC_EDIT_FOOTERRIGHT            2290
#define IDC_BTN_RELOAD_RESULTS          2291
#define IDC_EMR_ANALYSIS_CONFIG_LIST    2291
#define IDC_EDIT_FOOTER2LEFT            2291
#define IDC_BTN_CANCEL_SEARCH           2292
#define IDC_RADIO_ALL_EMN_DATES         2292
#define IDC_EDIT_FOOTER2RIGHT           2292
#define IDC_BTN_EMR_ANALYSIS_EXPORT     2293
#define IDC_RADIO_EMN_DATE              2293
#define IDC_EMR_INFO_ITEM_COMBO         2294
#define IDC_RADIO_ALL_EMR_ITEMS         2295
#define IDC_RADIO_ANY_EMR_ITEMS         2296
#define IDC_RADIO_GROUP_BY_PATIENT      2297
#define IDC_RADIO_GROUP_BY_DATE         2298
#define IDC_BTN_HEADFOOTHELP            2298
#define IDC_RADIO_GROUP_BY_EMN          2299
#define IDC_RADIO_GROUP_BY_EMR          2300
#define IDC_EDIT_CONFIG_NAME            2301
#define IDC_RADIO_ALL_EMN_DATES_ANALYSIS 2302
#define IDC_RADIO_FILTER_ON_PATIENT     2302
#define IDC_RADIO_EMN_DATE_ANALYSIS     2303
#define IDC_RADIO_FILTER_ON_EMN         2303
#define IDC_EMN_FROM_DATE_ANALYSIS      2304
#define IDC_RADIO_FILTER_ON_EMR         2304
#define IDC_EMN_TO_DATE_ANALYSIS        2305
#define IDC_EMR_TEMPLATE_COMBO          2305
#define IDC_RADIO_GROUP_BY_PATIENT_ANALYSIS 2306
#define IDC_RADIO_ONE_COL_PER_ITEM      2306
#define IDC_RADIO_GROUP_BY_DATE_ANALYSIS 2307
#define IDC_RADIO_MINIMAL_COLUMNS       2307
#define IDC_RADIO_GROUP_BY_EMN_ANALYSIS 2308
#define IDC_RADIO_GROUP_BY_EMR_ANALYSIS 2309
#define IDC_ANY_ALL_LABEL               2310
#define IDC_RADIO_ONE_COL_PER_ITEM2     2314
#define IDC_SIGNATURE_TEXT              2315
#define IDC_RADIO_MINIMAL_COLUMNS2      2315
#define IDC_COPY_OUTPUT_BTN             2317
#define IDC_CHECK_FILTER_BY_SELECTED_TEMPLATE 2358
#define IDC_CHECK_SHOW_SPAWNING_INFO    2359
#define IDC_CHECK_SHOW_PROVIDER_NAME    2362
#define IDC_CHECK_SHOW_SEC_PROVIDER_NAME 2363
#define IDC_CHECK_SHOW_EMN_DESCRIPTION  2364
#define IDC_CHECK_SHOW_EMR_DESCRIPTION  2365
#define IDC_ADD_EMR_OTHER_PROV          2408
#define IDC_REMOVE_EMR_OTHER_PROV       2409
#define IDC_CONFIDENTIAL_TEXT           2412
#define IDC_EMN_OTHER_PROVS             2413
#define IDC_EMR_PROBLEM_LINKED_OBJECTS_LIST 2433
#define IDD_CUSTOM_RECORD_DETAIL_DLG    2647
#define IDD_CUSTOM_RECORD_DLG           2648
#define IDD_CUSTOM_RECORD_ITEM_DLG      2649
#define IDD_CUSTOM_RECORDS_TAB_DLG      2652
#define IDD_CUSTOM_RECORD_SELECT_SERVICE_DLG 2653
#define IDD_EMR_DEBUG                   2708
#define IDD_EMR_EM_CHECKLIST_DLG        2712
#define IDD_EMR_EM_CHECKLIST_APPROVAL_DLG 2714
#define IDD_EMR_ITEM_ADV_MULTI_POPUP_DLG 2726
#define IDI_EMN                         2730
#define IDI_EMN_LOCKED                  2731
#define IDI_EMN_MOD                     2732
#define IDI_MOREINFO_OPEN               2733
#define IDI_MOREINFO_CLOSED             2734
#define IDI_MOREINFO_CLOSED_MOD         2735
#define IDI_MOREINFO_OPEN_MOD           2736
#define IDI_TOPIC_CLOSED_MOD            2741
#define IDI_TOPIC_OPEN_MOD              2742
#define IDI_TOPIC_OPEN                  2743
#define IDI_TOPIC_CLOSED                2744
#define IDI_EMN_RO                      2747
#define IDI_EMN_RO_MOD                  2748
#define IDD_EMR_ALERT_DLG               2753
#define IDD_EMR_SUMMARY_CONFIG_DLG      2755
#define IDD_EMR_WRITABLE_REVIEW         2757
#define IDD_EMN_FORCE_ACCESS_WAIT_DLG   2759
#define IDD_EMR_UNRESOLVED_TODOS        2763
#define IDD_EMR_DELETE_TODOS            2767
#define IDD_EMR_COPY_TODOS              2769
#define IDI_TOPIC_OPEN_CLOSEDPROBLEMS   2771
#define IDI_TOPIC_OPEN_PROBLEMS         2772
#define IDI_TOPIC_CLOSED_CLOSEDPROBLEMS 2773
#define IDI_TOPIC_CLOSED_PROBLEMS       2774
#define IDI_TOPIC_CLOSED_MOD_CLOSEDPROBLEMS 2775
#define IDI_TOPIC_CLOSED_MOD_PROBLEMS   2776
#define IDI_TOPIC_OPEN_MOD_CLOSEDPROBLEMS 2777
#define IDI_TOPIC_OPEN_MOD_PROBLEMS     2778
#define IDI_EMN_CLOSEDPROBLEMS          2779
#define IDI_EMN_LOCKED_CLOSEDPROBLEMS   2780
#define IDI_EMN_RO_CLOSEDPROBLEMS       2781
#define IDI_EMN_RO_MOD_CLOSEDPROBLEMS   2782
#define IDI_EMN_MOD_CLOSEDPROBLEMS      2783
#define IDI_EMN_PROBLEMS                2784
#define IDI_EMN_LOCKED_PROBLEMS         2785
#define IDI_EMN_RO_PROBLEMS             2786
#define IDI_EMN_RO_MOD_PROBLEMS         2787
#define IDI_EMN_MOD_PROBLEMS            2788
#define IDD_EMR_PROBLEM_DELETE          2789
#define IDI_EMN_LOCKED_RO_CLOSEDPROBLEMS 2791
#define IDI_EMN_LOCKED_RO_PROBLEMS      2792
#define IDI_EMN_LOCKED_RO               2793
#define IDD_EMR_ANALYSIS_DLG            2797
#define IDD_EMR_ANALYSIS_CONFIG_DLG     2798
#define IDD_EMN_CONFIDENTIAL_INFO_DLG   2821
#define IDD_EDIT_EMN_OTHER_PROVS_DLG    2822
#define IDD_EMR_PROBLEM_CHOOSER         2827
#define IDC_OTHER_PROVS_COLOR           4001
#define IDC_LINK_EMN_TO_BILL_LIST       4003
#define IDC_EMN_DESC_LABEL              4004
#define IDC_EMN_DATE_LABEL              4005
#define IDD_LINK_EMN_TO_BILL_DLG        4006
#define IDC_CHECK_INCLUDE_ALREADY_LINKED 4006
#define IDC_CHECK_MERGEEMNTOPRINTER     4008
#define IDD_EMR_POSITION_TOPICS_DLG     4008
#define IDC_POSITION_TOPICS_TREE        4010
#define IDD_DELETE_EMN_CONFIRM_DLG      4010
#define IDC_BTN_EMR_PREVIEW_PREV        4011
#define IDC_BTN_EMR_PREVIEW_NEXT        4012
#define IDD_FORCE_NEXWEB_EMN            4012
#define IDC_PREVIEW_AREA                4013
#define IDC_BTN_KEEP_EMN                4014
#define IDD_EMR_PREVIEW_MULTI_POPUP     4014
#define IDC_BTN_DELETE_EMN              4015
#define IDC_DELETE_EMN_BOTTOM_LABEL     4016
#define IDD_PATIENT_EMR_BY_DATE         4016
#define IDC_DELETE_EMN_TOP_LABEL        4017
#define IDC_DELETE_EMN_DESC             4019
#define IDD_EMR_IMAGE_STAMP_SETUP_DLG   4019
#define IDC_FORCE_EMN_LIST              4020
#define IDC_FORCE_FINAL                 4021
#define IDD_EMR_MED_ALLERGY_VIEWER_DLG  4021
#define IDC_PREVIEW_AREA_MULTI          4022
#define IDC_BUTTON_PRINT                4023
#define IDD_EMR_BARCODE                 4023
#define IDC_BUTTON_PREVIEW              4024
#define IDC_EMRPREVIEW_MULTI_NXCOLOR    4025
#define IDC_EMRPREVIEW_MULTI_DATALIST   4026
#define IDC_CHECK_PRINT_REVERSE         4027
#define IDC_EXISTING_LIST_BY_DATE       4030
#define IDD_SELECT_STAMP_DLG            4030
#define IDD_EMR_MU_PATIENT_MEASURES_DLG 4032
#define IDOPEN                          4033
#define IDC_STAMP_LIST                  4034
#define IDD_PATIENT_DASHBOARD           4034
#define IDD_EMR_MU_PROGRESS_SETUP_DLG   4035
#define IDC_BTN_ADD_STAMP               4035
#define IDC_BTN_DELETE_STAMP            4036
#define IDC_STAMP_SETUP_CLR             4037
#define IDD_EMR_GRAPH_SETUP_DLG         4037
#define IDC_BTN_STAMP_CLOSE             4038
#define IDC_CHECK_SHOW_INACTIVE_STAMPS  4039
#define IDR_EMR_GRAPH_SETUP_POPUP       4039
#define IDC_LABEL_OPEN_THIS_EMN         4040
#define IDD_STAMP_IMAGE_DLG             4040
#define IDC_CHECK_SIGNATURE_DATE_NO_TIME 4041
#define IDR_EMR_PHOTO_PANE_TOOLBAR      4041
#define IDC_BTN_DEVICE_INFO             4043
#define IDD_EMR_OMR_FORM_MAPPER         4043
#define IDC_LIST_MEDALLERGYITEMS        4045
#define IDD_OMR_REVIEW_DLG              4045
#define IDD_OMR_SCAN_DLG                4047
#define IDD_SELECT_CCDA_INFO_DIALOG     4048
#define IDC_BTN_TOGGLE_INACTIVE_MEDALLERGIES 4049
#define IDC_SPELL_CHECK_NOTES           4050
#define IDD_EMR_CODES_DLG               4050
#define IDC_EXCLUDE_PENDING             4051
#define IDI_CODES_OPEN                  4051
#define IDC_EMN_TECH                    4052
#define IDI_CODES_OPEN_MOD              4052
#define IDC_SELECT_EMN_TECHNICIAN       4053
#define IDI_CODES_CLOSED                4053
#define IDC_LIST_TECH                   4054
#define IDI_CODES_CLOSED_MOD            4054
#define IDC_STATIC_TECH                 4055
#define IDC_MIP_TECHNICIANS             4056
#define IDI_CLIN_SUM_MERGED             4056
#define IDC_CONFIG_EMR_TABS_BACKGROUND  4057
#define IDI_CLIN_SUM_NEXWEB             4057
#define IDC_LOCK_MANAGER_SHOW_SECONDARY_PROVIDER 4058
#define IDC_BTN_REFRESH_LOCK_MGR        4059
#define IDC_EMR_CHARGE_PROMPT_BACKGROUND 4059
#define IDC_EMR_CHARGE_PROMPT_CAPTION   4060
#define IDC_EMR_CHARGE_PROMPT_QUANTITY  4061
#define IDC_EMR_CHARGE_PROMPT_QUANTITY_LABEL 4062
#define IDC_BARCODE_EMR                 4063
#define IDC_BARCODENUM_EMR              4064
#define IDC_BARCODEINFOLINK             4065
#define IDC_SIGNATURE_PERCENT_SIZE      4066
#define IDC_SIGNATURE_PERCENT_SIZE_LABEL 4067
#define IDC_BUTTON_PRINT_ALL            4068
#define IDC_ASSIGN_RESP_TO_CHARGE       4070
#define IDC_ASSIGN_RESP_LABEL           4071
#define IDC_IMAGES_USE_FILE_SIZE        4072
#define IDC_SELECT_STAMP_CLR            4074
#define IDC_EMR_PAT_MU_MEASURE_LIST     4075
#define IDC_PAT_DASH_HTML               4076
#define IDC_EMR_MU_PROVIDER_LIST        4077
#define IDC_EMR_MU_MEASURES_LIST        4078
#define IDC_EMR_MU_EXCLUDE_SEC_PROV     4079
#define IDC_EMR_MU_DATE_OPTION_LIST     4080
#define IDC_EMR_MU_START_DATE           4081
#define IDC_EMR_MUSETUP_COLOR1          4082
#define IDC_EMR_MUSETUP_COLOR2          4083
#define IDC_EMRGS_GRAPH_LIST            4084
#define IDC_EMRGS_LINE_LIST             4085
#define IDC_SI_BROWSE_BTN               4085
#define IDC_EMRGS_ADD_ITEM_LIST         4086
#define IDC_SI_HEADER_LBL               4086
#define IDC_EMRGS_ITEM_LIST             4087
#define IDC_SI_PICTUREBOX               4087
#define IDC_SI_USE_TRANSPARENCY_CHECK   4089
#define IDC_SI_TRANSPARENT_COLOR        4090
#define IDC_IS_PICTUREBOX2              4094
#define IDC_EMR_DYNA1                   4095
#define IDC_EMR_DYNA2                   4096
#define IDC_EMR_DYNA3                   4097
#define IDC_EMR_DYNA4                   4098
#define IDC_EMR_DYNA5                   4099
#define IDC_EMR_DYNA6                   4100
#define IDC_EMRGS_NEWGRAPH              4101
#define IDC_EMRGS_REMOVEGRAPH           4102
#define IDC_EMRGS_NEWLINE               4103
#define IDC_EMRGS_REMOVELINE            4104
#define IDC_EMRGS_REMOVEITEM            4105
#define IDC_EMRGS_HELPTEXT              4106
#define IDC_STATIC_FOOT                 4107
#define IDC_STATIC_HEA                  4108
#define IDC_NXCOLORCTRL_MOREINFO        4109
#define IDC_STATIC_MOREINFO             4110
#define IDC_STATIC_SHOW_DISP            4111
#define IDC_NXCOLORCTRL_MISC            4112
#define IDC_NXCOLORCTRL_VISIBILITY      4113
#define IDC_STATIC_MISC_SET             4114
#define IDC_STATIC_MED_ALL              4115
#define IDC_NXCOLORCTRL_MEDSALL         4116
#define IDC_NXCOLORCTRLHEADER           4117
#define IDC_CHECK_DISPLAYMEDS           4118
#define IDC_CHECK_DISMEDS               4119
#define IDC_CHECK_DISPALLERGIES         4120
#define IDC_BTN_EDIT_CATEGORIES         4121
#define IDC_EMR_OMR_MAP_DL              4122
#define IDC_FORM_SELECT_LIST            4123
#define IDC_BTN_OMR_NEW                 4124
#define IDC_BTN_OMR_RENAME              4125
#define IDC_BTN_OMR_DELETE              4126
#define IDC_EMR_TEMPLATE_SELECT         4127
#define IDC_OMR_PEND_COMMIT_DETAILS     4129
#define IDC_OMR_REVIEW_DLG_COLOR        4132
#define IDC_OMR_REVIEW_PREV             4134
#define IDC_OMR_REVIEW_NEXT             4135
#define IDC_OMR_REVIEW_PAT_LBL          4136
#define IDC_OMR_REVIEW_TEMPLATE_LBL     4137
#define IDC_OMR_REVIEW_USERDEFINED_LBL  4138
#define IDC_OMR_SCAN_BTN                4139
#define IDC_OMR_SCAN_FORM_LIST          4140
#define IDC_OMR_SCAN_BGRND              4141
#define IDC_OMR_SCAN_PENDING_LIST       4142
#define IDC_LBL_OMR_REVIEW_DOC_COUNT    4143
#define IDC_OMR_REVIEW_COMMIT           4145
#define IDC_OMR_REVIEW_DONOTCOMMIT      4146
#define IDC_EDIT_OMR_FORM_LOCATION      4147
#define IDC_BTN_BROWSE_OMR_FORM         4148
#define IDC_EMR_OMR_MAPPER_BKGRD_CLR    4150
#define IDC_LIST_APPT_REF_PHYS          4152
#define IDC_STATIC_APPT_REF_PHYS        4153
#define IDC_BTN_RX_QUEUE_MORE_INFO      4155
#define IDC_STATIC_VIEW_OMR             4158
#define IDC_RDO_EXPANDED                4159
#define IDC_RDO_COLLAPSED_ALL           4160
#define IDC_RDO_COLLAPSED_SUCCESS       4161
#define IDC_ST_WITHOUT_PLACEHOLDER      4163
#define IDC_ST_WITH_PLACEHOLDER         4164
#define IDC_CHECK_ALL_FOR_HL7           4165
#define IDC_UNCHECK_ALL_FOR_HL7         4166
#define IDC_ONLY_SHOW_INSURANCE_RESP_CHECK 4167
#define IDC_HIDE_PATIENT_RESP_CHECK     4167
#define IDC_LIST_PROBLEM_SNOMED         4168
#define IDC_ST_INSTRUCTION              4169
#define IDC_CCDA_SELECTION_LIST         4200
#define IDC_GENERATE_XML                4201
#define IDC_GENERATE_PDF                4202
#define IDC_BILL_CODE                   4203
#define IDC_SEND_BILL_TO_HL7_CODE       4204
#define IDC_HIDE_UNBILLABLE_CPT_CODES_CODE 4205
#define IDC_BTN_CHARGE_SPLIT_CODE       4206
#define IDC_BTN_CREATE_BILL_CODE        4207
#define IDC_BTN_CREATE_QUOTE_CODE       4208
#define IDC_BTN_ADD_CHARGE_CODE         4209
#define IDC_BKG_CODE4                   4210
#define IDC_MERGE_SUMMARY_CARE_BTN      4211
#define IDC_MERGE_CLINICAL_SUMMARY_BTN  4213
#define IDC_EXISTING_QUOTE_BTN          4214
#define IDC_EMN_DIAG_SEARCH             4215
#define IDC_BTN_CODES_QUICKLIST         4216
#define IDC_EMR_SEARCH_DIAGNOSIS_SEARCH 4217
#define IDC_EMR_SEARCH_DIAGNOSIS_LIST   4218
#define IDC_EMR_SEARCH_DIAGNOSIS_NONE   4219
#define IDC_ADD_NEXCODE_BTN             4220
#define IDC_LINK_CODES_TO_ALL_CHARGES   4221
#define IDC_CHECK_NOSHOWONCCDA          4223
#define IDC_CHECK_DO_NOT_SHOW_ON_PROBLEM_PROMPT 4224
#define IDC_BTN_PT_EDUCATION            10341
#define IDC_PT_EDUCATION_LABEL          10342
#define IDC_PROBLEM_DIAG_SEARCH_LIST    10381
#define IDC_PROBLEM_DIAG_CODE_LIST      10382
#define IDD_SIGNATURE                   25614
#define ID_NEXEMRTABPOPUP_PUBLISHEMNTONEXWEB 32771
#define ID_EMRGS_NEWGRAPH               32772
#define ID_EMRGS_INACTIVATEGRAPH        32773
#define ID_EMRGS_NEWLINE                32774
#define ID_EMRGS_REMOVELINE             32775
#define ID_EMRGS_REMOVEITEM             32776
#define ID_EMRGS_REACTIVATEGRAPH        32777
#define ID_EMRGS_REMOVEGRAPH            32778
#define ID_GENERATECLINICALSUMMARY_XMLONLY 32784
#define ID_GENERATECLINICALSUMMARY_PDFONLY 32787
#define ID_GENERATECLINICALSUMMARY_XMLANDPDF 32789
#define ID_GENERATECLINICALSUMMARY_CUSTOMIZED 32790
#define ID_GENERATECLINICALSUMMARY_CANCERCASESUBMISSION 32791
#define ID_TABPOPUP_RENAME              40003
#define ID_TABPOPUP_DELETE              40004
#define ID_NEXEMRTABPOPUP_CREATENEWEMR  40005
#define ID_NEXEMRTABPOPUP_EDITEMR       40006
#define ID_NEXEMRTABPOPUP_DELETEEMR     40007
#define ID_NEXEMRTABPOPUP_VIEWHISTORY   40008
#define ID_NEXEMRTABPOPUP_RENAME_EMR    40009
#define ID_NEXEMRTABPOPUP_LOCKEMN       40010
#define ID_NEXEMRTABPOPUP_MOVEEMN_TOEMR 40019
#define ID_EMRLOCK_CHECK                40029
#define ID_EMRLOCK_GOTOPATIENT          40030
#define ID_EMRLOCK_GOTOEMN              40031
#define ID_EMRLOCK_UNCHECK              40032
#define ID_EMRSEARCH_TODAY              40033
#define ID_EMRSEARCH_YESTERDAY          40034
#define ID_EMRSEARCH_LAST7              40038
#define ID_EMRSEARCH_THISWEEK           40039
#define ID_EMRSEARCH_LASTWEEK           40040
#define ID_EMRSEARCH_LAST30             40041
#define ID_EMRSEARCH_THISMONTH          40042
#define ID_EMRSEARCH_LASTMONTH          40043
#define ID_EMRSEARCH_LAST365            40044
#define ID_EMRSEARCH_THISYEAR           40045
#define ID_EMRSEARCH_LASTYEAR           40046
#define ID_EMR_GOTOPATIENT              40047
#define ID_EMR_GOTOEMN                  40048
#define ID_EMRSEARCH_ALLDATES           40049
#define ID_CONFIGURE_CATEGORIES         40051
#define ID_CONFIGURE_CHARTS             40052
#define ID_NEXEMRTABPOPUP_SHOWPREVIEW   40053

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        4061
#define _APS_NEXT_COMMAND_VALUE         32792
#define _APS_NEXT_CONTROL_VALUE         4225
#define _APS_NEXT_SYMED_VALUE           4000
#endif
#endif
