//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Inventory.rc
//
#define IDC_DEFAULT                     3
#define IDC_BTN_SAVE_UNCOMPLETED        3
#define IDC_BTN_DISPLAY_CONSIGN_RESULTS 3
#define IDC_MARK_ALL_RECEIVED           3
#define IDC_BTN_ADD_SUPPLIER            3
#define IDOK2                           3
#define ID_GLASSES_ORDER_PRINTPREVIEWBTN 3
#define IDBTNSAVEANDPRINTORD            3
#define IDC_BTN_SAVE_COMPLETED          4
#define IDC_BTN_CANCEL_RECONCILIATION   5
#define IDC_BTN_SUPPLIER_CATALOG        6
#define IDR_MAINFRAME                   128
#define IDC_BTN_VISIONWEBSYNC           128
#define IDD_INVNEW                      359
#define IDD_INVADJUST                   520
#define IDD_INVEDITORDER                524
#define IDD_PATIENT_GROUPS_DLG          551
#define IDC_NEXT_ITEM                   1001
#define IDC_PREV_ITEM                   1002
#define IDC_COLOR_INVMULTISERIALPICKER  1002
#define IDC_INACTIVE_ITEMS              1003
#define IDC_RADIO_NOT_TRACKABLE         1004
#define IDC_PATIENT_COMBO               1004
#define IDC_NEW                         1005
#define IDC_RADIO_TRACK_ORDERS          1005
#define IDC_DELETE                      1006
#define IDC_RADIO_TRACK_QUANTITY        1006
#define IDC_PRINT_PREV                  1007
#define IDC_UNDO                        1007
#define IDC_ORDER                       1007
#define IDC_RADIO_NOT_TRACKABLE_ITEM    1007
#define IDC_RADIO_TRACK_ORDERS_ITEM     1008
#define IDC_ORDER_UO                    1008
#define IDC_RADIO_TRACK_QUANTITY_ITEM   1009
#define IDC_PREV_LOCATION               1009
#define IDC_ADD_ALL                     1009
#define IDC_UNITDESC                    1010
#define IDC_NEXT_LOCATION               1011
#define IDC_REMOVE_ALL                  1011
#define IDC_ORDER_CONSIGNMENT           1012
#define IDC_UB92_CATEGORIES             1013
#define IDC_UB92_CPT_CATEGORIES         1013
#define IDC_ORDER_UO_CONSIGNMENT        1014
#define IDC_CANCEL_BTN                  1015
#define IDC_QUANTITY                    1015
#define IDC_SUPPLIER_LIST               1015
#define IDC_ADD_SUPPLIER                1016
#define IDC_QUANTITY_UO                 1016
#define IDC_MAKE_DEFAULT                1017
#define IDC_NEW_SUPPLIER_LIST           1017
#define IDC_BKG_COLOR                   1018
#define IDC_DELETE_SUPPLIER             1018
#define IDC_LAST_COST                   1019
#define IDC_BILLABLE                    1020
#define IDC_ACTUAL                      1021
#define IDC_BOTTOM_BOX                  1021
#define IDC_REORDERPOINT                1022
#define IDC_REORDERQUANTITY             1023
#define IDC_CATEGORYBOX                 1024
#define IDC_ADD                         1024
#define IDC_CATALOG                     1025
#define IDC_UO_EDIT                     1025
#define IDC_TAXABLE                     1026
#define IDC_BARCODE                     1027
#define IDC_TRACKABLE                   1028
#define IDC_ACTUAL_UO                   1028
#define IDC_TAXABLE2                    1029
#define IDC_UU_EDIT                     1030
#define IDC_ITEM_LIST                   1030
#define IDC_CONVERSION_EDIT             1031
#define IDC_SELECTED_ITEM_LIST          1031
#define IDC_REORDERPOINT_UO             1032
#define IDC_EXPDATE                     1032
#define IDC_REORDERQUANTITY_UO          1033
#define IDC_BTN_APPLY_EXP_DATE          1033
#define IDC_EXP_DATE_LABEL              1034
#define IDC_SUPPLIER_COMBO              1034
#define IDC_SELECT_ITEM_LABEL           1035
#define IDC_CATALOG_EDIT                1035
#define IDC_BTN_SHOW_ITEMS              1036
#define IDC_BTN_APPLY_LOT_NUM           1036
#define IDC_SUPPLIER_LABEL              1037
#define IDC_LOCATION_LIST               1038
#define IDC_LOC_CAPTION                 1039
#define IDC_INV_QUANTITY_BKGRND         1040
#define IDC_INV_CAT_BKGRND              1041
#define IDC_INV_UO_UU_BKGRND            1042
#define IDC_HISTORY                     1043
#define IDC_UO_ADJ_TEXT                 1044
#define IDC_BTN_EQUIPMENT_MAINTENANCE   1044
#define IDC_CHECK_USE_UU                1045
#define IDC_UU_ADJ_TEXT                 1045
#define IDC_CHECK_SERIAL_NUM            1046
#define IDC_BTN_SELECT_PRODUCT          1046
#define IDC_CHECK_EXP_DATE              1047
#define IDC_ITEM                        1048
#define IDC_BTN_UNSELECT_PRODUCT        1048
#define IDC_CATEGORY_LIST               1049
#define IDC_QUANTITY_LABEL              1049
#define IDC_RESP_LIST                   1050
#define IDC_SERIAL_COMBO                1050
#define IDC_MAINT_INTERVAL              1051
#define IDC_EQUIPMENT                   1051
#define IDC_TRACKER_STATUS_LIST         1051
#define IDC_DATE                        1052
#define IDC_MAINTENANCE_LIST            1052
#define IDC_INS_CODE                    1052
#define IDC_TOTAL                       1053
#define IDC_MAINT_INTERVAL_TYPE         1053
#define IDC_CHECK_SERIALIZED_PER_UO     1053
#define IDC_CONFIRMED_DATE              1053
#define IDC_SUBTOTAL                    1054
#define IDC_EQUIPMENT_NAME              1054
#define IDC_INV_SHOP_FEE                1054
#define IDC_TAXTOTAL                    1055
#define IDC_ADD_NEW_MAINT_ENTRY         1055
#define IDC_BTN_TRANSFER_PRODUCT_ITEMS  1055
#define IDC_EXTRACOST                   1056
#define IDC_STARTCHARGEDATE             1056
#define IDC_DEFAULT_CONSIGNMENT         1056
#define IDC_STARTDATE                   1056
#define IDC_PRICE                       1057
#define IDC_ENDCHARGEDATE               1057
#define IDC_ENDDATE                     1057
#define IDC_INV_ORDER_TOTAL_QTY         1057
#define IDC_LIST_SERIALIZED             1058
#define IDC_ACTUAL_CONSIGNMENT          1058
#define IDC_CHECK_FILTERONCHGDATES      1059
#define IDC_CHECK_FILTERONDATES         1059
#define IDC_ACTUAL_UO_CONSIGNMENT       1059
#define IDC_CHECK_FILTER_CONSIGNMENT    1060
#define IDC_REORDERPOINT_CONSIGNMENT    1060
#define IDC_REORDERPOINT_UO_CONSIGNMENT 1061
#define IDC_PRODUCT_FILTER_LABEL        1062
#define IDC_CAT_FILTER_LABEL            1063
#define IDC_DEFAULT_INV_PROVIDER        1064
#define IDC_LOCATION_FROM               1065
#define IDC_REORDERQUANTITY_CONSIGNMENT 1065
#define IDC_REORDERQUANTITY_UO_CONSIGNMENT 1066
#define IDC_AVAIL_INV                   1067
#define IDC_STOCK_FROM                  1068
#define IDC_AVAIL_UO                    1068
#define IDC_STOCK_UO_FROM               1069
#define IDC_AVAIL_CONSIGNMENT           1069
#define IDC_QUANTITY_FROM               1070
#define IDC_AVAIL_UO_CONSIGNMENT        1070
#define IDC_QUANTITY_UO_FROM            1071
#define IDC_STOCK_TO                    1074
#define IDC_STOCK_UO_TO                 1075
#define IDC_QUANTITY_TO                 1076
#define IDC_QUANTITY_UO_TO              1077
#define IDC_LOC_FROM_NAME_LABEL         1078
#define IDC_TRANSFER_AMT_UO             1079
#define IDC_LOC_TO_NAME_LABEL           1080
#define IDC_UU_LABEL_FROM               1081
#define IDC_UO_LABEL_FROM               1082
#define IDC_TRANSFER_AMT                1083
#define IDC_TRANSFER_ITEM               1084
#define IDC_BTN_AUTO_CALC               1085
#define IDC_PENDING_CASES_LIST          1086
#define IDC_PRODUCT_NAME                1087
#define IDC_LOCATION_NAME               1088
#define IDC_CHECK_TAX_SHIPPING          1088
#define IDC_BTN_SELECT_CATEGORY         1089
#define IDC_BTN_REMOVE_CATEGORY         1090
#define IDC_ALL                         1091
#define IDC_BTN_ADD_NEW_SUPPLIER        1091
#define IDC_CLOSE_PRODUCT_ITEMS         1093
#define IDC_SUPPLIER_FILTER             1094
#define IDC_INV_SHOP_FEE_LABEL          1095
#define IDC_UNSELECTED_ITEM_LIST        1096
#define IDC_BTN_SELECT_ONE              1097
#define IDC_BTN_SELECT_ALL              1098
#define IDC_BTN_UNSELECT_ONE            1099
#define IDC_BTN_UNSELECT_ALL            1100
#define IDC_NEW_LOCATION_COMBO          1101
#define IDC_CATEGORY                    1102
#define IDC_BTN_APPLY_LOC               1102
#define IDC_BTN_APPLY_DATE_TO_SELECTED  1103
#define IDC_NEW_ITEM_LOCATION           1104
#define IDC_BTN_APPLY_LOT_NUM_TO_SELECTED 1104
#define IDC_PREV_LOC                    1105
#define IDC_NEXT_LOC                    1106
#define IDC_NEW_ITEM_LOC_LABEL          1107
#define IDC_BTN_CATEGORY_PICKER         1108
#define IDC_BTN_CATEGORY_REMOVE         1109
#define IDC_BTN_INV_SUGGESTED_SALES     1110
#define IDC_NOTES                       1111
#define IDC_RECEIVE_ORDER_LIST          1111
#define IDC_RECEIVE_ORDER_LOCATION      1112
#define IDC_PRODUCT_ALLOC_COMBO         1112
#define IDC_SURGERY_ALLOC_COMBO         1113
#define IDC_ORDER_PLACED_DATE           1114
#define IDC_ALLOCATION_LIST             1114
#define IDC_ORDER_PLACED_FROM           1115
#define IDC_QUOTE_ALLOC_COMBO           1115
#define IDC_ORDER_TRACKING_NUM          1116
#define IDC_ALLOCATIONS_LIST            1116
#define IDC_ALLOC_ADD_COMBO             1116
#define IDC_RECEIVE_ORDER_COLOR1        1117
#define IDC_BTN_CREATE_NEW_ALLOCATION   1117
#define IDC_CONSIGNMENT_LIST            1118
#define IDC_BTN_COMPLETE_MULTIPLE_ALLOCATIONS 1118
#define IDC_EDIT_ALLOCATION_NOTES       1119
#define IDC_BTN_CONFIGURE_RETURN_METHODS 1119
#define IDC_CONSIGNMENT_COMBO           1119
#define IDC_RAD_RECEIVE_ORDER_BARCODE_INC 1120
#define IDC_BTN_CONFIGURE_RETURN_REASONS 1120
#define IDC_RAD_RECEIVE_ORDER_BARCODE_PROMPT 1121
#define IDC_APPOINTMENT_COMBO           1121
#define IDC_PAT_ALLOC_BKG2              1122
#define IDC_ALLOC_BKG                   1123
#define IDC_PAT_ALLOC_BKG1              1123
#define IDC_SUPPLIER_RETURN_LIST        1123
#define IDC_CONSIGN_BKG                 1124
#define IDC_ITEM_RETURN_LIST            1124
#define IDC_LOCATION_RETURN_LIST        1125
#define IDC_BTN_NEW_RETURN              1125
#define IDC_CONSIGN_BKG2                1125
#define IDC_CONSIGN_SUPPLIER_COMBO      1126
#define IDC_BTN_SUPPLIER_STATEMENTS     1126
#define IDC_DT_OVERVIEW_FROM            1127
#define IDC_BTN_RECONCILE_CONSIGNMENT   1127
#define IDC_CONSIGN_PRODUCT_COMBO       1128
#define IDC_RETURN_LIST                 1129
#define IDC_DT_OVERVIEW_TO              1129
#define IDC_BTN_FRAME_TYPE              1131
#define IDC_RETURN_METHOD_LIST          1132
#define IDC_BTN_MATERIAL                1132
#define IDC_RETURN_FOR_LIST             1133
#define IDC_BTN_TREATMENTS              1133
#define IDC_RETURN_REASON_LIST          1134
#define IDC_BTN_DESIGN                  1135
#define IDC_SUPPLIER_FILTER_RETURN      1136
#define IDC_CONSIGN_LOCATION_COMBO      1136
#define IDC_RADIO_ALL_OVERVIEW_DATES    1137
#define IDC_RADIO_OVERVIEW_DATE_RANGE   1138
#define IDC_ALLOCATED_ITEMS_LIST        1139
#define IDC_ALLOC_PATIENT_NAME          1140
#define IDC_CREATE_DATE                 1141
#define IDC_CONSIGN_CATEGORY_COMBO      1141
#define IDC_OVERVIEW_PRODUCT_TYPE_COMBO 1142
#define IDC_APPT_INFO                   1143
#define IDC_OVERVIEW_STATUS_COMBO       1143
#define IDC_ALLOCATION_NOTES            1144
#define IDC_BTN_LINK_PRODUCTS           1145
#define IDC_TOTAL_OVERVIEW_ROWS_LABEL   1146
#define IDC_HEADER_LABEL                1147
#define IDC_FOREIGN_CHECK               1148
#define IDC_RECONCILE_HISTORY_LIST      1148
#define IDC_RECONCILE_CURRENT_LIST      1149
#define IDC_BTN_NEW_RECONCILIATION      1150
#define IDC_RECONCILE_LOCATION          1152
#define IDC_SCAN_ONLY_MODE              1157
#define IDC_BTN_COMPLETE_ALLOCATION     1158
#define IDC_PURCHASE_LIST               1158
#define IDC_RADIO_ACTIVE_ALLOCATIONS    1159
#define IDC_STATIC_TOTAL_AMOUNT         1159
#define IDC_BTN_PREVIEW_ALLOCATIONS     1159
#define IDC_RADIO_COMPLETED_NOT_BILLED  1160
#define IDC_STATIC_TOTAL                1160
#define IDC_RADIO_COMPLETED_AND_BILLED  1161
#define IDC_INVENTORY_LIST              1161
#define IDC_OVERVIEW_LOCATION_COMBO     1163
#define IDC_OVERVIEW_CATEGORY_COMBO     1164
#define IDC_OVERVIEW_PRODUCT_COMBO      1165
#define IDC_OVERVIEW_SUPPLIER_COMBO     1166
#define IDC_OVERVIEW_LIST               1167
#define IDC_RADIO_BARCODE_USED          1168
#define IDC_OVERVIEW_PROVIDER_COMBO     1168
#define IDC_RADIO_BARCODE_RELEASED      1169
#define IDC_OVERVIEW_ORDER_COMBO        1169
#define IDC_RADIO_BATCH_BARCODE_RELEASED 1170
#define IDC_RADIO_BATCH_BARCODE_USED    1171
#define IDC_MULTI_ALLOCATION_LIST       1172
#define IDC_MULTI_ALLOC_BKG             1173
#define IDC_DESCRIPTION                 1175
#define IDC_TRACKING_NUMBER             1176
#define IDC_AUTO_PURCH_INV              1177
#define IDC_AUTO_CONSIGN                1178
#define IDC_LABEL_RETURN_SHOW           1179
#define IDC_PURCHASE_ORDER              1179
#define IDC_LABEL_RETURN_SUPPLIER       1180
#define IDC_ORDER_CONTACT_NAME          1180
#define IDC_BTN_SAVE_AND_COMPLETE       1181
#define IDC_BTN_SAVE_LEAVE_UNCOMPLETED  1182
#define IDC_STATIC_INVADJ_QUANTITY      1182
#define IDC_ORDER_CC_NAME               1182
#define IDC_CATEGORY_BOX                1182
#define IDC_ENABLE_SHIP_TO              1183
#define IDC_ORDER_CC_NUMBER             1184
#define IDC_ORDER_CC_EXP_DATE           1185
#define IDC_EDIT_SHIP_METHOD            1186
#define IDC_EDIT_CC_TYPE                1187
#define IDC_SHIPPING_METHOD_LIST        1188
#define IDC_CC_TYPE_LIST                1189
#define IDC_SOLD_TO                     1190
#define IDC_ORDER_CC_ON_FILE            1191
#define IDC_PROVIDER_ALLOC_COMBO        1192
#define IDC_ORDER_METHOD_COMBO          1192
#define IDC_LINKED_APPT_LABEL           1193
#define IDC_REMINDER_TEXT               1194
#define IDC_EDIT_ORDER_METHODS          1194
#define IDC_REMINDER_TEXT2              1195
#define IDC_RADIO_SCAN_GENERAL          1195
#define IDC_REMINDER_TEXT3              1196
#define IDC_RADIO_SCAN_CONSIGNMENT      1196
#define IDC_REMINDER_TEXT4              1197
#define IDC_STATIC_SCAN_AS              1197
#define IDC_REMINDER_TEXT5              1198
#define IDC_CHECK_FACILITY_FEE          1198
#define IDC_REMINDER_TEXT6              1199
#define IDC_CLOSE_APPTS_REQUIRING_ALLOCATIONS 1199
#define IDC_REQUIREMENTS_LIST           1200
#define IDC_ADD_REQUIREMENT             1201
#define IDC_EDIT_REQUIREMENT            1202
#define IDC_DELETE_REQUIREMENT          1203
#define IDC_APPT_REQS_BKG               1204
#define IDC_CONFIGURE_REQUIRED_ALLOCATIONS 1205
#define IDC_UB92_CPT_LABEL              1206
#define IDC_REQUIRED_ALLOCATION_DETAIL_DESCRIPTION 1206
#define IDC_AVAILABLE_TYPES             1207
#define IDC_ADD_REQUIRED_TYPE           1208
#define IDC_REMOVE_REQUIRED_TYPE        1209
#define IDC_SELECTED_TYPES              1210
#define IDC_AVAILABLE_PURPOSES_LIST     1211
#define IDC_ADD_REQUIRED_PURPOSE        1214
#define IDC_REMOVE_REQUIRED_PURPOSE     1216
#define IDC_REMOVE_ALL_REQUIRED_PURPOSES 1217
#define IDC_SELECTED_PURPOSES_LIST      1218
#define IDC_REQUIRED_ALLOCATION_DETAIL_BKG 1219
#define IDC_TRANSFER_WARNING            1220
#define IDC_REMIND_ME                   1221
#define IDC_CLOSE_APPTS_WO_ALLOCS       1222
#define IDC_APPOINTMENTS_LIST           1223
#define IDC_CREATE_ALLOCATION_WO        1224
#define IDC_CREATE_ORDER_WO             1225
#define IDC_CONFIGURE_REQUIREMENTS      1226
#define IDC_APPTS_WO_BKG                1227
#define IDC_REQUIREMENT_DAYS            1228
#define IDC_STATIC_SERIAL               1230
#define IDC_LIST_MULTISERIALPICKER      1231
#define IDC_PREVIEW_APPTS               1232
#define IDC_BTN_APPLY_DISCOUNTS         1233
#define IDC_TO_BE_RETURNED              1234
#define IDC_CLOSE_PRODUCTS_TO_RETURN    1235
#define IDC_TO_BE_ORDERED               1235
#define IDC_PRODUCTS_TO_BE_RETURNED     1237
#define IDC_NEW_RETURN_ALL              1238
#define IDC_NEW_RETURN_SELECTED         1239
#define IDC_TO_BE_RETURNED_COLOR        1240
#define IDC_EDIT_ADJ_CATEGORIES         1242
#define IDC_ADJ_CATEGORIES              1243
#define IDC_CLOSE_PRODUCT_ADJUSTMENT_CATEGORIES 1244
#define IDC_PRODUCT_ADJUSTMENT_CATEGORIES 1245
#define IDC_ADD_CATEGORY                1246
#define IDC_DELETE_CATEGORY             1247
#define IDC_EDIT_ADJUSTMENT_CATEGORY    1248
#define IDC_ADJUSTMENT_CATEGORY_BKG     1249
#define IDC_INV_ORDER_DATE_LABEL        1250
#define IDC_INV_ORDER_FROM_DATE         1251
#define IDC_INV_ORDER_TO_DATE           1252
#define IDC_INV_ORDER_DATE_FILTER_LIST  1252
#define IDC_INV_ORDER_ORDER_FILTER      1255
#define IDC_INV_ORDER_USE_DATE          1256
#define IDC_INV_ORDER_RETURN_FILTER     1257
#define IDC_SERIAL_NUMBER_AS_LOT_NUMBER 1258
#define IDC_LOT_NUMBER                  1259
#define IDC_LOT_NUM_LABEL               1260
#define IDC_CLOSE_LINK_PRODUCTS         1261
#define IDC_AVAILABLE_CPT_LIST          1262
#define IDC_INCLUDE_UNLINKED            1263
#define IDC_AVAILABLE_PRODUCTS          1264
#define IDC_LINKED_PRODUCTS             1265
#define IDC_LINK_PRODUCT                1266
#define IDC_UNLINK_PRODUCT              1267
#define IDC_LINK_PRODUCTS_BKG           1268
#define IDC_LINK_PRODUCTS_DESCRIPTION   1269
#define IDC_SELECT_LINKED_PRODUCTS_CAPTION 1270
#define IDC_LINKABLE_PRODUCTS           1271
#define IDC_PRODUCTS_TO_BILL            1272
#define IDC_BILL_PRODUCT                1273
#define IDC_UNBILL_PRODUCT              1274
#define IDC_SELECT_LINKED_PRODUCTS_BKG  1275
#define IDC_SELECT_LINKED_PRODUCTS_TITLE 1276
#define IDC_CLOSE_TO_BE_ORDERED         1277
#define IDC_PRODUCTS_TO_BE_ORDERED      1279
#define IDC_ORDER_ALL                   1280
#define IDC_ORDER_SELECTED              1281
#define IDC_TO_BE_ORDERED_BKG           1282
#define IDC_LINKED_ALLOCATIONS          1283
#define IDC_LINKED_ALLOCATIONS_LABEL    1284
#define IDC_DATE_FILTER_TYPES           1285
#define IDC_PRODUCT_LIST                1286
#define IDC_INV_REC_DATE_LABEL          1287
#define IDC_EDIT_INV_REC_NOTES          1288
#define IDC_PRODUCT_LOCATION_LABEL      1289
#define IDC_BTN_CONSIGNMENT_LIST        1291
#define IDC_REMOVE                      1292
#define IDC_BTN_CONSIGNMENT_TURN_RATE_BY_MONTH 1292
#define IDC_BTN_SERIAL_IN_STOCK         1293
#define IDC_BTN_PHYSICAL_INVENTORY      1294
#define IDC_BTN_GO_REPORTS              1295
#define IDC_BTN_ALLOCATION_LIST         1296
#define IDC_BTN_CLOSE_INV_REC           1296
#define IDC_BTN_CONSIGNMENT_HISTORY_BY_DATE 1297
#define IDC_CHECK_SHOW_CANCELLED_INV_REC 1297
#define IDC_BTN_SERIAL_BY_PT            1298
#define IDC_INC_REC_BKG                 1298
#define IDC_INV_REC_HIST_BKG            1299
#define IDC_BTN_EDIT_CUR_INV_REC        1301
#define IDC_BTN_VIEW_HIST_INV_REC       1302
#define IDC_INC_REC_ADJ_BKG             1302
#define IDC_ADJUSTED_PRODUCT_LIST       1303
#define IDC_INC_REC_ADJ_CONSIGNMENT_LABEL 1304
#define IDC_VENDOR_CONFIRMED_CHK        1305
#define IDC_VENDOR_CONF_NUM             1306
#define IDC_VENDOR_CONFIRMED            1307
#define IDC_CONFIRMATION_NUMBER         1308
#define IDC_TOTAL_ITEMS_RETURNED_LABEL  1309
#define IDC_BTN_RETURN_TRACK_FEDEX      1310
#define IDC_BTN_ORDER_TRACK_FEDEX       1311
#define IDC_ORDERED_PRODUCT_LIST        1312
#define IDC_RETURNED_PRODUCT_LIST       1313
#define IDC_RADIO_FILTER_BY_ORDER       1314
#define IDC_RADIO_FILTER_BY_DATES       1315
#define IDC_ORDER_COMBO                 1316
#define IDC_DT_SUPPLIER_STATEMENT_FROM  1317
#define IDC_DT_SUPPLIER_STATEMENT_TO    1318
#define IDC_RADIO_GROUP_BY_ORDER_DETAIL 1319
#define IDC_RADIO_GROUP_BY_SERIAL_NUM   1320
#define IDC_LIST                        1321
#define IDC_RADIO_SHOW_USED             1321
#define IDC_RADIO_SHOW_AVAIL            1322
#define IDC_RADIO_SHOW_ALL_USEDSTATUS_PRODUCTS 1323
#define IDC_BTN_DISPLAY_STATEMENT_RESULTS 1323
#define IDC_RADIO_SHOW_UNPAID           1324
#define IDC_RADIO_SHOW_PAID             1325
#define IDC_RADIO_SHOW_ALL_PAYSTATUS_PRODUCTS 1326
#define IDC_CONSIGN_PRODUCT_LIST        1327
#define IDC_INV_CONSIGN_RECONCILE_BKG   1328
#define IDC_INV_SUPPLIER_STATEMENT_BKG  1329
#define IDC_INVREC_SUPPLIER_COMBO       1330
#define IDC_INVREC_CATEGORY_COMBO       1331
#define IDC_BTN_PRINT_INV_REC_ADJ       1331
#define IDC_PRODUCT_SELECTED_COUNT      1332
#define IDC_BTN_APPLY_PRODUCT_CHANGES   1333
#define IDC_BTN_CLOSE_PRODUCT_UPDATER   1334
#define IDC_UPDATE_PRODUCT_UNSELECTED_LIST 1335
#define IDC_UPDATE_PRODUCT_SELECTED_LIST 1336
#define IDC_PROD_TAXABLE                1338
#define IDC_PROD_TAXABLE2               1339
#define IDC_PROD_SHOP_FEE               1340
#define IDC_PROD_REORDERPOINT           1341
#define IDC_PROD_REORDERQUANTITY        1342
#define IDC_PROD_USER_RESP_COMBO        1343
#define IDC_PROD_REV_CODE_COMBO         1344
#define IDC_PROD_BILLABLE               1345
#define IDC_PROD_RADIO_NOT_TRACKABLE    1346
#define IDC_PROD_RADIO_TRACK_ORDERS     1347
#define IDC_PROD_RADIO_TRACK_QUANTITY   1348
#define IDC_UPDATE_PROD_LOCATION_COMBO  1349
#define IDC_PROD_SHOP_FEE_LABEL         1350
#define IDC_CHECK_UPDATE_CATEGORY       1351
#define IDC_CHECK_UPDATE_SUPPLIER       1352
#define IDC_CHECK_SHOWPONUMBER          1352
#define IDC_CHECK_UPDATE_TAXABLE_1      1353
#define IDC_FRAMES_CATALOG_LIST         1353
#define IDC_CHECK_UPDATE_TAXABLE_2      1354
#define IDC_CHECK_UPDATE_REV_CODE       1355
#define IDC_NXCOLOR_INV_FRAMES2         1355
#define IDC_CHECK_UPDATE_SHOP_FEE       1356
#define IDC_NXCOLOR_INV_FRAMES          1356
#define IDC_CHECK_UPDATE_BILLABLE       1357
#define IDC_FRAMES_COMBO_MANUFACTURER   1357
#define IDC_CHECK_UPDATE_TRACKABLE      1358
#define IDC_FRAMES_COMBO_COLLECTION     1358
#define IDC_CHECK_UPDATE_REORDER_POINT  1359
#define IDC_FRAMES_COMBO_STYLE          1359
#define IDC_VISIONWEB_COMBO_SUPPLIER    1359
#define IDC_CHECK_UPDATE_REORDER_QTY    1360
#define IDC_FRAMES_COMBO_BRAND          1360
#define IDC_LOCATION_ALLOC_COMBO        1361
#define IDC_CHECK_UPDATE_USER_RESP      1361
#define IDC_FRAMES_COMBO_GROUP          1361
#define IDC_CHECK_UPDATE_SHOP_FEE_LOC   1362
#define IDC_PROD_SHOP_FEE_LABEL_LOC     1363
#define IDC_PROD_SHOP_FEE_LOC           1364
#define IDC_FRAMES_STYLE                1365
#define IDC_CHECK_UPDATE_REMEMBER_CHARGE_PROVIDER 1365
#define IDC_FRAMES_COLOR                1366
#define IDC_PROD_REMEMBER_CHARGE_PROVIDER 1366
#define IDC_FRAMES_LENS_COLOR           1367
#define IDC_CHECK_UPDATE_INSURANCE_CODE 1367
#define IDC_FRAMES_EYE                  1368
#define IDC_PROD_SHOP_FEE_LABEL2        1368
#define IDC_PROD_INSURANCE_CODE_LABEL   1368
#define IDC_FRAMES_BRIDGE               1369
#define IDC_PROD_INSURANCE_CODE         1369
#define IDC_FRAMES_TEMPLE               1370
#define IDC_FRAMES_DBL                  1371
#define IDC_FRAMES_A                    1372
#define IDC_FRAMES_B                    1373
#define IDC_FRAMES_ED                   1374
#define IDC_FRAMES_CIRCUMFERENCE        1375
#define IDC_FRAMES_EDANGLE              1376
#define IDC_FRAMES_FRONT_PRICE          1377
#define IDC_FRAMES_HALF_TEMPLES_PRICE   1378
#define IDC_FRAMES_TEMPLES_PRICE        1379
#define IDC_FRAMES_COMPLETE_PRICE       1380
#define IDC_FRAMES_MANUFACTURER         1381
#define IDC_FRAMES_BRAND                1382
#define IDC_FRAMES_COLLECTION           1383
#define IDC_FRAMES_GENDER               1384
#define IDC_FRAMES_AGE_GROUP            1385
#define IDC_FRAMES_ACTIVE_STATUS        1386
#define IDC_FRAMES_PRODUCT_GROUP_NAME   1387
#define IDC_FRAMES_RIM_TYPE             1388
#define IDC_FRAMES_MATERIAL             1389
#define IDC_FRAMES_FRAME_SHAPE          1390
#define IDC_FRAMES_COUNTRY              1391
#define IDC_FRAMES_SKU                  1392
#define IDC_FRAMES_YEAR_INTRODUCED      1393
#define IDC_NXCOLOR_FRAMES_DATA         1394
#define IDC_FRAMES_IMPORT_BUTTON        1395
#define IDC_FRAMES_COLOR_CODE           1395
#define IDC_FRAMES_SELECT_ALL           1396
#define IDC_FRAMES_PRODUCT_NAME         1396
#define IDC_FRAMES_SELECT_NONE          1397
#define IDC_FR_OP_BKGD                  1397
#define IDC_FRAMES_CREATE_SELECTED_PRODUCTS 1398
#define IDC_FRAMES_UPDATE_EXISTING_PRODUCTS 1399
#define IDC_FRAMES_APPLY_MARKUP         1400
#define IDC_FR_OP_BILLABLE              1402
#define IDC_FR_OP_TAXABLE               1403
#define IDC_FR_OP_TAXABLE2              1404
#define IDC_FR_OP_RADIO_NOT_TRACKABLE_ITEM 1405
#define IDC_FR_OP_RADIO_TRACK_ORDERS_ITEM 1406
#define IDC_FR_OP_RADIO_TRACK_QUANTITY_ITEM 1407
#define IDC_FRAMES_OPTIONS              1408
#define IDC_FR_OP_CAT_LIST              1409
#define IDC_FRAMES_EDIT_MARKUPS         1409
#define IDC_FRAME_DATA_CANCEL_BTN       1411
#define IDC_FRAMES_VERSION_DATE_LABEL   1412
#define IDC_FRAMES_LIST_COUNT_LABEL     1413
#define IDC_INV_LABEL_REPORT_LIST       1415
#define IDC_INV_LABEL_REPORT_BKG        1416
#define IDC_PRINT_LABEL                 1417
#define IDC_PRINTPREVIEW                1418
#define IDC_PRICE_CHANGE_REPORT         1420
#define IDC_MARKUP_LIST                 1421
#define IDC_MARKUP_NAME                 1422
#define IDC_MARKUP_FORMULA              1423
#define IDC_VISIONWEB_ORDER_LIST        1423
#define IDC_NEW_MARKUP                  1424
#define IDC_DELETE_MARKUP               1425
#define IDC_VISIONWEB_COMBO_PATIENT     1425
#define IDC_MARKUP_BACKGROUND           1426
#define IDC_VISIONWEB_COMBO_OPTICIAN    1426
#define IDC_VISIONWEB_ORDER_STATUS      1427
#define IDC_NEW_VISIONWEB_ORDER         1428
#define IDC_BTN_VISIONWEB_ACCOUNT_SETUP 1429
#define IDC_COLOR_ORDERLIST             1430
#define IDC_CHECK_SINGLE_REV_CODE       1431
#define IDC_COLOR_ACTION                1431
#define IDC_CHECK_MULTIPLE_REV_CODES    1432
#define IDC_DT_VISIONWEB_FROM           1432
#define IDC_BTN_EDIT_MULTIPLE_REV_CODES 1433
#define IDC_DT_VISIONWEB_TO             1433
#define IDC_VIEW_FRAMES_DATA            1434
#define IDC_RADIO_VISIONWEB_DATE_RANGE  1434
#define IDC_RADIO_ALL_VISIONWEB_DATES   1435
#define IDC_VIEW_CONTACT_INV_DATA       1435
#define IDC_VISIONWEB_DATE_FILTER_TYPES 1436
#define IDC_MARKUP_HELP                 1437
#define IDC_VISIONWEB_PATIENT           1438
#define IDC_ROUNDUP_HELP                1438
#define IDC_VISIONWEB_LOCATION          1439
#define IDC_VISIONWEB_SUPPLIER          1440
#define IDC_SPHERE_L                    1441
#define IDC_CYLINDER_L                  1442
#define IDC_AXIS_L                      1443
#define IDC_ADDITION_L                  1444
#define IDC_SPHERE_R                    1445
#define IDC_CYLINDER_R                  1446
#define IDC_AXIS_R                      1447
#define IDC_ADDITION_R                  1448
#define IDC_PRISM_L                     1449
#define IDC_BASE_L                      1450
#define IDC_VISIONWEB_PROVIDER          1451
#define IDC_PRISM_R                     1453
#define IDD_INVEDITOR                   1454
#define IDC_BASE_R                      1454
#define IDC_BACKGROUND                  1457
#define IDC_DIST_PD_L                   1457
#define IDC_BACKGROUND2                 1458
#define IDC_NEAR_PD_L                   1458
#define IDC_BACKGROUND3                 1459
#define IDC_HEIGHT_L                    1459
#define IDC_BACKGROUND4                 1460
#define IDC_DIST_PD_R                   1460
#define IDC_NEAR_PD_R                   1461
#define IDC_HEIGHT_R                    1462
#define IDC_VISIONWEB_JOB_TYPE          1463
#define IDC_VISIONWEB_LENS_DESIGN_L     1465
#define IDC_VISIONWEB_LENS_MATERIAL_L   1466
#define IDC_VISIONWEB_LENS_TREATMENT_L  1467
#define IDC_TREATMENT_COMMENTS_L        1468
#define IDC_A_BOX                       1469
#define IDC_B_BOX                       1470
#define IDC_DBL                         1471
#define IDC_ED                          1472
#define IDC_GLASSES_ORD_INVO_NO         1473
#define IDC_VISIONWEB_FRAME_TYPE        1476
#define IDC_NAME                        1477
#define IDC_VISIONWEB_THICKNESS_TYPE    1477
#define IDC_THICKNESS_L                 1478
#define IDC_THICKNESS_R                 1479
#define IDC_MANUFACTURER                1480
#define IDC_STYLE                       1481
#define IDC_FRAME_COLOR                 1482
#define IDC_TEMPLE_LENGTH               1483
#define IDC_EYE_SIZE                    1484
#define IDC_SPECIAL_INSTRUCTIONS        1487
#define IDC_VISIONWEB_ORDER_CLR1        1488
#define IDC_VISIONWEB_ORDER_CLR2        1489
#define IDC_VISIONWEB_USERNAME          1489
#define IDC_VISIONWEB_ORDER_CLR3        1490
#define IDC_VISIONWEB_PASSWORD          1490
#define IDC_VISIONWEB_ORDER_CLR4        1491
#define IDC_VISIONWEB_ORDER_CLR5        1492
#define IDC_VISIONWEB_SUPPLIER_LIST     1495
#define IDC_VISIONWEB_LENS_DESIGN_R     1496
#define IDC_VISIONWEB_SUPPLIER_LOCATION_LIST 1496
#define IDC_VISIONWEB_LENS_MATERIAL_R   1497
#define IDC_VISIONWEB_LENS_TREATMENT_R  1498
#define IDC_TREATMENT_COMMENTS_R        1499
#define IDC_CATALOG_SETUP               1502
#define IDC_VISIONWEB_ORDER_DESCRIPTION 1503
#define IDC_SUBMIT_TO_VISIONWEB         1505
#define IDC_FRAME                       1506
#define IDC_TREATMENTS_LABEL_L          1507
#define IDC_TREATMENTS_LABEL_R          1508
#define IDC_COPY_PRESCRIPTION           1509
#define IDC_COPY_LENS                   1510
#define IDC_COPY_LENS_DESIGN            1511
#define IDC_SELECT_PRISCRIPTION         1512
#define IDC_BTN_VISIONWEB_SETUP         1513
#define IDC_FRAME_LODING_LABEL          1513
#define IDC_BTN_VISIONWEB_SETUP_CLOSE   1514
#define IDC_CLR_LOGIN                   1515
#define IDC_VISIONWEB_SERVICE_URL_LIST  1516
#define IDC_SETUP_VISIONWEB_CLR         1517
#define IDC_BTN_VSIONWEB_SETUP_OK       1518
#define IDC_BTN_VSIONWEB_SETUP_CANCEL   1519
#define IDC_SUPPLIER_VISIONWEB_CODE     1520
#define IDC_SUPPLIER_VISIONWEBCODE1     1521
#define IDC_COMBO_SUPPLIER              1522
#define IDC_VISONWEB_LOCATION_COMBO     1524
#define IDC_LOCATION_VISIONWEB_CODE     1525
#define IDC_SELECTED_SUPPLIERNAME       1526
#define IDC_CLR_VISIONWEB_SUPP_LOCATION 1528
#define IDC_BTN_ADD_LOCATION            1529
#define IDC_NXCOLOR_VISONWEB_SUPPLIER_SETUP 1530
#define IDC_CHECK_WARRANTY              1531
#define IDC_WARRANTY_TEXT               1532
#define IDC_WARRANTY                    1533
#define IDC_VISIONWEB_ORDER_STATUS_LIST 1534
#define IDC_NXVISIONWEB_ORDER_STATUS_LIST 1535
#define IDC_STATIC_CATALOG_SYNC         1536
#define IDC_CUSTOMIZE                   1537
#define IDC_VISIONWEB_PARAMETERS        1538
#define IDC_VISIONWEB_PARAMS_NXCOLOR    1539
#define IDC_OK                          1541
#define IDC_VISION_PLANS                1541
#define IDC_BTN_DELETE_RETURN           1542
#define IDC_BTN_GLASSES_CATALOG_SETUP   1542
#define IDC_PTSS_PREVIEW                1543
#define IDC_GLASSES_DESIGN_LIST         1543
#define IDC_NEXT_SUPPLIER               1545
#define IDC_PREV_SUPPLIER               1546
#define IDC_BTN_GLASSES_ITEM_ADD        1547
#define IDC_EDIT_ITEM_NAME              1549
#define IDC_EDIT_ITEM_CODE              1550
#define IDC_STATIC_ITEM_NAME            1551
#define IDC_STATIC_ITEM_CODE            1552
#define IDC_SELECTED_FRAMETYPE_LIST     1553
#define IDC_CREATED_FROM_EMN            1553
#define IDC_PREVIEW_EMN                 1554
#define IDC_SELECTED_MATERIALS_LIST     1555
#define IDC_ORDER_MESSAGES              1555
#define IDC_SELECTED_TREATMENTS_LIST    1556
#define IDC_ORDER_STATUS_LIST           1556
#define IDC_SELECTED_DESIGNS_LIST       1557
#define IDC_CHECK_IS_FRAME_DATA         1557
#define IDC_SELECTED_SUPPLIER_LIST      1558
#define IDC_INV_MANAGEMENT_OWNER_COMBO  1558
#define IDC_INV_MANAGEMENT_CATEGORY_COMBO 1559
#define IDC_IS_CONTACT_LENS             1559
#define IDC_INV_MANAGEMENT_LOCATION_COMBO 1560
#define IDC_INV_MANAGEMENT_STATUS_COMBO 1561
#define IDC_INV_MANAGEMENT_REQUEST_ITEM_BUTTON 1562
#define IDC_INV_MANAGEMENT_MAKE_REQUEST_BUTTON 1562
#define IDC_INV_MANAGEMENT_SHOW_MY_REQUESTS_CHECKBOX 1563
#define IDC_INVENTORY_STATUS_LIST       1564
#define IDC_INV_REQUEST_USER_COMBO      1569
#define IDC_INV_REQUEST_CATEGORY_COMBO  1570
#define IDC_INV_REQUEST_SELECTED_ITEM_COMBO 1571
#define IDC_INV_REQUEST_NOTES_EDIT      1573
#define IDC_INV_REQUEST_FROM_DATETIMEPICKER 1574
#define IDC_INV_REQUEST_UNTIL_DATETIMEPICKER 1576
#define IDC_INV_MANAGEMENT_CANCEL_BUTTON 1577
#define IDC_VISIONWEB_ORDER_DATE        1578
#define IDC_AVAILABLE_SERVICE_CODES     1579
#define IDC_SELECT_SERVICE_CODES        1580
#define IDC_SELECT_PRODUCTS             1581
#define IDC_GLASSES_ORDER_SERVICES      1582
#define IDC_VISIONWEBORDER_CLR5         1583
#define IDC_GLASSES_ORDER_RX_DATE       1584
#define IDC_GLASSES_ORDER_RX_DATE_EXPIRATION 1585
#define ID_GLASSES_RX_PRINTPREVIEWBTN   1586
#define IDC_BILLING_SETUP               1587
#define IDC_DESIGN_LIST                 1588
#define IDC_DESIGNS                     1590
#define IDC_MATERIALS                   1591
#define IDC_TREATMENTS                  1592
#define IDC_BILLING_SETUP_LABEL         1593
#define IDC_MATERIAL_LIST               1594
#define IDC_TREATMENT_LIST              1595
#define IDC_NXC_GLASSES_BILLING_SETUP   1596
#define IDC_JOB_TYPE_LABEL              1598
#define IDC_JOB_INSTRUCTIONS_LABEL      1599
#define IDC_DESIGN_LABEL                1600
#define IDC_MATERIAL_LABEL              1601
#define IDC_LENS_OD_LABEL               1602
#define IDC_LENS_OS_LABEL               1603
#define IDC_TREATMENT_LABEL             1604
#define IDC_TREATMENT_NOTES_LABEL       1605
#define IDC_THICKNESS_LABEL             1606
#define IDC_TREATMENT_OD_LABEL          1607
#define IDC_THICKNESS_TYPE_LABEL        1608
#define IDC_TREATMENT_OS_LABEL          1609
#define IDC_FRAME_TYPE_LABEL            1610
#define IDC_BOX_A_LABEL                 1611
#define IDC_BOX_B_LABEL                 1612
#define IDC_DBL_LABEL                   1613
#define IDC_ED_LABEL                    1614
#define IDC_MANUFACTURER_LABEL          1615
#define IDC_STYLE_LABEL                 1616
#define IDC_COLOR_LABEL                 1617
#define IDC_TEMPLE_LENGTH_LABEL         1618
#define IDC_EYE_SIZE_LABEL              1619
#define IDC_JOB_TYPE_LABEL2             1620
#define IDC_STANDARD_HISTORY_NOTES      1627
#define IDC_EDIT_STANDARD_NOTES         1628
#define IDC_LENS_COST_LABEL             1629
#define IDC_LENS_COST                   1630
#define IDC_FRAME_COST                  1631
#define IDC_FRAME_COST_LABEL            1632
#define IDC_CL_COST                     1634
#define IDC_MARKUP_SELECT               1635
#define IDC_SCANNED_FRAME               1636
#define IDC_STATICWARNING               1637
#define IDC_SELECT_FRAME                1639
#define IDC_COLLECTION_FILTER           1640
#define IDC_FRAMES_SELECT_LIST          1641
#define IDC_MANUFACTURE_FILTER          1642
#define IDC_TEXT_MANUFACTURE            1643
#define IDC_TEXT_COLLECTION             1644
#define IDC_TEXT_FRAMES                 1645
#define IDC_BRAND_FILTER                1646
#define IDC_TEXT_BRAND                  1647
#define IDC_REFRESH                     1652
#define IDC_TEXT_PRODUCT                1653
#define IDC_TEXT_MARKUP                 1654
#define IDC_FRAME_TO_PRODUCT            1657
#define IDC_SECONDARY_PRISM_R           1658
#define IDC_SECONDARY_PRISM_L           1659
#define IDC_SECONDARY_BASE_R            1660
#define IDC_SECONDARY_BASE_L            1661
#define IDC_GLASSES_ORDER_EMN_LIST      1672
#define ID_CLOSE_GLASSES_EMN_PRESCRIPTIONS 1673
#define ID_SELECT_PRESCRIPTIONS         1674
#define ID_CLOSE_GLASSES_EMN_PRESCRIPTIONS_CLOSE 1675
#define IDC_RECIEVE_FRAMES              1678
#define IDC_RECEIVE_FRAMES              1678
#define IDC_ALL_ORDERS                  1679
#define IDC_NOT_BILLED_ORDERS           1680
#define IDC_BILLED_ORDERS               1681
#define IDC_CHECK_SHIP_TO_PATIENT       1682
#define IDC_NXCOLOR1_CON_LEN            1682
#define IDC_NXCOLOR2_CON_LEN            1683
#define IDC_INV_MANAGEMENT_REMEMBER_FILTERS_CHECKBOX 1684
#define IDC_CON_LENS_PAT_LIST           1684
#define IDC_CON_LENS_LOCATION           1685
#define IDC_CON_LENS_PROVIDER           1686
#define IDC_CON_LENS_EXAM_DATE          1687
#define IDC_CON_LENS_EXPIRE_DATE        1688
#define IDC_CON_LENS_ISSUE_DATE         1689
#define IDC_CON_LENS_VISION_PLANS       1690
#define IDC_NXCOLOR3_CON_LEN            1691
#define IDC_CON_LENS_CREATED_FROM_EMN   1692
#define IDC_CON_LENS_PREVIEW_EMN        1693
#define IDC_CON_LEN_DESCRIPTION         1694
#define IDC_CON_LENS_SERVICE_CODES      1695
#define IDC_CON_LENS_SERVICES           1696
#define IDC_CON_LENS_PRODUCTS           1697
#define IDC_CON_LEN_SERVICES_RADIO      1698
#define IDC_CON_LEN_PRODUCTS_RADIO      1699
#define IDC_NXCOLOR3_CON_LEN2           1700
#define IDC_CATALOG_CPT_LIST            1701
#define IDC_CON_LENS_ORDER_DATE         1701
#define IDC_CPT_MSG_LABEL               1702
#define IDC_CON_LEN_SHIP_PATIENT        1703
#define IDC_CPT_MSG_LABEL2              1703
#define IDC_NXCOLOR4_CON_LEN            1704
#define IDC_CON_LEN_OD_SPHERE           1705
#define IDC_CON_LEN_OD_CYL              1706
#define IDC_CON_LEN_OD_AXIS             1707
#define IDC_CON_LEN_OD_ADD              1708
#define IDC_CON_LEN_OD_BC               1709
#define IDC_CON_LEN_OD_DIAM             1710
#define IDC_CON_LEN_OD_CLR              1711
#define IDC_CON_LEN_OD_QTY              1712
#define IDC_CON_LENS_SUPPLIER           1714
#define IDC_CON_LENS_OD_PRODUCT         1715
#define IDC_CON_LENS_OD_NOTES           1716
#define IDC_CON_LEN_COPY_TO_OS          1717
#define IDC_CON_LEN_BTN_PREV_RX         1718
#define IDC_CON_LEN_OS_SPHERE           1719
#define IDC_CON_LEN_OS_CYL              1720
#define IDC_CON_LEN_OS_AXIS             1721
#define IDC_CON_LEN_OS_ADD              1722
#define IDC_CON_LEN_OS_BC               1723
#define IDC_CON_LEN_OS_DIAM             1724
#define IDC_CON_LEN_OS_CLR              1725
#define IDC_CON_LEN_OS_QTY              1726
#define IDC_CON_LENS_OS_NOTES           1729
#define IDC_CON_LEN_COPY_TO_OD          1730
#define IDC_CON_LENS_OS_PRODUCT         1732
#define IDC_NXCOLOR5_CON_LEN            1733
#define IDC_CHK_FRAME_TO_BE_ORDERED     1736
#define IDC_CHECK_ROUND_UP              1736
#define IDC_CON_LEN_PREV_RX             1737
#define IDC_NEW_FRAME_CATEGORY          1738
#define IDC_BTN_FRAME_CATEGORY_PICKER   1739
#define IDC_STATIC_CATEGORY             1741
#define IDC_BTN_FRAME_CATEGORY_REMOVE   1742
#define IDC_CONTACT_LENS_PRODUCT_NAME   1743
#define IDC_NEW_CONTACT_LENS_CATEGORY   1744
#define IDC_BTN_CONTACT_LENS_CATEGORY_PICKER 1745
#define IDC_BTN_CONTACT_LENS_CATEGORY_REMOVE 1746
#define IDC_CONTACT_LENS_PRODUCT        1748
#define IDC_CONTACT_LENS_QTY_PER_PACK   1749
#define IDC_STATIC_NEW_CONTACT_LENS     1750
#define IDC_DD_CONTACT_LENS_TYPE        1751
#define IDC_CONTACT_LENS_TINT           1752
#define IDC_BTN_CONTACT_LENS_TYPE       1753
#define IDC_DD_CONTACT_LENS_MANUFACTURER 1754
#define IDC_CHK_CON_LENS_OD_TO_BE_ORDERED 1755
#define IDC_BTN_CONTACT_LENS_MANUFACTURER 1755
#define IDC_CHK_CON_LENS_OS_TO_BE_ORDERED 1756
#define IDC_CON_LEN_BILL_LABEL          1757
#define IDC_CHECK_GLASSES_RX            1757
#define IDC_GLS_ORD_BILL_LABEL          1758
#define IDC_CHECK_CONTACT_LENSE_RX      1758
#define IDC_GLS_ORD_PATIENT_RESP_AMT    1759
#define IDC_SHOW_HISTORY_CHECKBOX       1759
#define IDC_GLS_ORD_TOTAL_AMT           1760
#define IDC_GLS_ORD_VISION_RESP_AMT     1761
#define IDC_COST                        1762
#define IDC_CON_LEN_OPTICIAN            1765
#define IDC_GLASSES_ORDER_OPTICIAN      1766
#define IDC_STATIC_OD_MESSAGE1          1766
#define IDC_STATIC_OS_MESSAGE1          1767
#define IDC_CON_LENS_VISION_RESP_AMOUNT 1768
#define IDC_CON_LENS_PATIENT_RESP_AMOUNT 1769
#define IDC_CON_LENS_TOTAL_AMOUNT       1770
#define IDC_STATIC_CL_VISION_LABEL      1771
#define IDC_STATIC_GLASSES_VISION_LABEL 1772
#define IDC_BTN_FRAMES_SELECT_SERACH    1773
#define IDC_FRAMES_SELECT_COMBO_STYLE   1774
#define IDC_FRAMES_SELECT_COMBO_COLLECTION 1775
#define IDC_FRAMES_SELECT_COMBO_BRAND   1776
#define IDC_FRAMES_SELECT_COMBO_MANUFACTURER 1777
#define ID_BTN_FRAMES_SELECT_OK         1778
#define ID_BTN_FRAMES_SELECT_CANCEL     1779
#define IDC_FRAME_SELECT_LIST           1780
#define IDC_CON_LENS_ORDER_INVO_NO      1781
#define IDC_HIDE_INDEFINITE             1781
#define IDC_INDEFINITE                  1782
#define IDC_NXCOLOR_CHECKLIST           1786
#define IDC_NAME_LABEL_CHECKLIST        1787
#define IDC_DATE_DUE                    1788
#define IDC_DESCRIPTION_LABEL_CHECKLIST 1788
#define IDC_DATE_CONFIRMED              1789
#define IDC_BARCODE_LABEL_CHECKLIST     1789
#define IDC_NOTES_LABEL_CHECKLIST       1790
#define IDC_EQUIPMENT_SIGN              1796
#define IDC_SKIP_SIGN                   1797
#define IDC_USERNAME_SIGN               1798
#define IDC_PASSWORD_SIGN               1799
#define IDC_EQUIPMENT_AGREEMENT         1800
#define IDC_USERNAME_LABEL_SIGN         1801
#define IDC_PASSWORD_LABEL_SIGN         1802
#define IDC_LBL_RX_GLASSES              1803
#define IDC_LBL_RX_CONTACT_LENS         1804
#define IDC_LBL_FRAMES_COUNT            1807
#define IDC_CHK_FRAME_MANUFATURER       1808
#define IDC_CHK_FRAME_STYLE             1809
#define IDC_INV_NDC_DEF_BTN             1810
#define IDC_BTN_RX_PRINT_PREVIEW        1810
#define IDC_REMOVE_OWNER                1810
#define IDC_BUTTON_COPY_SETUP           1810
#define IDC_BUTTON_PRINT_RX             1811
#define IDC_STATIC_GLASSES_RX_PROVIDER  1812
#define IDC_STATIC_CON_LENS_RX_PROVIDER2 1813
#define IDC_NXDATALIST_PROVIDERS        1814
#define IDC_STATIC_SELECT_RX_PROVIDER3  1815
#define IDC_STATIC_SELECT_RX_MESSAGE    1817
#define IDC_PRINT_RX                    1818
#define IDC_ALL_OWNERS                  1821
#define IDC_ITEM_OWNERS                 1822
#define IDC_OWNABLE_ITEMS               1823
#define IDC_ADD_OWNER                   1825
#define IDC_OWNERS_COLOR                1826
#define IDC_MANAGE_OWNERS               1827
#define IDC_EDIT_SHOP_FEES              1829
#define IDC_CON_LENS_OD_DOCINSTRUCT     1830
#define IDC_CON_LENS_OS_DOCINSTRUCT     1831
#define IDC_NXCOLOR_GO_SERVICE_SELECT   1831
#define IDC_GLASSES_ORDER_SERVICE_SELECT_LIST 1832
#define IDC_GLASSES_SERVICE_SELECT_STATIC 1833
#define IDC_VISION_WEB_LOCATION_FILTER  1834
#define IDC_INVENTORY_CONFIGURE_CHARGE_LEVEL_PROVIDERS 1835
#define IDC_ROUND_UP_RULE               1836
#define IDC_CHECK_REMEMBER_CHARGE_PROVIDER 1837
#define IDC_LOCATION                    1911
#define IDC_LOCATION_TO                 1912
#define IDC_SUPPLIER                    1928
#define IDC_DELETE_ITEM                 1929
#define IDC_ADJUST                      1931
#define IDC_NEW_ITEM                    1932
#define IDC_PRICE_TEXT                  1933
#define IDC_ACTUAL_TEXT                 1934
#define IDC_REORDERPOINT_TEXT           1935
#define IDC_REORDERQUANTITY_TEXT        1936
#define IDC_PENDING_CH                  1937
#define IDC_LAST_COST_TEXT              1938
#define IDC_CATALOG_LABEL               1939
#define IDC_ORDER_TEXT                  1940
#define IDC_RESP_TEXT                   1941
#define IDC_BARCODE_TEXT                1942
#define IDC_STOCK                       1943
#define IDC_MARK_ITEM_INACTIVE          1943
#define IDC_ORDER_LIST                  1944
#define IDC_UO_TEXT                     1944
#define IDC_STOCK_UO                    1944
#define IDC_UU_TEXT                     1945
#define IDC_CONVERSION_TEXT             1946
#define IDC_CONVERSION_TEXT2            1947
#define IDC_CREATE                      1948
#define IDC_UU_LABEL                    1948
#define IDC_NEED                        1949
#define IDC_UO_LABEL                    1949
#define IDC_TAX                         1950
#define IDC_UU_TRANSFER_LABEL           1950
#define IDC_UU_LABEL_CONSIGNMENT        1950
#define IDC_EXTRA_COST                  1951
#define IDC_UO_TRANSFER_LABEL           1951
#define IDC_UO_LABEL_CONSIGNMENT        1951
#define IDC_BACKG                       1952
#define IDC_UU_LABEL_TO                 1952
#define IDC_LABEL_PURCHASED_INV         1952
#define IDC_UO_LABEL_TO                 1953
#define IDC_LABEL_CONSIGNMENT           1953
#define IDC_UU_LABEL_NEW                1954
#define IDC_AVAIL_TEXT                  1954
#define IDC_UO_LABEL_NEW                1955
#define IDC_NOC_PRODUCT_COMBO           1955
#define IDC_FRAMES_RELOAD               1956
#define IDC_ADV_REVCODE_INV_SETUP       2052
#define IDC_BTN_CHECK_ORDER_STATUS      2137
#define IDC_CASE_HISTORY_SELECT_LABEL   2146
#define IDC_CASE_ALLOCATION_LIST        2147
#define IDC_CASE_HISTORY_COMBO          2147
#define IDC_ORDER_STATUS_PROGRESS_BAR   2284
#define IDC_ORDER_STATUS_PROGRESS_TEXT  2285
#define IDC_GLASSES_ORDER_CONFIRMATION_BKG 2406
#define IDD_INVORDER                    2505
#define IDC_PDF_PREVIEW                 2510
#define IDC_GLASSES_ORDER_PREVIEW       2510
#define IDD_SERIAL_TRACKER              2519
#define IDC_NOC_LABEL                   2668
#define IDC_NOC_PRODUCT_LABEL           2668
#define IDD_INV_INTERNAL_MANAGEMENT_REQUEST_DLG 5511
#define IDD_ADD_SUPPLIER                13001
#define IDD_PRODUCT_ITEMS               13002
#define IDD_EQUIPMENT_MAINTENANCE_DLG   13003
#define IDD_INV_TRANSFER                13004
#define IDD_PENDING_CASE_HISTORIES_DLG  13005
#define IDD_PRODUCT_ITEM_TRANSFER_DLG   13006
#define IDD_INV_PATIENT_ALLOCATION_DLG  13007
#define IDD_INV_ALLOCATIONS_DLG         13008
#define IDD_INV_OVERVIEW_DLG            13009
#define IDD_RECEIVE_ORDER_DLG           13010
#define IDD_INVEDITRETURN               13011
#define IDD_INV_ALLOCATION_USAGE_DLG    13012
#define IDD_INV_RECONCILE_HISTORY_DLG   13014
#define IDD_INV_CONSIGNMENT_PURCHASE_DLG 13016
#define IDD_INV_BATCH_COMPLETE_ALLOCATIONS_DLG 13017
#define IDD_INV_CONSIGNMENT_ASSIGN_DLG  13019
#define IDD_AGN_INV_BETA_REMINDER_DLG   13020
#define IDD_APPTS_REQUIRING_ALLOCATIONS_DLG 13021
#define IDD_REQUIRED_ALLOCATIONS_DETAIL_DLG 13023
#define IDD_APPOINTMENTS_WITHOUT_ALLOCATIONS_DLG 13025
#define IDD_INVMULTISERIALPICKER        13027
#define IDD_PRODUCTS_TO_BE_RETURNED     13029
#define IDD_EDIT_PRODUCT_ADJUSTMENT_CATEGORIES_DLG 13031
#define IDD_INV_ORDER_DATE_FILTER_PICKER_DLG 13033
#define IDD_LINK_PRODUCTS_TO_SERVICES   13035
#define IDD_SELECT_LINKED_PRODUCTS_DLG  13037
#define IDD_PRODUCTS_TO_BE_ORDERED      13039
#define IDD_INV_RECONCILIATION_DLG      13041
#define IDD_INV_REPORTS                 13043
#define IDD_INV_RECONCILIATION_ADJUST_DLG 13044
#define IDD_SUPPLIER_STATEMENT_DLG      13046
#define IDD_CONSIGNMENT_RECONCILE_DLG   13048
#define IDD_UPDATE_PRODUCTS_DLG         13050
#define IDD_INV_FRAMES                  13053
#define IDD_INV_FRAMES_DATA             13055
#define IDD_FRAMES_OPTIONS_DLG          13057
#define IDD_INV_LABEL_REPORT            13059
#define IDD_MARKUP_FORMULA_EDITOR       13061
#define IDD_INV_VISIONWEB_DLG           13062
#define IDD_VISION_WEB_ORDER_DLG        13063
#define IDD_INV_VISIONWEB_SETUP         13065
#define IDD_INV_VISIONWEB_CATALOG_SETUP 13066
#define IDR_VISIONWEB_TAB               13066
#define IDD_INV_VISIONWEB_LOCATION_SETUP_DLG 13066
#define IDD_VISIONWEB_SERVICE_SETUP     13068
#define IDR_MENU_VISIONWEB_SUPPLIER     13070
#define IDD_VISIONWEB_ORDER_HISTORY     13071
#define IDD_GLASSES_ORDER_CONFIRMATION  13073
#define IDD_VISIONWEB_ORDER_PARAMETERS_DLG 13075
#define IDD_GLASSES_CATALOG_SETUP       13077
#define IDD_GLASSES_ITEM_DLG            13079
#define IDD_GLASSES_ITEM_EDIT_DLG       13081
#define IDD_INV_EDIT_GLASSES_ORDER_STATUS_DLG 13085
#define IDD_INV_INTERNAL_MANAGEMENT_DLG 13086
#define IDB_VISIONWEB_SETUP_LOGO        13088
#define IDB_VISIONWEB_SUBMIT_TO_LOGO    13089
#define IDD_GLASSES_CATALOG_BILLING_SETUP 13090
#define IDD_INV_ORDER_ADD_PRODUCT       13092
#define IDD_INV_ORDER_SELECT_FRAME      13094
#define IDD_GLASSES_EMN_PRESCRIPTIONS   13096
#define IDD_CONTACT_LENS_ORDER          13098
#define IDD_SELECT_MULTIPLE_CPT_DLG     13101
#define IDD_INV_CONTACT_LENS_DATADLG    13103
#define IDD_INV_FRAME_SELECTION         13107
#define IDD_SELECT_GLASSES_CONTACT_RX_PRINT_DIALOG 13108
#define IDD_INV_INTERNAL_RETURN_CHECKLIST 13109
#define IDD_INV_INTERNAL_SIGN_EQUIPMENT 13111
#define IDD_INV_OWNERS                  13113
#define IDD_GLASSES_ORDER_SELECT_SERVICES 13116
#define ID_VISIONWEB_ORDERPOPUP_EDIT    32776
#define ID_VISIONWEB_ORDERPOPUP_DELETE  32777
#define ID_VISIONWEB_ORDERPOPUP_STATUS_CHECK 32779
#define ID_SUPPLIERPOPUP_CATALOG        32781
#define ID_ORDERPOPUP_STATUSHISTORY     32782
#define ID_SUPPLIERPOPUP_REMOVE         32783
#define ID_VISIONWEB_ORDERPOPUP_CHANGE_ORDER_STATUS 32785
#define ID_REPORT_GLASSESORDER          32787
#define ID_REPORT_GLASSESRX             32788
#define ID_VISIONWEB_ORDERPOPUP_GOTOPATIENT 32789
#define ID_VISIONWEB_ORDERPOPUP_BILLORDER 32790
#define IDC_BUTTON_PRINT_BC             32800
#define IDC_NXCOLORCTRL_SELECT_FRM_CNT_LENSE 32801

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        13122
#define _APS_NEXT_COMMAND_VALUE         32791
#define _APS_NEXT_CONTROL_VALUE         1838
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
