//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by LetterWriting.rc
//

#ifndef RC_INVOKED
#pragma once
#endif


#define IDC_EDIT_FILTERS                4
#define IDC_SAVE_FILTERS                5
#define IDC_CLEAR_BTN                   6
#define IDD_LETTERS                     334
#define IDD_GROUPS                      338
#define IDD_SUPERBILL                   350
#define IDD_FILTER_DETAIL_DLG           457
#define IDD_SELECT_PACKET               610
#define IDD_EDIT_PACKET_DLG             612
#define IDD_CONFIG_PACKETS_DLG          614
#define IDD_REMOVED_FILTER              680
#define IDD_APPT_TYPE_SELECTOR          980
#define IDC_EMPLOYEE_COMBO              1001
#define IDC_OPERATOR_COMBO              1002
#define IDC_VALUE_EDIT                  1003
#define IDC_DELETE                      1006
#define IDC_DELETEFILTER                1007
#define IDC_EMAIL_CHECK                 1007
#define IDC_PERSON_TYPE_COMBO           1008
#define IDC_EDIT_SUBJECT                1008
#define IDC_ADD_ALL                     1009
#define IDC_DEFTEMPLATE_BTN             1009
#define IDC_NOINACTIVE_CHECK            1010
#define IDC_REMOVE_ALL                  1011
#define IDC_NEW_TEMPLATE_BTN            1011
#define IDC_MERGE_TO_PRINTER_CHECK      1012
#define IDC_RES_UNSELECTED              1013
#define IDC_PRACTICE_INFO_CHECK         1013
#define IDC_FILTER_BKG                  1014
#define IDC_SORT_BY_DATE                1014
#define IDC_PERSON_INFO_CHECK           1014
#define IDC_USE_DATE_RANGE              1015
#define IDC_PRINT_SUPERBILLS            1016
#define IDC_DATE_INFO_CHECK             1016
#define IDC_EXCLUDE_CANCELLED           1016
#define IDC_PRESCRIPTION_INFO_CHECK     1017
#define IDC_ADD_REMINDER_FOR_PT_MERGED  1018
#define IDC_BOTTOM_BOX                  1021
#define IDC_CUSTOM_INFO_CHECK           1021
#define IDC_RES_SELECTED                1022
#define IDC_INSURANCE_INFO_CHECK        1022
#define IDC_TYPE_SELECTED               1023
#define IDC_EMAILHTML_CHECK             1023
#define IDC_ADD                         1024
#define IDC_TYPE_UNSELECTED             1024
#define IDC_SELECT_PACKET_COLOR         1024
#define IDC_PROCEDURE_INFO_CHECK        1024
#define IDC_TEMPLATE                    1025
#define IDC_PACKET_LIST                 1025
#define IDC_BILL_INFO_CHECK             1025
#define IDC_VALUE_COMBO                 1026
#define IDC_SORT_BY_NAME                1026
#define IDC_CONFIG_PACKETS              1026
#define IDC_DOCTOR_INFO                 1026
#define IDC_EDIT_PACKET_DLG             1027
#define IDC_RESP_INFO_CHECK             1027
#define IDC_LOCATION_FILTER             1027
#define IDC_LOCATION_UNSELECTED         1027
#define IDC_EXISTING_PACKETS            1028
#define IDC_LOCATION_SELECTED           1028
#define IDC_SORT_BY_RESOURCE_DATE       1028
#define IDC_RESOURCE_UNSELECTED         1029
#define IDC_EDIT_PACKET                 1030
#define IDC_RESOURCE_SELECTED           1030
#define IDC_PUR_UNSELECTED              1031
#define IDC_COMPONENT_LIST              1032
#define IDC_PUR_SELECTED                1032
#define IDC_COMPONENT_UP                1035
#define IDC_COMPONENT_DOWN              1036
#define IDC_CONFIG_PACKETS_COLOR        1037
#define IDC_EXPORTONLY_CHECK            1038
#define IDC_DONT_EXCLUDE_PRIV_EMAIL     1039
#define IDC_HIDE_IDENTIFIER_FIELDS_CHECK 1040
#define IDC_NEXTECH_FAX                 1041
#define IDC_ADD_COPY                    1042
#define IDC_EDIT_SUBFILTER              1043
#define IDC_EXCLUDE_PATIENTS            1044
#define IDC_REMEMBER_COLUMNS            1045
#define IDC_FROM                        1046
#define IDC_REMOVED_FILTER_HELP         1046
#define IDC_TO                          1047
#define IDC_REMOVAL_EXPLANATION         1047
#define IDC_DO_NOT_ATTACH               1049
#define IDC_REMEMBER_SELECTED           1050
#define IDC_MERGE_PRINTER               1051
#define IDC_USERS_LIST                  1051
#define IDC_LABEL1                      1052
#define IDC_SUBJECT_MATTER              1052
#define IDC_LABEL2                      1053
#define IDC_CHECK_REVERSE_MERGE         1053
#define IDC_LABEL3                      1054
#define IDC_SAVE_FILTER_AS              1054
#define IDC_VALUE_LIST                  1055
#define IDC_CHECK_LOCATION_FILTER       1056
#define IDC_EMR_CHECK                   1058
#define IDC_SEPARATE_DOCUMENTS          1059
#define IDC_CHECK_SB_SHOWINACTIVERESOURCES 1060
#define IDC_FILTER_TYPE_TAB             1061
#define IDC_STATUS_UNSELECTED           1063
#define IDC_STATUS_SELECTED             1064
#define IDC_BK1                         1067
#define IDC_BK2                         1068
#define IDC_BACKGROUND6                 1069
#define IDC_STATUS_ADD_ALL              1070
#define IDC_STATUS_ADD                  1071
#define IDC_STATUS_REMOVE               1072
#define IDC_STATUS_REMOVE_ALL           1073
#define IDC_SHOW_INACTIVE               1074
#define IDC_REPOSITION                  1075
#define IDC_BATCH_MERGE_LIST            1077
#define IDC_BATCH_MERGE_NXCOLOR         1078
#define IDC_MERGE_ALL                   1079
#define IDC_MERGE_BATCH_TO_PRINTER      1080
#define IDC_TRACKING_USERS              1081
#define IDC_SELECT_ALL_STEPS            1082
#define IDC_UNSELECT_ALL_STEPS          1083
#define IDC_EXISTING_FILTER_LIST        1084
#define IDC_SHOW_ON_HOLD_LADDERS        1084
#define IDC_EXISTING_GROUP_LIST         1085
#define IDC_INCLUDE_FIELDS_GROUPBOX     1086
#define IDC_OPTIONS_GROUPBOX            1087
#define IDC_PHI_HELP_BTN                1088
#define IDC_USE_ADVANCED_CONFIG         1089
#define IDC_TEMPLATE_CONFIG             1090
#define IDC_BKG                         1092
#define IDC_BK4                         1093
#define IDC_BKG2                        1094
#define IDC_BK6                         1094
#define IDC_BKG3                        1095
#define IDC_BK3                         1096
#define IDC_MERGE                       1097
#define IDC_BK5                         1097
#define IDC_EDIT_TEMPLATE_BTN           1101
#define IDC_REMOVE                      1292
#define IDC_CANCEL                      1326
#define IDC_SUBJECT_COMBO               1346
#define IDC_SORT_ORDER_LIST             1347
#define IDC_COMBO_FIELD                 1407
#define IDC_LABEL                       1487
#define IDC_SELECTED                    1531
#define IDC_WRITE_OTHER                 1533
#define IDC_WRITE_PACKET                1534
#define IDC_WRITE_FORM                  1535
#define IDC_WRITE_LETTER                1536
#define IDC_WRITE_LABEL                 1540
#define IDC_WRITE_ENVELOPE              1541
#define IDC_GROUP_LABEL2                1544
#define IDC_GROUP_LABEL3                1545
#define IDC_RES_ADD_ALL                 1552
#define IDC_GROUPEDITOR                 1553
#define IDC_RES_ADD                     1553
#define IDC_RES_REMOVE                  1554
#define IDC_RES_REMOVE_ALL              1555
#define IDC_MASS_MAIL                   1741
#define IDC_SELCOUNT                    1742
#define IDC_AVAILTEXT                   1743
#define IDC_AVAILCOUNT                  1744
#define IDC_SAVEGROUP                   1751
#define IDC_FILTERLIST_COMBO            1771
#define IDC_NEW_FILTER_BTN              1772
#define IDC_NEW_GROUP_BTN               1773
#define IDC_FILTER_NAME_EDIT            1788
#define IDC_FILTER_BKG_LABEL            1844
#define IDC_USE_OR_BTN                  1845
#define IDC_FILTER_BKG_LABEL2           1845
#define IDC_FILTER_BKG_LABEL3           1846
#define IDC_FILTER_BKG_LABEL4           1847
#define IDC_FILTER_BKG_LABEL5           1848
#define IDC_FIELD_BTN                   1855
#define IDC_UNSELECTED                  2352
#define IDC_APPT_UNSELECTED             2353
#define IDC_APPT_SELECTED               2354
#define IDD_FILTER_EDIT_DLG             2475
#define IDD_FILTER_DLG                  2504
#define IDD_SELECT_SENDER_DLG           2628
#define IDD_BATCH_MERGE_TRACKING        2676
#define IDC_MULTI_VALUE_LIST            2749
#define IDC_APT_ADD                     33336
#define IDC_APT_REMOVE                  33337
#define IDC_APT_ADD_ALL                 33338
#define IDC_ATP_REMOVE_ALL              33339
#define IDC_TYPE_ADD_ALL                33340
#define IDC_TYPE_ADD                    33341
#define IDC_TYPE_REMOVE                 33342
#define IDC_TYPE_REMOVE_ALL             33343
#define IDC_LOC_ADD_ALL                 33344
#define IDC_LOC_ADD                     33345
#define IDC_LOC_REMOVE                  33346
#define IDC_LOC_REMOVE_ALL              33347
#define IDC_PUR_ADD_ALL                 33352
#define IDC_PUR_ADD                     33353
#define IDC_PUR_REMOVE                  33354
#define IDC_PUR_REMOVE_ALL              33355

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        596
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1091
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
