//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Marketing.rc
//

#ifndef RC_INVOKED
#pragma once
#endif


#define IDR_MAINFRAME                   128
#define IDD_MARKET_COST_ENTRY           450
#define IDD_SELECT_CONTACT_DLG          712
#define IDC_NUMBER_RAD                  1000
#define IDC_REVENUE_RAD                 1001
#define IDC_COSTS_RAD                   1002
#define IDC_CONVERSION_RAD              1003
#define IDC_CONVERSION_DATE_RAD         1004
#define IDC_INQ_TO_CONS_BY_PROC         1005
#define IDC_PROCS_PERF                  1005
#define IDC_DELETE                      1006
#define IDC_EXPENSE                     1006
#define IDC_PROS_TO_CONS_BY_PROC        1006
#define IDC_PROCS_CLOSED5               1006
#define IDC_PROS_TO_SURG_BY_PROC        1007
#define IDC_PROS_TO_CONS_BY_PROC2       1007
#define IDC_INQ_TO_CONS_BY_PROC3        1007
#define IDC_COMPLETED_ONLY              1008
#define IDC_PROCS_PERF_BY_PROC          1008
#define IDC_TOTAL_REVENUE2              1008
#define IDC_SELECT_CONTACT              1009
#define IDC_CONS_TO_SURG_BY_PAT_COORD   1009
#define IDC_PROCS_CLOSED2               1009
#define IDC_PROS_TO_CONS_BY_PROC3       1009
#define IDC_CONTACT_LIST                1010
#define IDC_PROCS_CLOSED3               1010
#define IDC_ALL_REFERRALS_CHECK         1011
#define IDC_APPT_TO_CHARGE              1011
#define IDC_SEL_REFERRALS_CHECK         1012
#define IDC_CITY_STATE                  1013
#define IDC_FIRST_THREE                 1014
#define IDC_RETENTION_PROCEDURE_LIST    1015
#define IDC_CONS1_LABEL                 1015
#define IDC_RETENTION_STEP_LIST         1016
#define IDC_CONS_LABEL                  1016
#define IDC_RANGE_LIST                  1017
#define IDC_CONS2_LABEL                 1017
#define IDC_PIVOT_DATE                  1018
#define IDC_SHOW_ALL_PROSPECTS          1018
#define IDC_CONFIGURE_APPT_TYPES        1019
#define IDC_MERGE_RANGE_LIST            1019
#define IDC_ALL_CONSULTS                1020
#define IDC_SHOW_CONS_PROSPECTS         1020
#define IDC_RETENTION_PURPOSE_LIST      1020
#define IDC_CONFIGURE_APPT_TO_CHARGE    1020
#define IDC_SPLIT_CONSULTS              1021
#define IDC_EFFECTIVENESS               1021
#define IDC_APTTYPE_NEW_CONSULT_LIST    1022
#define IDC_MONEY_BY_REFERRAL           1022
#define IDC_APTTYPE_EXISTING_CONSULT_LIST 1023
#define IDC_MONEY_BY_PROC               1023
#define IDC_ADD                         1024
#define IDC_APTTYPE_CONSULT_LIST        1024
#define IDC_PROFIT_BY_PROC              1024
#define IDC_NEW_LABEL                   1025
#define IDC_MONEY_BY_PAT_COORD          1025
#define IDC_CONS_TO_SURG                1025
#define IDC_TYPE_MOVE_RIGHT             1025
#define IDC_APTTYPE_SURGERY_LIST        1026
#define IDC_TYPE_MOVE_LEFT              1026
#define IDC_EXISTING_LABEL              1027
#define IDC_STATIC1                     1027
#define IDC_CODE_MOVE_RIGHT             1027
#define IDC_ALL_LABEL                   1028
#define IDC_STATIC2                     1028
#define IDC_CODE_MOVE_LEFT              1028
#define IDC_STATIC3                     1029
#define IDC_NEW_CONSULT_LABEL           1031
#define IDC_ALL_CONSULT_LABEL           1032
#define IDC_APPT_PURPOSE_LIST           1032
#define IDC_EXISTING_CONSULT_LABEL      1033
#define IDC_YEAR_FILTER                 1033
#define IDC_SURGERY_LABEL               1034
#define IDC_SHOW_ALL_COLUMNS            1034
#define IDC_PATS_BY_REFERRAL            1034
#define IDC_MONEY_BY_CATEGORY           1034
#define IDC_PATS_NO_SHOW_BY_PROC        1035
#define IDC_INQ_BY_REFERRAL             1035
#define IDC_SHOW_NUMBERS_ONLY           1035
#define IDC_SHOW_PERCENTAGES_ONLY       1036
#define IDC_INQ_BY_PROC                 1036
#define IDC_NO_SHOW_BY_REFERRAL2        1036
#define IDC_NO_SHOW_BY_PROC             1037
#define IDC_CANCEL_BY_PAT_COORD         1038
#define IDC_NO_SHOW_BY_PAT_COORD        1039
#define IDC_CANCEL_BY_PROC              1040
#define IDC_CANCEL_BY_REASON            1041
#define IDC_NO_SHOW_BY_REASON           1042
#define IDC_CONTACT_WITH_PROS_BY_PAT_COORD 1043
#define IDC_CONSULTS_BY_PAT_COORD       1044
#define IDC_FILTERED_LOCATION_LIST      1045
#define IDC_MULTI_PROC_LIST             1045
#define IDC_FROM                        1046
#define IDC_FILTERED_PROVIDER_LIST      1046
#define IDC_TO                          1047
#define IDC_DATE_OPTION_LIST            1047
#define IDC_PAT_COORD_LIST              1048
#define IDC_FILTERED_FROM_DATE          1049
#define IDC_FILTERED_TO_DATE            1050
#define IDC_FILTERED_CATEGORY_LIST      1051
#define IDC_RESP_FILTER                 1052
#define IDC_INCLUDE_TAX                 1053
#define IDC_EFF_LABEL6                  1060
#define IDC_RETENTION_LABEL1            1063
#define IDC_RETENTION_LABEL2            1064
#define IDC_RETENTION_LABEL3            1065
#define IDC_RETENTION_LABEL4            1066
#define IDC_RETENTION_BASED_ON          1067
#define IDC_RETENTION_LABEL5            1068
#define IDC_EFF_GRAPH                   1074
#define IDC_INQ_TO_CONS_BY_STAFF2       1075
#define IDC_REGIONAL_COLOR_TOP          1077
#define IDC_REGIONAL_COLOR_GRAPH        1078
#define IDC_REGIONAL_COLOR_REF_SOUR     1079
#define IDC_RETENTION_COLOR_FILTERS     1080
#define IDC_CHECK_INQUIRIES             1081
#define IDC_DETAILED_RADIO              1081
#define IDC_CHECK_CONSULTATIONS         1082
#define IDC_SUMMARY_RADIO               1082
#define IDC_CHECK_CLOSURE               1083
#define IDC_SHOW_INQUIRIES              1083
#define IDC_CHECK_SURGERIES             1084
#define IDC_CHECK_CLOSURE_LENGTH        1085
#define IDC_PATIENTS                    1086
#define IDC_CHECK_AVGPROC               1086
#define IDC_PATIENT_COST                1087
#define IDC_CHECK_TRACKINGNOSHOW        1087
#define IDC_CANCELLATIONS2              1087
#define IDC_CHECK_SHOWPREVYEAR          1088
#define IDC_STATIC_PATIENTS_UNLIMITED   1090
#define IDC_NUMBER                      1091
#define IDC_EFF_LABEL9                  1091
#define IDC_REFERRAL_COUNT              1092
#define IDC_FEES_BILLED                 1093
#define IDC_COLLECTED                   1094
#define IDC_REFERRAL_COST               1095
#define IDC_FEES_BILLED2                1096
#define IDC_COLLECTED2                  1097
#define IDC_PROGRESS                    1097
#define IDC_PROGRESS2                   1098
#define IDC_PATIENT_COUNT               1098
#define IDC_EDIT_CONSULTSPERMONTH       1099
#define IDC_TEXT                        1100
#define IDC_EDIT_SURGERIESPERMONTH      1100
#define IDC_STATIC_LEGEND1              1100
#define IDC_COLOR3                      1101
#define IDC_EDIT_CLOSURERATIO           1101
#define IDC_STATIC_LEGEND2              1101
#define IDC_EDIT_CLOSUREDURATION        1102
#define IDC_STATIC_LEGEND3              1102
#define IDC_STATIC_LEGEND4              1103
#define IDC_STATIC_LEGEND5              1104
#define IDC_STATIC_LEGEND6              1105
#define IDC_STATIC_LEGEND7              1106
#define IDC_MONEY_BY_REFERRAL2          1107
#define IDC_STATIC_LEGEND_LABEL         1107
#define IDC_CONVERSION_RAD2             1108
#define IDC_COLOR1                      1109
#define IDC_GRAPH_COLOR                 1110
#define IDC_NOTES                       1111
#define IDC_PATS_BY_REFERRAL2           1111
#define IDC_NO_SHOW_BY_REFERRAL3        1112
#define IDC_REFERRAL                    1114
#define IDC_MONEY_BY_PAT_COORD3         1114
#define IDC_CONS_TO_SURG_BY_PAT_COORD2  1115
#define IDC_PATIENTS4                   1116
#define IDC_CANCEL_BY_PAT_COORD2        1117
#define IDC_INQ_TO_CONS_BY_STAFF22      1118
#define IDC_TOTAL_REVENUE3              1119
#define IDC_CONVERSION_DATE_RAD3        1121
#define IDC_PATIENTS3                   1122
#define IDC_CANCELLATIONS3              1123
#define IDC_COST_LOCATION               1126
#define IDC_REPORT_ON                   1127
#define IDC_REFERRAL_SOURCE_RADIO       1128
#define IDC_REF_PHYS_RADIO              1129
#define IDC_RETAINED_RADIO              1130
#define IDC_UNRETAINED_RADIO            1131
#define IDC_GROUP_BY_BILL               1133
#define IDC_GROUP_BY_PATIENT            1134
#define IDC_DOCFROM                     1135
#define IDC_MARKETING_INCIDENTS_PER_CAT 1135
#define IDC_DOCTO                       1136
#define IDC_INCIDENTS_PER_PERSON        1136
#define IDC_INCIDENTS_PER_CLIENT        1137
#define IDC_CREATE_MERGE_GROUP          1138
#define IDC_EXCLUDE_APPTS               1139
#define IDC_INTERNAL_GRAPH              1143
#define IDC_INTERNAL_PROGRESS           1144
#define IDC_MARKET_FILTER_LIST          1146
#define IDC_USE_SCHEDULE                1147
#define IDC_USE_TRACKING                1148
#define IDC_OPEN_PER_WEEK               1148
#define IDC_RETENTION_RANGE_SETUP       1149
#define IDC_RANGE_LIST_EDIT             1150
#define IDC_MOVE_UP                     1151
#define IDC_ADD_RANGE                   1152
#define IDC_REMOVE_RANGE                1153
#define IDC_MOVE_DOWN                   1154
#define IDC_RESTORE_DEFAULTS            1157
#define IDC_REFERRAL_AREA               1158
#define IDC_MKTZIP_REFERRAL_AREA        1159
#define IDC_MKT_EFFECT_REFERRAL_AREA    1160
#define IDC_GO                          1162
#define IDC_MARKET_DATE_MULTI_PURPOSE_LIST 1174
#define IDC_RETENTION_LADDER_LIST       1175
#define IDC_RETENTION_COLOR_MERGEGROUP  1176
#define IDC_STATIC_PIE_GRAPH_REGION     1177
#define IDC_PRINT_STYLE_GROUPBOX        1178
#define IDC_COMBO_EXP_PROCEDURES        1179
#define IDC_MARKET_REF_SOURCE_FILTER    1180
#define IDC_MARKET_REF_SOURCE_LINK      1181
#define IDC_MARKET_PROC_FILTER          1182
#define IDC_MARKET_PROC_LINK            1183
#define IDC_CONFIGURE_APPT_TYPES_PROC   1184
#define IDC_CONFIGURE_APPT_TYPES_REFERRAL 1185
#define IDC_CONFIGURE_APPT_TYPES_COORDINATOR 1186
#define IDC_SHOW_ALL_COLUMNS_COORD      1187
#define IDC_SHOW_NUMBERS_ONLY_COORD     1188
#define IDC_SHOW_PERCENTAGES_ONLY_COORD 1189
#define IDC_SHOW_ALL_COLUMNS_REF        1190
#define IDC_SHOW_NUMBERS_ONLY_REF       1191
#define IDC_SHOW_NUMBERS_ONLY_PROC      1192
#define IDC_SHOW_PERCENTAGES_ONLY_REF   1193
#define IDC_SHOW_PERCENTAGES_ONLY_PROC  1194
#define IDC_SHOW_ALL_COLUMNS_PROC       1195
#define IDC_APPT_CONV_GROUP_LIST        1197
#define IDC_APPT_TYPE_AVAIL_LIST        1198
#define IDC_APPT_TYPE_SELECTED_LIST     1199
#define IDC_CODE_AVAIL_LIST             1200
#define IDC_CODE_SELECT_LIST            1201
#define IDC_ACG_RENAME                  1204
#define IDC_ACG_ADD                     1206
#define IDC_ACG_DELETE                  1207
#define IDC_ACG_CLOSE                   1208
#define IDC_CONVERSION_DAYS             1209
#define IDC_ACG_INSTRUCTIONS            1210
#define IDC_CONVERSION_GROUP_LIST       1211
#define IDC_MERGE_GROUP_OPTIONS         1212
#define IDC_ENABLE_EXCLUDE_UNRETAINED   1215
#define IDC_EXCLUDE_UNRETAINED_RANGE    1216
#define IDC_MERGE_OPTION_CAPTION        1217
#define IDC_COLOR                       1335
#define IDC_RETENTION_COLOR_CHART       1336
#define IDC_PREVIEW_BTN                 1382
#define IDC_NXCOLORCTRL1                1383
#define IDC_BACKGROUND                  1457
#define IDC_BACKGROUND2                 1458
#define IDC_UP                          1525
#define IDC_GRAPH                       1720
#define IDC_RECIEVER                    1760
#define IDC_COST                        1762
#define IDC_MULTI_PROCEDURE_LABEL       1763
#define IDC_MULTI_PROCEDURE_EXP_LABEL   1763
#define IDC_DTPAID                      1767
#define IDC_TREE                        1771
#define IDC_CHART                       1811
#define IDC_NXDATALISTCTRL              1924
#define IDC_LIST_BY_BILL                1925
#define IDC_PORTRAIT_RADIO              1952
#define IDC_LANDSCAPE_RADIO             1953
#define IDC_ORIENTATION_STATIC          1954
#define IDC_REF_PATIENT_RADIO           1954
#define IDD_MARKET_COST                 2495
#define IDD_MARKET_EFFECT               2496
#define IDD_MARKET_ZIP                  2499
#define IDD_MARKET_RETENTION_PERCENTAGE 2614
#define IDD_CONFIGURE_CONVERSION_GRAPH  2615
#define IDD_MARKET_CONVERSION_RATE      2620
#define IDD_PATIENT_COORDINATOR         2624
#define IDD_REFERRAL_SOURCE             2626
#define IDD_PROCEDURE                   2630
#define IDD_DATE                        2632
#define IDD_MARKET_OTHER                2634
#define IDD_MARKET_BASELINE             2636
#define IDD_MARKET_BASELINE_CONFIG      2641
#define IDD_MARKET_PRINT_SETUP_DLG      2642
#define IDD_MARKET_REFERRALS_PRINT_DLG  2643
#define IDD_ACTIVITIES_SETMARKETINGBASELINEGOALS 2644
#define IDD_MARKET_BAR                  2646
#define IDD_MARKET_FILTER_PICKER_DLG    2662
#define IDD_MARKET_RETENTION_RANGE_CONFIG_DLG 2670
#define IDD_CONFIGURE_APPT_GROUPS_DLG   2674
#define IDD_MARKET_INTERNAL             2699
#define IDD_MARKET_RETENTION_PRINT_SETUP 11335

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2675
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1218
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
