#if !defined(AFX_NXCOLOR_H__CC3EB0D6_9242_40B2_9AB2_3FD3D1A09E98__INCLUDED_)
#define AFX_NXCOLOR_H__CC3EB0D6_9242_40B2_9AB2_3FD3D1A09E98__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CNxColor wrapper class

class CNxColor : public CWnd
{
protected:
	DECLARE_DYNCREATE(CNxColor)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xb4d2b106, 0x9bde, 0x11d1, { 0xb2, 0xc8, 0x0, 0x0, 0x1b, 0x4b, 0x97, 0xb } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	unsigned long GetColor();
	void SetColor(unsigned long);
	short GetAppearance();
	void SetAppearance(short);
	unsigned long GetBackColor();
	void SetBackColor(unsigned long);
	void EnableGradients(BOOL); // (z.manning 2011-09-19 11:02) - PLID 44676

// Operations
public:
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_NXCOLOR_H__CC3EB0D6_9242_40B2_9AB2_3FD3D1A09E98__INCLUDED_)
