//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Scheduler.rc
//
#define IDC_DELETE_BTN                  3
#define ID_ADVPALM                      3
#define IDC_BTN_HELP                    3
#define IDC_BTN_CANCEL_LINK             3
#define IDC_BTN_OVERRIDE                3
#define IDC_EXTRA_INFO_BTN              4
#define IDC_BTN_FFA                     4
#define ID_APP_HISTORY_BTN              4
#define ID_RES_DELETEBLOCK              101
#define IDD_CANCELAPPOINTMENTS          135
#define IDD_RESCHEDULING_CANCEL_APPT    135
#define IDD_MULTI_RESOURCE_DLG          152
#define IDR_RES_POP_UP_MENU             175
#define IDD_FIRST_AVAILABLE_APPT        244
#define IDD_MONTH_DLG                   245
#define IDD_ONE_DAY_DLG                 246
#define IDD_TEMPLATES_DLG               252
#define IDD_WEEK_DAY_DLG                253
#define IDD_PRINT_SCHEDULE_DLG          254
#define IDD_RES_ENTRY_DLG               257
#define IDD_TEMPLATE_LINE_ITEM_DLG      259
#define IDD_TEMPLATE_ENTRY_DLG          260
#define IDD_SUPERBILL                   350
#define IDD_RULE_ENTRY_DLG              583
#define IDD_INPUT_LIST                  584
#define IDD_FIRST_AVAIL_LIST            586
#define IDR_RESENTRY_MENU               592
#define IDD_SHOW_MOVEUP_LIST            701
#define IDD_PALM_PREFERENCES            703
#define IDR_SCHEDULER_CONTEXT_MENUS     705
#define IDD_SCHEDULED_PATIENTS_DLG      706
#define IDD_MULTIRESOURCE_PASTE         708
#define IDD_RES_LINK_DLG                710
#define ID_LINKACTION_GOTOAPPT          711
#define IDI_PIN_UP                      720
#define IDI_PIN_DOWN                    721
#define IDI_BOLD                        722
#define IDD_REASON_DLG                  723
#define IDD_SINGLESELECT_DLG            728
#define IDC_SCALE_COMBO                 1001
#define IDC_BY_COMBO                    1002
#define IDC_START_TIME_BOX              1003
#define IDC_EVERY_1_RADIO               1003
#define IDC_PATIENT_COMBO               1004
#define IDC_EVERY_2_RADIO               1004
#define IDC_END_TIME_BOX                1005
#define IDC_EVERY_X_RADIO               1005
#define IDC_EVERY_X_TEXT                1006
#define IDC_ARRIVAL_TIME_BOX            1006
#define IDC_PURPOSE_COMBO               1007
#define IDC_ONE_DAY_CTRL                1007
#define IDC_APTPURPOSE_COMBO            1008
#define IDC_MOVE_DAY_BACK               1009
#define IDC_PIVOT_DATE_COMBO            1009
#define IDC_APTTYPE_COMBO               1009
#define IDC_MOVE_DAY_FORWARD            1010
#define IDC_APPLY_DATE                  1010
#define IDC_UNSELECTED_RESOURCES        1010
#define IDC_APTRESOURCE_COMBO           1010
#define IDC_APTLOCATION_COMBO           1011
#define IDC_APPLY_DATE_END              1011
#define IDC_MOVE_WEEK_BACK              1012
#define IDC_SELECT_ALL_ITEMS            1012
#define IDC_LIST_STATUS                 1012
#define IDC_SELECT_ALL                  1013
#define IDC_RES_UNSELECTED              1013
#define IDC_SELECT_ONE_ITEM             1013
#define IDC_REQUESTED_RESOURCE          1013
#define IDC_EVERY_X_STATIC              1014
#define IDC_UNSELECT_ONE                1014
#define IDC_SORT_BY_DATE                1014
#define IDC_MOVE_WEEK_FORWARD           1014
#define IDC_EDIT_REASON_COMBO           1014
#define IDC_BY_LABEL                    1015
#define IDC_UNSELECT_ALL                1015
#define IDC_USE_DATE_RANGE              1015
#define IDC_PRINT_SUPERBILLS            1016
#define IDC_MONDAY_CHECK                1018
#define IDC_THURSDAY_CHECK              1019
#define IDC_TUESDAY_CHECK               1020
#define IDC_DATE_SEL_COMBO              1021
#define IDC_FRIDAY_CHECK                1021
#define IDC_WEDNESDAY_CHECK             1022
#define IDC_RES_SELECTED                1022
#define IDC_ONE_DAY_EVENT_CTRL          1022
#define IDC_SUNDAY_CHECK                1023
#define IDC_TYPE_SELECTED               1023
#define IDC_WEEK_EVENT_CTRL             1023
#define IDC_SATURDAY_CHECK              1024
#define IDC_TYPE_UNSELECTED             1024
#define IDC_BTN_NEW_EVENT               1024
#define IDC_TEMPLATE                    1025
#define IDC_STATIC_START                1025
#define IDC_BTN_ROOMMANAGER             1025
#define IDC_PERIOD_FRAME                1026
#define IDC_SORT_BY_NAME                1026
#define IDC_STATIC_END                  1026
#define IDC_INCLUDE_FRAME               1027
#define IDC_MONTH_EVENT_CTRL            1027
#define IDC_STATIC_ARRIVAL              1027
#define IDC_MOVEUP_COMBO                1028
#define IDC_SCOPE_FRAME                 1028
#define IDC_CONFIRMED_COMBO             1029
#define IDC_START_TIME_COMBO            1029
#define IDC_NOTES_BOX                   1030
#define IDC_END_TIME_COMBO              1030
#define IDC_PATTERN_ORDINAL_COMBO       1031
#define IDC_WEEK_DAY_CTRL               1033
#define IDC_START_TIME                  1034
#define IDC_END_TIME                    1035
#define IDC_WARNING_EDIT                1036
#define IDC_TYPE_CHECK                  1037
#define IDC_ACTIVE_DATE_LABEL           1038
#define IDC_PURPOSE_CHECK               1038
#define IDC_DAY_NUMBER_LABEL            1039
#define IDC_MULTI_RESOURCE_CTRL         1039
#define IDC_BOOKING_CHECK               1039
#define IDC_DAY_NUMBER_EDIT             1040
#define IDC_LISTOF_PURPOSES             1040
#define IDC_BY_DATE_FRAME               1041
#define IDC_LISTOF_TYPES                1041
#define IDC_RESULTS_LABEL               1042
#define IDC_INPUT_LIST                  1042
#define IDC_LISTOF_BOOKINGS             1042
#define IDC_DAY_NUMBER_SPIN             1043
#define IDC_WARN_CHECK                  1043
#define IDC_LINE_ITEM_LIST              1044
#define IDC_PREVENT_CHECK               1044
#define IDC_ADD_LINE_ITEM_BTN           1045
#define IDC_FROM                        1046
#define IDC_TO                          1047
#define IDC_EDIT_LINE_ITEM_BTN          1048
#define IDC_PRIORITY_EDIT               1049
#define IDC_ADD_RULE_BTN                1051
#define IDC_DATE                        1052
#define IDC_EDIT_RULE_BTN               1052
#define IDC_EVENT_DATE_START            1053
#define IDC_EVENT_DATE_END              1054
#define IDC_ADD_EXCEPTION_BTN           1054
#define IDC_REMOVE_LINE_ITEM_BTN        1055
#define IDC_REMOVE_RULE_BTN             1056
#define IDC_EDIT_EXCEPTION_BTN          1057
#define IDC_REMOVE_EXCEPTION_BTN        1058
#define IDC_RES_PATIENT_ID_BOX          1062
#define IDC_RES_PATIENT_HOME_PHONE_BOX  1063
#define IDC_AM_PM_BTN                   1063
#define IDC_RES_PATIENT_BIRTH_DATE_BOX  1064
#define IDC_TODAY_BTN                   1064
#define IDC_AM_PM_BTN2                  1065
#define IDC_VIEW_MIX_RULES              1065
#define IDC_RES_PATIENT_WORK_PHONE_BOX  1066
#define IDC_RES_PATIENT_CELL_PHONE_BOX  1067
#define IDC_PATIENT_ID_CHECK            1068
#define IDC_HOME_PHONE_CHECK            1069
#define IDC_WORK_PHONE_CHECK            1070
#define IDC_BIRTH_DATE_CHECK            1071
#define IDC_CELL_PHONE_CHECK            1072
#define IDC_PREFERRED_CONTACT_CHECK     1073
#define IDC_CHOOSE_PURPOSE              1073
#define IDC_MOVE_MONTH_BACK             1074
#define IDC_RES_PATIENT_PREFERRED_CONTACT_BOX 1074
#define IDC_MOVE_MONTH_FORWARD          1075
#define IDC_WEEK_LABEL_0                1076
#define IDC_RES_PTBAL_BOX               1076
#define IDC_WEEK_LABEL_1                1077
#define IDC_WEEK_LABEL_2                1078
#define IDC_RES_INSBAL_BOX              1078
#define IDC_WEEK_LABEL_3                1079
#define IDC_WEEK_LABEL_4                1081
#define IDC_ALL_RESOURCES_RADIO         1081
#define IDC_GRAPHICAL_RADIO             1081
#define IDC_WEEK_LABEL_5                1082
#define IDC_TEXTUAL_RADIO               1082
#define IDC_SELECT_RESOURCES_RADIO      1083
#define IDC_CHECK_MON                   1087
#define IDC_CHECK_TUE                   1088
#define IDC_BKG                         1092
#define IDC_BKG2                        1094
#define IDC_BKG3                        1095
#define IDC_CHOOSE_COLOR_BTN            1099
#define IDC_ADD_TEMPLATE_BTN            1099
#define IDC_ALL_TO_SELECTED             1099
#define IDC_NEW_TEMPLATE_CHOOSE_COLOR   1099
#define IDC_REMOVE_TEMPLATE_BTN         1100
#define IDC_TO_AVAIL                    1100
#define IDC_EDIT_TEMPLATE_BTN           1101
#define IDC_ALL_TO_AVAIL                1101
#define IDC_TO_SELECTED                 1102
#define IDC_CHOOSE_TYPE                 1102
#define IDC_PATBAL_CHECK                1103
#define IDC_INSBAL_CHECK                1104
#define IDC_TEMPLATE_DROPDOWN           1104
#define IDC_SELECT_EXISTING_TEMPLATE    1105
#define IDC_NEW_TEMPLATE_LINE_ITEM      1106
#define IDC_CHECK_WED                   1108
#define IDC_CHECK_THU                   1109
#define IDC_CHECK_FRI                   1110
#define IDC_COUNT_TYPE_LIST             1110
#define IDC_CHECK_SAT                   1111
#define IDC_SINGLE_DAY_CTRL             1121
#define IDC_MOVE_PRIORITY_UP_BTN        1124
#define IDC_FIRST_DAY_FRAME             1130
#define IDC_EDIT_ACTIVE_SINGLEDAY_DAY   1134
#define IDC_SPIN_NAME_OFFSETS           1135
#define IDC_STATIC_SUN                  1136
#define IDC_STATIC_MON                  1137
#define IDC_STATIC_TUE                  1138
#define IDC_STATIC_WED                  1139
#define IDC_STATIC_THU                  1140
#define IDC_STATIC_FRI                  1141
#define IDC_STATIC_SAT                  1142
#define IDC_TEMPLATE_NAME_EDIT          1143
#define IDC_REFERRING_PHYS_LIST         1160
#define IDC_REASON_COMBO                1186
#define IDC_AVAILABLE_LIST              1205
#define IDC_SELECTED_LIST               1206
#define IDC_CHECK_SUN                   1219
#define IDC_CHECK_ANY_TIME              1222
#define IDC_CHECK_EARLY_MORN            1223
#define IDC_CHECK_LATE_MORN             1224
#define IDC_CHECK_EARLY_AFTN            1225
#define IDC_CHECK_LATE_AFTN             1226
#define IDC_CHECK_OFFICE_HOURS_ONLY     1227
#define IDC_LIST_TIME_PREFS             1233
#define IDC_LIST_HOURS                  1234
#define IDC_LIST_MINUTES                1235
#define IDC_BKG_ROOM_STATUS             1289
#define IDC_CANCEL                      1326
#define IDC_TEMPLATES_LIST              1351
#define IDC_PREVIEW_BTN                 1382
#define IDC_MOVE_PRIORITY_DOWN_BTN      1392
#define IDC_RESOURCE_ORDER_BTN          1394
#define IDC_COLOR_PICKER_CTRL           1399
#define IDC_RESOURCE_LIST               1406
#define IDC_INTERVAL                    1407
#define IDC_RES_ADD_ALL                 1552
#define IDC_RES_ADD                     1553
#define IDC_RES_REMOVE                  1554
#define IDC_RES_REMOVE_ALL              1555
#define IDC_NEW_TEMPLATE_NAME           1758
#define IDC_COLOR_CHOOSER_CTRL          1759
#define IDC_DESCRIPTION_EDIT            1778
#define IDC_FFA_SELECT_ALL_RESOURCES    1859
#define IDC_FFA_SELECT_NO_RESOURCES     1860
#define IDC_GOTOPATIENT                 1862
#define IDC_BTN_CHANGEPATIENT           1863
#define IDC_BTN_NEWPATIENT              1864
#define IDC_GOTO_INSURANCE              1865
#define IDC_DATE_START                  1900
#define IDC_RADIO_START_FROM            1902
#define IDC_RADIO_STARTPAT              1903
#define IDC_EDIT_DAYS_AFTER             1904
#define IDC_PATIENT_LIST_COMBO          1905
#define IDC_FFA_DEFAULT_LOCATION_COMBO  1906
#define IDC_FFA_DEFAULT_RESOURCE_COMBO  1907
#define IDC_UNSELECTED_RESOURCES_COMBO  1908
#define IDC_FFA_APP_HIST_LIST           1909
#define IDC_CHECK_RESULTS               1910
#define IDC_LISTOF_ANDDETAILS           1912
#define IDC_MOVEUPLIST                  1913
#define IDC_APPOINTMENTS                1913
#define IDC_APPOINTMENTS_GROUPED        1914
#define IDC_COMBO_APTPURPOSE_FILTER     1918
#define IDC_COMBO_APTTYPE_FILTER        1919
#define IDC_COMBO_LOCATION_FILTER       1920
#define IDC_CHECK_PRINT_TEMPLATE_COLOR  1921
#define IDC_CHECK_PRINT_PROCEDURES      1922
#define IDC_CHECK_PRINT_PENDING         1923
#define IDC_CHECK_VIEWED_RESOURCES      1924
#define IDC_CHECK_PRINT_TEMPLATES       1925
#define IDC_STATIC_MOVEUP               1926
#define IDC_STATIC_CONFIRMED            1927
#define IDC_STATIC_DATE                 1928
#define IDC_STATIC_END_DATE             1929
#define IDC_STATIC_START_DATE           1930
#define IDC_ACTIVE_DATE_APTCOUNT_LABEL  1932
#define IDC_STATIC_CONFIRMED3           1932
#define IDC_CHECK_SHOW_CANCELLED_APPTS  1934
#define IDC_ACTIVE_RESOURCES_APTCOUNT_LABEL 1934
#define IDC_RESOURCE_EVENT_CTRL         1935
#define IDC_ACTIVE_WEEK_APTCOUNT_LABEL  1935
#define IDC_RADIO_AND_RESOURCE          1938
#define IDC_RADIO_OR_RESOURCE           1939
#define IDC_STATIC_NOT_APPLICABLE       1940
#define IDC_STATIC_DESCRIPTION          1945
#define IDC_MULTISELECT_LIST            1946
#define IDC_STATIC_LISTOFPURPOSES       1951
#define IDC_PORTRAIT_RADIO              1952
#define IDC_LANDSCAPE_RADIO             1953
#define IDC_ORIENTATION_STATIC          1954
#define IDC_GOTOAPPOINTMENT             1956
#define IDC_BTN_MOVEUP                  1957
#define IDC_PREVIEW_MOVEUP_LIST         1958
#define IDC_COMBO_PALMUSERLIST          1959
#define IDC_PALM_DIALOG_TAB             1961
#define IDC_PALM_RESOURCE_LIST          1962
#define IDC_STATIC_AVAILABLE_FIELDS     1963
#define IDC_STATIC_RESOURCES            1964
#define IDC_SCHEDULED_PATIENT_LIST      1965
#define IDC_STATIC_DISPLAYED_FIELDS     1966
#define IDC_PALMPREF_ADD                1967
#define IDC_PALMPREF_REMOVE             1968
#define IDC_LIST_RESOURCE               1969
#define IDC_PALMPREF_RENAME             1970
#define IDC_RADIO_CREATETODO            1975
#define IDC_RADIO_DONOTHING             1976
#define IDC_APPOINTMENTS_UNGROUPED      1976
#define IDC_SAVE_CREATE_CASE_HISTORY    1977
#define IDC_DAY_LABEL_05                1977
#define IDC_DAY_LABEL_06                1978
#define IDC_DAY_LABEL_07                1979
#define IDC_DAY_LABEL_08                1980
#define IDC_DAY_LABEL_09                1981
#define IDC_DAY_LABEL_10                1982
#define IDC_DAY_LABEL_11                1983
#define IDC_DAY_LABEL_12                1984
#define IDC_DAY_LABEL_13                1985
#define IDC_DAY_LABEL_14                1986
#define IDC_DAY_LABEL_15                1987
#define IDC_DAY_LABEL_16                1988
#define IDC_DAY_LABEL_17                1989
#define IDC_DAY_LABEL_18                1990
#define IDC_DAY_LABEL_19                1991
#define IDC_DAY_LABEL_20                1992
#define IDC_DAY_LABEL_00                1993
#define IDC_DAY_LABEL_01                1994
#define IDC_DAY_LABEL_02                1995
#define IDC_DAY_LABEL_03                1996
#define IDC_DAY_LABEL_04                1997
#define IDC_EDIT_ALARM_DESCRIPTION      1998
#define IDC_APT_BOOK_ALARM_DETAIL_LIST  1999
#define IDC_CHECK_APT_BEFORE            2001
#define IDC_CHECK_APT_AFTER             2002
#define IDC_CHECK_SAME_TYPE             2003
#define IDC_CHECK_ALLOW_SAVE            2004
#define IDC_LABEL_DAYS_BEFORE           2005
#define IDC_LABEL_DAYS_AFTER            2006
#define IDC_CHECK_SAME_PURPOSE          2007
#define IDC_APT_BOOKING_ALARM_LIST      2008
#define IDC_CHECK_INCLUDE_NO_SHOWS      2008
#define IDC_ADD_ALARM_BTN               2009
#define IDC_CHECK_SAME_RESOURCE         2009
#define IDC_EDIT_ALARM_BTN              2010
#define IDC_REMOVE_ALARM_BTN            2011
#define IDC_ADD_APT_ALARM_DETAIL_BTN    2012
#define IDC_EDIT_APT_ALARM_DETAIL_BTN   2013
#define IDC_REMOVE_APT_ALARM_DETAIL_BTN 2014
#define IDC_RADIO_MOVEALL               2015
#define IDC_EDIT_SEARCH_INTERVAL        2016
#define IDC_STATIC_SHOW_IN              2017
#define IDC_APPT_TYPE_LIST              2019
#define IDC_APPT_PURPOSE                2020
#define IDC_APPT_RESOURCE               2021
#define IDC_ALL_CHECK                   2023
#define IDC_CHECK_EXCLUDE_WARNINGS      2024
#define IDC_STATIC_DAYSAFTER            2025
#define IDC_STATIC_NODAYSAFTER          2026
#define IDC_EXTRA_FIELDS1               2027
#define IDC_EXTRA_FIELDS2               2028
#define IDC_EXTRA_FIELDS3               2029
#define IDC_EXTRA_FIELDS4               2030
#define IDC_DATE_MOVEUP                 2030
#define IDC_EXTRA_FIELDS5               2031
#define IDC_MOVEUP_TIME_BOX             2031
#define IDC_EXTRA_FIELDS6               2032
#define IDC_PRINT_GRID                  2032
#define IDC_EXTRA_FIELDS7               2033
#define IDC_EXTRA_FIELDS8               2034
#define IDC_STATIC_MININTERVALS         2034
#define IDC_EXTRA_INFO_OFFSET_LABEL     2039
#define IDC_STATIC_MOVEUPDATETIME       2040
#define IDC_PIN_RESENTRY                2041
#define IDC_RES_INS_MORE                2042
#define IDC_EXTRA_BOLD1                 2046
#define IDC_EXTRA_BOLD2                 2047
#define IDC_EXTRA_BOLD3                 2048
#define IDC_REASON_PATIENT              2048
#define IDC_EXTRA_BOLD4                 2049
#define IDC_EXTRA_BOLD5                 2050
#define IDC_EXTRA_BOLD6                 2051
#define IDC_CUSTOM_REASON_EDIT          2051
#define IDC_EXTRA_BOLD7                 2052
#define IDC_REASON_START_TIME           2052
#define IDC_EXTRA_BOLD8                 2053
#define IDC_REASON_END_TIME             2053
#define IDC_REASON_DATE                 2054
#define IDC_REASON_TYPE                 2055
#define IDC_REASON_TEXT                 2056
#define IDC_REASON_PURPOSE              2057
#define IDC_CUSTOM_REASON               2058
#define IDC_REQUESTED_RESOURCE_LABEL    2064
#define IDC_SINGLESELECT_LIST           2065
#define IDC_REFERRING_PHYS_LABEL        2065
#define IDC_BTN_SHOWPATIENTINFORMATION  2066
#define IDC_REASON_CAPTION              2067
#define IDC_CHECK_OLDTEMPLATES          2069
#define IDC_BTN_PREVIEW_REPORT          2069
#define IDC_CURRENT_VIEW_NAME           2070
#define IDC_EDIT_SEARCH_DAYS            2071
#define IDC_STATIC_SEARCH_UP_TO         2072
#define IDC_STATIC_DAYS_IN_FUTURE       2073
#define IDC_APPLY_DATE_END_LABEL        2074
#define IDC_APPLY_DATE_LABEL            2075
#define IDC_STATIC_RESOURCE             2076
#define IDC_TODAYS_PATIENTS_LIST        2077
#define IDC_ROOM_LIST                   2078
#define IDC_CLOSE_ROOM_MANAGER          2079
#define IDC_BTN_ROOM_EDITOR             2080
#define IDC_BTN_EDIT_ROOM_STATUS        2081
#define IDC_WAITING_AREA_LIST           2082
#define IDC_BTN_ADD_ROOM                2083
#define IDC_CHECKOUT_LIST               2083
#define IDC_BTN_DELETE_ROOM             2084
#define IDC_BTN_INACTIVATE_ROOM         2085
#define IDC_BTN_CLOSE_ROOM_SETUP        2086
#define IDC_BTN_ADD_ROOM_STATUS         2087
#define IDC_BTN_DELETE_ROOM_STATUS      2088
#define IDC_BTN_INACTIVATE_ROOM_STATUS  2089
#define IDC_BTN_CLOSE_ROOM_STATUS_SETUP 2090
#define IDC_ROOM_STATUS_LIST            2091
#define IDC_CHECK_SHOW_INACTIVE_ROOMS   2092
#define IDC_CHECK_SHOW_INACTIVE_ROOM_STATUSES 2093
#define IDC_BKG_ROOM_SETUP              2094
#define IDC_APPT_LABEL                  2095
#define IDC_ROOM_SELECTION_COMBO        2096
#define IDC_MOVEUP_BKG                  2098
#define IDC_TEMPLATE_ITEM_ENTRY_CTRL    2100
#define IDC_APPLY_DATE_START            2102
#define IDC_CLOSE_BTN                   2102
#define IDC_CHECK_TO_DATE               2103
#define IDC_OPTIONS_BTN                 2103
#define IDC_SCHEDULE_TEMPLATING_HELP    2104
#define IDC_LIST_TEMPLATE_RESOURCES     2105
#define IDC_CREATE_COLLECTION_FROM_VIEW 2105
#define IDC_CREATE_COLLECTION_FROM_VIEW_BTN 2105
#define IDC_OPTIONS_BTN2                2106
#define IDC_REMOVE_TEMPLATES_BTN        2106
#define IDC_RADIO_ALL_RESOURCES         2107
#define IDC_RADIO_SELECT_RESOURCES      2108
#define IDC_TEMPLATE_LIST_PLACEHOLDER   2109
#define IDC_CHECK_TOP_PRIORITY          2111
#define IDC_CHECK_IGNORE_TEMPLATE       2112
#define IDC_EXCEPTION_DATE_START        2113
#define IDC_EXCEPTION_DATE_END          2114
#define IDC_EDIT_EXCEPTION_DESCRIPTION  2115
#define IDC_CHECK_HIDE_OLD_LINEITEMS    2116
#define IDC_CHANGE_ONCE                 2117
#define IDC_CHANGE_LINE_ITEM            2118
#define IDC_CHANGE_TIME_PROMPT          2119
#define IDC_BTN_ADD_LINE_ITEM_EXCEPTION 2121
#define IDC_BTN_EDIT_LINE_ITEM_EXCEPTION 2122
#define IDC_BTN_REMOVE_LINE_ITEM_EXCEPTION 2123
#define IDC_CHECK_BLOCK_APPTS           2124
#define IDC_BTN_SHOWEXINFO              2125
#define IDC_DEFAULT_LINE_ITEMS_AS_BLOCKS 2128
#define IDC_DEFAULT_LINE_ITEMS_ALL_RESOURCES 2129
#define IDC_STATIC_DAY_OF_WEEK          2130
#define IDC_BTN_SCHEDULE                2132
#define IDC_CHECK_GO_SELECTED_DAY       2133
#define IDC_BTN_NEW_FFA_SEARCH          2134
#define IDC_BTN_SCHEDULE_EDIT           2135
#define IDC_BTN_SCHEDULE_KEEP_OPEN      2136
#define IDC_BTN_GO_SELECTED_DAY         2137
#define IDC_ROOM_MGR_RESOURCE_COMBO     2141
#define IDC_ROOM_MGR_MULTI_RESOURCE_LABEL 2142
#define IDC_LIST_EXCEPTION_DATES        2143
#define IDC_ROOM_MGR_LOCATION_COMBO     2143
#define IDC_ROOM_MGR_WAITINGROOM_COMBO  2144
#define IDC_STATIC_FOREVER              2145
#define IDC_LIST_LINE_ITEMS             2146
#define IDC_LIST_RULES                  2147
#define IDC_LIST_EXCEPTIONS             2148
#define IDC_STATIC_PATIENT              2148
#define IDC_STATIC_PURPOSE              2151
#define IDC_STATIC_APPT_TYPE            2152
#define IDC_STATIC_WAIT_LIST_ITEMS      2154
#define IDC_STATIC_NOTES                2155
#define IDC_WAIT_LIST_NOTES             2156
#define IDC_ADD_REQUEST_ITEM            2157
#define IDC_EDIT_REQUEST_ITEM           2158
#define IDC_REMOVE_REQUEST_ITEM         2159
#define IDC_STATIC_DATE_ENTERED         2160
#define IDC_DATE_ENTERED                2161
#define IDC_STATIC_RESULTS              2163
#define IDC_WL_RESOURCES                2164
#define IDC_DATE_END                    2165
#define IDC_ADD_WAIT_LIST_PATIENT       2170
#define IDC_WL_PATIENT                  2174
#define IDC_WL_APPT_TYPE                2175
#define IDC_WL_PURPOSE                  2176
#define IDC_WL_DATE_START               2177
#define IDC_WL_DATE_END                 2178
#define IDC_WL_START_TIME               2179
#define IDC_WL_END_TIME                 2180
#define IDC_REQUEST_LIST                2186
#define IDC_WL_PURPOSE_MULTI_LIST       2188
#define IDC_MULTIPLE_RESOURCE_LABEL     2189
#define IDC_WAITING_LIST_MATCHES        2190
#define IDC_WL_MATCH_LABEL              2191
#define IDC_WL_BTN_DELETE_MATCHES       2193
#define IDC_CRITERIA_GROUPBOX           2195
#define IDC_RESOURCE_GROUPBOX           2196
#define IDC_ADV_SETTINGS_GROUPBOX       2197
#define IDC_HOW_LONG_GROUPBOX           2198
#define IDC_DEFAULT_SETTINGS_GROUPBOX   2198
#define IDC_DAY_GROUPBOX                2199
#define IDC_TIME_GROUPBOX               2200
#define IDC_SCHED_PRINT_STYLE_GROUPBOX  2201
#define IDC_START_DATE_GROUPBOX         2201
#define IDC_PROPERTIES_GROUPBOX         2202
#define IDC_APPLIES_GROUPBOX            2204
#define IDC_APPEARANCE_GROUPBOX         2205
#define IDC_RESULTS_GROUPBOX            2206
#define IDC_DESC_GROUPBOX               2207
#define IDC_RULE_OPTIONS_GROUPBOX       2208
#define IDC_WARNING_GROUPBOX            2209
#define IDC_MORE_INFO_GROUPBOX          2210
#define IDC_GROUPED_GROUPBOX            2211
#define IDC_NOT_GROUPED_GROUPBOX        2212
#define IDC_WARN_OPTIONS_GROUPBOX       2213
#define IDC_DATES_GROUPBOX              2214
#define IDC_EXCEPTION_TYPE_GROUPBOX     2215
#define IDC_SUPERBILL_BY_TYPE           2219
#define IDC_SUPERBILL_TYPE_LIST         2220
#define IDC_SUPERBILL_BY_RESOURCE       2221
#define IDC_SUPERBILL_RESOURCE_LIST     2222
#define IDC_SUPERBILL_BY_PICKLIST       2223
#define IDC_SUPERBILL_PICK_LIST         2224
#define IDC_SUPERBILL_BROWSE            2225
#define IDC_SUPERBILL_GLOBAL            2226
#define IDC_GLOBAL_TEMPLATE_PATH        2227
#define IDC_GLOBAL_TEMPLATE_BROWSE      2228
#define IDC_SUPERBILL_ADD_TYPE          2229
#define IDC_SUPERBILL_MODIFY_TYPE       2230
#define IDC_SUPERBILL_REMOVE_TYPE       2231
#define IDC_SUPERBILL_ADD_RESOURCE      2232
#define IDC_SUPERBILL_MODIFY_RESOURCE   2233
#define IDC_SUPERBILL_REMOVE_RESOURCE   2234
#define IDC_SUPERBILL_ADD_PICKLIST      2235
#define IDC_SUPERBILL_REMOVE_PICKLIST   2237
#define IDC_SUPERBILL_HEADER_TEXT       2238
#define IDC_SUPERBILL_ADD_LIST          2239
#define IDC_ADD_SUPERBILL_DESCRIPTION_TEXT 2240
#define IDC_SUPERBILL_GROUP_LIST        2241
#define IDC_SUPERBILL_GROUPNAME         2242
#define IDC_SUPERBILL_TEMPLATE_LABEL    2243
#define IDC_SUPERBILL_GROUP_ADD_TEMPLATE 2244
#define IDC_SUPERBILL_GROUP_TEMPLATE_LIST 2245
#define IDC_SUPERBILL_GROUP_REMOVE_TEMPLATE 2246
#define IDC_SUPERBILL_GROUP_ADD_ITEM    2247
#define IDC_SUPERBILL_GROUP_REMOVE_ITEM 2248
#define IDC_MOVEUP                      2248
#define IDC_CONFIRMED                   2249
#define IDC_READY                       2250
#define IDC_RADIO_ADD                   2251
#define IDC_STATIC_APPT_INFO            2252
#define IDC_RADIO_REPLACE               2253
#define IDC_RADIO_NOCHANGE              2254
#define IDC_ROOM_MANAGER_REMEMBER_COL_WIDTHS 2255
#define IDC_CHECK_MOVEUP_SHOWINPUTDATE  2256
#define IDC_CHECK_MOVEUP_SHOW_APPT_START 2257
#define IDC_MOVEUPLIST_SORT             2258
#define IDC_MOVEUP_SORT_ASC             2259
#define IDC_MOVEUP_SORT_DESC            2260
#define IDC_BTN_PREVIEW_ROOM_MGR        2261
#define IDC_SUPERBILL_ADD_PROMPT_TEXT   2262
#define IDC_CHECK_INCLUDE_NONPT_APPTS   2263
#define IDC_STATIC_SCHEDCOUNTSETUP      2265
#define IDC_BTN_APPTCT_SELECTALL        2266
#define IDC_BTN_APPTCT_UNSELECTALL      2267
#define IDC_COPY_RESOURCE_LIST          2269
#define IDC_COPY_DATE_SEL_COMBO         2272
#define IDC_COPY_ALL_TEXT               2273
#define IDC_SINGLE_SELECT_FILTER_CHECK  2274
#define IDC_TEMPLATE_RULES_CAPTION      2275
#define IDC_TEMPLATE_LOCATION_LABEL     2276
#define IDC_TEMPLATE_LOCATION           2277
#define IDC_SELECT_TEMPLATE_LOCATION_LABEL 2278
#define IDC_SELECT_TEMPLATE_LOCATION_COMBO 2279
#define IDC_WAITING_AREA_COLUMNS        2280
#define IDC_ROOMS_COLUMNS               2281
#define IDC_BTN_CONFIG_COLUMNS          2281
#define IDC_CHECKOUT_COLUMNS            2282
#define NxColorRoomManager              2282
#define IDC_OVERRIDE_LOCATION_TEMPLATING 2283
#define IDC_FFA_PROGRESS_BAR            2284
#define IDC_FFA_PROGRESS_TEXT           2285
#define IDC_FFA_RESULTS_LIST            2286
#define IDC_PATIENT_COMBO_2             2287
#define IDC_NXBTN_CREATE_RECALL_SCHED   2288
#define IDC_BTN_RECALL                  2289
#define IDC_BTN_RESCHEDULING_QUEUE      2290
#define IDC_RES_INS_CAT                 2291
#define IDC_RES_PRI_LABEL               2292
#define IDC_RES_INS_ORDER_LIST          2293
#define IDC_RES_SEC_LABEL               2294
#define IDC_RES_INS_LIST                2294
#define IDC_RES_INS_MOVE_UP             2295
#define IDC_RES_INS_MOVE_DOWN           2296
#define IDC_NOTES_BOX_LABEL             2296
#define IDC_SAVE_VIEW_MEDICATION_HISTORY 2297
#define IDC_TEMPLATE_EDITOR_BACKGROUND  2298
#define IDC_RULE_DATE                   2298
#define IDC_TEMPLATE_COLLECTIOIN_NAME   2299
#define IDC_RULE_RESOURCE               2299
#define IDC_TEMPLATE_COLLECTION_APPLY_LIST 2300
#define IDC_RULE_LIST                   2300
#define IDC_TEMPLATE_COLLECTION_HIDE_OUTDATED 2301
#define IDC_SCHEDULE_MIX_RULES_NXC      2301
#define IDC_TEMPLATE_COLLECTION_CHOOSE_COLOR 2302
#define IDC_FFA_INSURED_PARTY_STATIC    2302
#define IDC_TEMPLATE_COLLECTION_NEW_APPLY 2303
#define IDC_NAME_COLOR_ENTRY_NAME       2303
#define IDC_FFA_INSURED_PARTY_COMBO     2303
#define IDC_TEMPLATE_COLLECTION_EDIT_APPLY 2304
#define IDC_NAME_COLOR_ENTRY_CHOOSE_COLOR 2304
#define IDC_TEMPLATE_COLLECTION_DELETE_APPLY 2305
#define IDC_TIME_RANGE_BOX              2305
#define IDC_WARNING_LABEL               2306
#define IDC_TEMPLATE_COLLECTION_UPDATE_APPLY 2306
#define IDC_APPEARANCE_BOX              2307
#define IDC_DATE_LEFT                   2307
#define IDC_PRECISION_TEMPLATE_CHECK    2308
#define IDC_DATE_LEFT2                  2308
#define IDC_DATE_RIGHT                  2308
#define IDC_START_TIME_LABEL            2309
#define IDC_END_TIME_LABEL              2310
#define IDC_RESOURCE_LABEL              2311
#define IDC_RESOURCE_DROPDOWN           2312
#define IDC_COLLECTIONS_USED_LABEL      2313
#define IDC_STATIC_COLLECTIONS_USED     2313
#define IDC_CHECK_RESCHEDULE            2313
#define IDC_HIDE_COLLECTION_LINE_ITEMS  2314
#define IDC_RESCHEDULE_APPOINTMENTS     2314
#define IDC_LIST_LOCATIONS              2316
#define IDC_LIST_APPOINTMENTS           2317
#define IDC_LIST_REASON                 2318
#define IDC_UNCHECKALL                  2318
#define IDC_LIST_TYPE                   2319
#define IDC_CHECKALL                    2319
#define IDC_LIST_PURPOSE                2320
#define IDC_LISTAPPOINTMENTS            2320
#define IDC_TOCANCELINSTRUCTIONS        2321
#define IDC_NXCOLOR_CANCEL_APPT         2323
#define IDC_ALL_RESOURCES               2324
#define IDC_SELECT_RESOURCES            2325
#define IDC_RESOURCES                   2326
#define IDC_TIME_START                  2329
#define IDC_TIME_END                    2330
#define IDC_RESCHEDULE_ALL              2331
#define IDC_CANCELLATION_REASON         2332
#define IDC_EDIT_CANCELLATION_REASONS   2334
#define IDC_CANCELLATION_TEMPLATE       2335
#define IDC_CHECK_REMEMBER_COL_RESCHED_LIST 2336
#define IDC_RESOURCE_LIST_STATIC        2337
#define IDC_BUTTON1                     2338
#define IDC_TOGGLE_DOCK                 2338
#define IDC_LOCATION_LIST_STATIC        2339
#define IDC_ACTIVE_RESOURCES_CHECK      2340
#define IDC_NO_ACTIVE_RESOURCES_CHECK   2341
#define IDC_APPOINTMENTS_SHOWN_STATIC   2342
#define IDC_RADIO_SHOW_APPTS_WITH_MULTIPLE_RESOURCES 2343
#define IDC_RADIO_SHOW_ALL_APPTS        2344
#define IDC_FFA_LOCATIONS_COMBO         2345
#define IDC_MULTI_LOCATION              2346
#define ID_UNSELECTED_RESOURCES_STATIC  2347
#define IDC_FILTER_RESOURCE_LEFT        2347
#define ID_ALL_NONE_RESOURCES_STATIC    2348
#define IDC_FILTER_RESOURCE_RIGHT       2348
#define IDC_FFA_HOURS_COMBO             2349
#define IDC_FILTER_LOCATION_LEFT        2349
#define IDC_FILTER_RESOURCE_LABEL       2350
#define ID_ALL_NONE_RESOURCES_STATIC2   2350
#define ID_ALL_ANY_OF_STATIC            2350
#define IDC_FILTER_RESOURCE_COMBO       2351
#define IDC_FFA_MINS_COMBO              2352
#define IDC_FILTER_LOCATION_LABEL       2352
#define IDC_LOCATION_STATIC             2353
#define IDC_FILTER_LOCATIONS_COMBO      2353
#define IDC_FILTER_LOCATION_RIGHT       2354
#define IDD_TEMPLATE_SELECT             11371
#define IDD_RES_LINK_ACTION_DLG         30101
#define IDD_APT_BOOK_ALARM_DLG          30102
#define IDD_APT_BOOK_ALARM_DETAIL_DLG   30103
#define IDD_APT_BOOK_ALARM_LIST_DLG     30104
#define IDD_ROOM_MANAGER_DLG            30105
#define IDD_ROOM_SETUP_DLG              30106
#define IDD_ROOM_STATUS_SETUP_DLG       30107
#define IDD_ROOM_SELECTOR_DLG           30110
#define IDD_TEMPLATE_ITEM_ENTRY_GRAPHICAL 30112
#define IDD_TEMPLATE_EXCEPTION_DLG      30116
#define IDD_TEMPLATE_ITEM_CHANGE_TIME_PROMPT 30118
#define IDD_TEMPLATE_INTERFACE_OPTIONS  30120
#define IDD_WAITING_LIST_ENTRY_DLG      30121
#define IDD_WAITING_LIST_RESOURCE_DLG   30124
#define IDD_WAITING_LIST_MATCH_DLG      30125
#define IDD_CONFIGURE_SUPERBILL_TEMPLATES_DLG 30127
#define IDD_CONFIGURE_SUPERBILL_ADD_FILE 30129
#define IDD_CONFIGURE_SUPERBILL_MODIFY_GROUPS 30131
#define IDD_RESOLVE_CONS_SURG_BOOKING   30133
#define IDD_SCHED_COUNT_SETUP           30135
#define IDD_TEMPLATE_COPYALLDLG         30136
#define IDD_ROOM_MANAGER_CONFIG_COL_DLG 30139
#define IDD_APPT_CHOOSE_MORE_INSURED_DLG 30141
#define IDD_TEMPLATE_COLLECTION_ENTRY   30143
#define IDD_NAME_AND_COLOR_ENTRY        30144
#define IDD_VIEW_SCHEDULER_MIX_RULES_DLG 30145
#define IDD_SCHEDULER_MIX_WARNING_DLG   30146
#define IDD_RESCHEDULING_QUEUE          30147
#define IDD_RESCHEDULE_APPOINTMENTS_DLG 30150
#define IDS_APPOINTMENT_NOT_FOUND       31480
#define ID_RES_EDIT                     32791
#define ID_RES_CUT                      32792
#define ID_RES_COPY                     32793
#define ID_RES_PASTE                    32794
#define ID_RES_DELETE                   32797
#define ID_SEND_TO_HCFA                 32900
#define IDC_SEND_TO_EBILL               32902
#define IDC_OPEN_HCFA                   32904
#define IDC_REMOVE_HCFA                 32905
#define ID_VALIDATE_CLAIM               32906
#define ID_GOTOPATIENT                  32976
#define ID_PRINTSUPERBILL               32989
#define IDC_APT_ADD                     33336
#define IDC_APT_REMOVE                  33337
#define IDC_APT_ADD_ALL                 33338
#define IDC_ATP_REMOVE_ALL              33339
#define ID_RES_EVENT                    40001
#define ID_FORWARD_ONE_DAY              40005
#define ID_FORWARD_ONE_WEEK             40006
#define ID_FORWARD_ONE_MONTH            40007
#define ID_FORWARD_ONE_YEAR             40008
#define ID_BACK_ONE_DAY                 40009
#define ID_BACK_ONE_WEEK                40010
#define ID_BACK_ONE_MONTH               40011
#define ID_BACK_ONE_YEAR                40012
#define ID_BACK_DAYS_2                  40013
#define ID_BACK_DAYS_3                  40014
#define ID_BACK_DAYS_4                  40015
#define ID_BACK_DAYS_5                  40016
#define ID_BACK_DAYS_6                  40017
#define ID_BACK_WEEKS_2                 40018
#define ID_BACK_WEEKS_3                 40019
#define ID_BACK_WEEKS_4                 40020
#define ID_BACK_WEEKS_5                 40021
#define ID_BACK_WEEKS_6                 40022
#define ID_BACK_WEEKS_7                 40023
#define ID_BACK_MONTHS_2                40024
#define ID_BACK_MONTHS_3                40025
#define ID_BACK_MONTHS_4                40026
#define ID_BACK_MONTHS_5                40027
#define ID_BACK_MONTHS_6                40028
#define ID_BACK_YEARS_2                 40029
#define ID_BACK_YEARS_3                 40030
#define ID_BACK_YEARS_4                 40031
#define ID_BACK_YEARS_5                 40032
#define ID_FORWARD_DAYS_2               40033
#define ID_FORWARD_DAYS_3               40034
#define ID_FORWARD_DAYS_4               40035
#define ID_FORWARD_DAYS_5               40036
#define ID_FORWARD_DAYS_6               40037
#define ID_FORWARD_WEEKS_2              40038
#define ID_FORWARD_WEEKS_3              40039
#define ID_FORWARD_WEEKS_4              40040
#define ID_FORWARD_WEEKS_5              40041
#define ID_FORWARD_WEEKS_6              40042
#define ID_FORWARD_WEEKS_7              40043
#define ID_FORWARD_MONTHS_2             40044
#define ID_FORWARD_MONTHS_3             40045
#define ID_FORWARD_MONTHS_4             40046
#define ID_FORWARD_MONTHS_5             40047
#define ID_FORWARD_MONTHS_6             40048
#define ID_FORWARD_YEARS_2              40049
#define ID_FORWARD_YEARS_3              40050
#define ID_FORWARD_YEARS_4              40051
#define ID_FORWARD_YEARS_5              40052
#define ID_BTN_APPOINTMENTLINKING       40053
#define IDC_BTN_APPOINTMENTLINKING      40054
#define IDC_SAVE_CREATE_INV_ALLOCATION  40055
#define IDC_SAVE_CREATE_INV_ORDER       40056
#define IDC_SAVE_CREATE_BILL            40057
#define ID_GOTO_INSURANCE               40059
#define ID_RESTORE_APPT                 40062
#define IDC_GO_TO_SCHEDULE              40063

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        30153
#define _APS_NEXT_COMMAND_VALUE         40064
#define _APS_NEXT_CONTROL_VALUE         2356
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
