(function(k){k.color={};k.color.make=function(d,a,b,g){var c={};c.r=d||0;c.g=a||0;c.b=b||0;c.a=null!=g?g:1;c.add=function(a,h){for(var d=0;d<a.length;++d)c[a.charAt(d)]+=h;return c.normalize()};c.scale=function(a,h){for(var d=0;d<a.length;++d)c[a.charAt(d)]*=h;return c.normalize()};c.toString=function(){return 1<=c.a?"rgb("+[c.r,c.g,c.b].join()+")":"rgba("+[c.r,c.g,c.b,c.a].join()+")"};c.normalize=function(){function a(c,d,b){return d<c?c:d>b?b:d}c.r=a(0,parseInt(c.r),255);c.g=a(0,parseInt(c.g),255);
c.b=a(0,parseInt(c.b),255);c.a=a(0,c.a,1);return c};c.clone=function(){return k.color.make(c.r,c.b,c.g,c.a)};return c.normalize()};k.color.extract=function(d,a){var b;do{b=d.css(a).toLowerCase();if(""!=b&&"transparent"!=b)break;d=d.parent()}while(!k.nodeName(d.get(0),"body"));"rgba(0, 0, 0, 0)"==b&&(b="transparent");return k.color.parse(b)};k.color.parse=function(r){var a,b=k.color.make;if(a=/rgb\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*\)/.exec(r))return b(parseInt(a[1],10),parseInt(a[2],
10),parseInt(a[3],10));if(a=/rgba\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]+(?:\.[0-9]+)?)\s*\)/.exec(r))return b(parseInt(a[1],10),parseInt(a[2],10),parseInt(a[3],10),parseFloat(a[4]));if(a=/rgb\(\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*\)/.exec(r))return b(2.55*parseFloat(a[1]),2.55*parseFloat(a[2]),2.55*parseFloat(a[3]));if(a=/rgba\(\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\s*\)/.exec(r))return b(2.55*
parseFloat(a[1]),2.55*parseFloat(a[2]),2.55*parseFloat(a[3]),parseFloat(a[4]));if(a=/#([a-fA-F0-9]{2})([a-fA-F0-9]{2})([a-fA-F0-9]{2})/.exec(r))return b(parseInt(a[1],16),parseInt(a[2],16),parseInt(a[3],16));if(a=/#([a-fA-F0-9])([a-fA-F0-9])([a-fA-F0-9])/.exec(r))return b(parseInt(a[1]+a[1],16),parseInt(a[2]+a[2],16),parseInt(a[3]+a[3],16));r=k.trim(r).toLowerCase();if("transparent"==r)return b(255,255,255,0);a=d[r]||[0,0,0];return b(a[0],a[1],a[2])};var d={aqua:[0,255,255],azure:[240,255,255],beige:[245,
245,220],black:[0,0,0],blue:[0,0,255],brown:[165,42,42],cyan:[0,255,255],darkblue:[0,0,139],darkcyan:[0,139,139],darkgrey:[169,169,169],darkgreen:[0,100,0],darkkhaki:[189,183,107],darkmagenta:[139,0,139],darkolivegreen:[85,107,47],darkorange:[255,140,0],darkorchid:[153,50,204],darkred:[139,0,0],darksalmon:[233,150,122],darkviolet:[148,0,211],fuchsia:[255,0,255],gold:[255,215,0],green:[0,128,0],indigo:[75,0,130],khaki:[240,230,140],lightblue:[173,216,230],lightcyan:[224,255,255],lightgreen:[144,238,
144],lightgrey:[211,211,211],lightpink:[255,182,193],lightyellow:[255,255,224],lime:[0,255,0],magenta:[255,0,255],maroon:[128,0,0],navy:[0,0,128],olive:[128,128,0],orange:[255,165,0],pink:[255,192,203],purple:[128,0,128],violet:[128,0,128],red:[255,0,0],silver:[192,192,192],white:[255,255,255],yellow:[255,255,0]}})(jQuery);
(function(k){function d(a,d,g,c){function w(n,p){for(var p=[I].concat(p),j=0;j<n.length;++j)n[j].apply(this,p)}function h(n){for(var p=[],j=0;j<n.length;++j){var e=k.extend(!0,{},l.series);null!=n[j].data?(e.data=n[j].data,delete n[j].data,k.extend(!0,e,n[j]),n[j].data=e.data):e.data=n[j];p.push(e)}G=p;p=G.length;j=[];e=[];for(n=0;n<G.length;++n){var H=G[n].color;null!=H&&(--p,"number"==typeof H?e.push(H):j.push(k.color.parse(G[n].color)))}for(n=0;n<e.length;++n)p=Math.max(p,e[n]+1);j=[];for(n=e=
0;j.length<p;)H=l.colors.length==n?k.color.make(100,100,100):k.color.parse(l.colors[n]),H.scale("rgb",1+0.2*(1==e%2?-1:1)*Math.ceil(e/2)),j.push(H),++n,n>=l.colors.length&&(n=0,++e);for(n=p=0;n<G.length;++n){e=G[n];null==e.color?(e.color=j[p].toString(),++p):"number"==typeof e.color&&(e.color=j[e.color].toString());if(null==e.lines.show){var c,H=!0;for(c in e)if(e[c]&&e[c].show){H=!1;break}H&&(e.lines.show=!0)}e.xaxis=s(O,q(e,"x"));e.yaxis=s(R,q(e,"y"))}c=function(n,e,j){e<n.datamin&&e!=-d&&(n.datamin=
e);j>n.datamax&&j!=d&&(n.datamax=j)};var a=Number.POSITIVE_INFINITY,h=Number.NEGATIVE_INFINITY,d=Number.MAX_VALUE,L,f,b,g,r;k.each(z(),function(n,e){e.datamin=a;e.datamax=h;e.used=!1});for(n=0;n<G.length;++n)p=G[n],p.datapoints={points:[]},w(Q.processRawData,[p,p.data,p.datapoints]);for(n=0;n<G.length;++n){var p=G[n],u=p.data,P=p.datapoints.format;if(!P){P=[];P.push({x:!0,number:!0,required:!0});P.push({y:!0,number:!0,required:!0});if(p.bars.show||p.lines.show&&p.lines.fill)P.push({y:!0,number:!0,
required:!1,defaultValue:0}),p.bars.horizontal&&(delete P[P.length-1].y,P[P.length-1].x=!0);p.datapoints.format=P}if(null==p.datapoints.pointsize){p.datapoints.pointsize=P.length;f=p.datapoints.pointsize;H=p.datapoints.points;insertSteps=p.lines.show&&p.lines.steps;p.xaxis.used=p.yaxis.used=!0;for(j=L=0;j<u.length;++j,L+=f){r=u[j];var t=null==r;if(!t)for(e=0;e<f;++e){b=r[e];if(g=P[e])g.number&&null!=b&&(b=+b,isNaN(b)?b=null:Infinity==b?b=d:-Infinity==b&&(b=-d)),null==b&&(g.required&&(t=!0),null!=
g.defaultValue&&(b=g.defaultValue));H[L+e]=b}if(t)for(e=0;e<f;++e)b=H[L+e],null!=b&&(g=P[e],g.x&&c(p.xaxis,b,b),g.y&&c(p.yaxis,b,b)),H[L+e]=null;else if(insertSteps&&0<L&&null!=H[L-f]&&H[L-f]!=H[L]&&H[L-f+1]!=H[L+1]){for(e=0;e<f;++e)H[L+f+e]=H[L+e];H[L+1]=H[L-f+1];L+=f}}}}for(n=0;n<G.length;++n)p=G[n],w(Q.processDatapoints,[p,p.datapoints]);for(n=0;n<G.length;++n){p=G[n];H=p.datapoints.points;f=p.datapoints.pointsize;P=p.datapoints.format;r=L=a;t=u=h;for(j=0;j<H.length;j+=f)if(null!=H[j])for(e=0;e<
f;++e)if(b=H[j+e],(g=P[e])&&!(b==d||b==-d))g.x&&(b<L&&(L=b),b>u&&(u=b)),g.y&&(b<r&&(r=b),b>t&&(t=b));if(p.bars.show){switch(p.bars.align){case "left":j=0;break;case "right":j=-p.bars.barWidth;break;case "center":j=-p.bars.barWidth/2;break;default:throw Error("Invalid bar alignment: "+p.bars.align);}p.bars.horizontal?(r+=j,t+=j+p.bars.barWidth):(L+=j,u+=j+p.bars.barWidth)}c(p.xaxis,L,u);c(p.yaxis,r,t)}k.each(z(),function(n,e){e.datamin==a&&(e.datamin=null);e.datamax==h&&(e.datamax=null)})}function q(n,
p){var j=n[p+"axis"];"object"==typeof j&&(j=j.n);"number"!=typeof j&&(j=1);return j}function z(){return k.grep(O.concat(R),function(n){return n})}function f(n){var p={},j,e;for(j=0;j<O.length;++j)(e=O[j])&&e.used&&(p["x"+e.n]=e.c2p(n.left));for(j=0;j<R.length;++j)(e=R[j])&&e.used&&(p["y"+e.n]=e.c2p(n.top));void 0!==p.x1&&(p.x=p.x1);void 0!==p.y1&&(p.y=p.y1);return p}function s(n,p){n[p-1]||(n[p-1]={n:p,direction:n==O?"x":"y",options:k.extend(!0,{},n==O?l.xaxis:l.yaxis)});return n[p-1]}function t(n,
p){var j=document.createElement("canvas");j.className=p;j.width=S;j.height=T;n||k(j).css({position:"absolute",left:0,top:0});k(j).appendTo(a);j.getContext||(j=window.G_vmlCanvasManager.initElement(j));j.getContext("2d").save();return j}function u(){S=a.width();T=a.height();if(0>S||0>T)throw Error("Invalid dimensions for plot, width = "+S+", height = "+T);}function E(n){n.width!=S&&(n.width=S);n.height!=T&&(n.height=T);n=n.getContext("2d");n.restore();n.save()}function F(n){var p=n.labelWidth,j=n.labelHeight,
e=n.options.position,c=n.options.tickLength,a=l.grid.axisMargin,b=l.grid.labelMargin,d="x"==n.direction?O:R,f=k.grep(d,function(n){return n&&n.options.position==e&&n.reserveSpace});k.inArray(n,f)==f.length-1&&(a=0);if(null==c)var c=k.grep(d,function(n){return n&&n.reserveSpace}),h=0==k.inArray(n,c),c=h?"full":5;isNaN(+c)||(b+=+c);"x"==n.direction?(j+=b,"bottom"==e?(C.bottom+=j+a,n.box={top:T-C.bottom,height:j}):(n.box={top:C.top+a,height:j},C.top+=j+a)):(p+=b,"left"==e?(n.box={left:C.left+a,width:p},
C.left+=p+a):(C.right+=p+a,n.box={left:S-C.right,width:p}));n.position=e;n.tickLength=c;n.box.padding=b;n.innermost=h}function B(){var n,p=z(),j=l.grid.show;for(n in C){var e=l.grid.margin||0;C[n]="number"==typeof e?e:e[n]||0}w(Q.processOffset,[C]);for(n in C)C[n]+=j?l.grid.borderWidth:0;k.each(p,function(n,e){e.show=e.options.show;null==e.show&&(e.show=e.used);e.reserveSpace=e.show||e.options.reserveSpace;var j=e.options,p=+(null!=j.min?j.min:e.datamin),c=+(null!=j.max?j.max:e.datamax),a=c-p;if(0==
a){if(a=0==c?1:0.01,null==j.min&&(p-=a),null==j.max||null!=j.min)c+=a}else{var H=j.autoscaleMargin;null!=H&&(null==j.min&&(p-=a*H,0>p&&(null!=e.datamin&&0<=e.datamin)&&(p=0)),null==j.max&&(c+=a*H,0<c&&(null!=e.datamax&&0>=e.datamax)&&(c=0)))}e.min=p;e.max=c});if(j){var c={style:a.css("font-style"),size:Math.round(0.8*(+a.css("font-size").replace("px","")||13)),variant:a.css("font-variant"),weight:a.css("font-weight"),family:a.css("font-family")},j=k.grep(p,function(n){return n.reserveSpace});k.each(j,
function(n,e){var j=e.options,p;p="number"==typeof j.ticks&&0<j.ticks?j.ticks:0.3*Math.sqrt("x"==e.direction?S:T);p=(e.max-e.min)/p;var a,b,d,f;if("time"==j.mode){var h={second:1E3,minute:6E4,hour:36E5,day:864E5,month:2592E6,year:525949.2*6E4};f=[[1,"second"],[2,"second"],[5,"second"],[10,"second"],[30,"second"],[1,"minute"],[2,"minute"],[5,"minute"],[10,"minute"],[30,"minute"],[1,"hour"],[2,"hour"],[4,"hour"],[8,"hour"],[12,"hour"],[1,"day"],[2,"day"],[3,"day"],[0.25,"month"],[0.5,"month"],[1,"month"],
[2,"month"],[3,"month"],[6,"month"],[1,"year"]];a=0;null!=j.minTickSize&&(a="number"==typeof j.tickSize?j.tickSize:j.minTickSize[0]*h[j.minTickSize[1]]);for(b=0;b<f.length-1&&!(p<(f[b][0]*h[f[b][1]]+f[b+1][0]*h[f[b+1][1]])/2&&f[b][0]*h[f[b][1]]>=a);++b);a=f[b][0];d=f[b][1];"year"==d&&(b=Math.pow(10,Math.floor(Math.log(p/h.year)/Math.LN10)),f=p/h.year/b,a=(1.5>f?1:3>f?2:7.5>f?5:10)*b);e.tickSize=j.tickSize||[a,d];b=function(n){var e=[],j=n.tickSize[0],p=n.tickSize[1],a=new Date(n.min),b=j*h[p];"second"==
p&&a.setUTCSeconds(r(a.getUTCSeconds(),j));"minute"==p&&a.setUTCMinutes(r(a.getUTCMinutes(),j));"hour"==p&&a.setUTCHours(r(a.getUTCHours(),j));"month"==p&&a.setUTCMonth(r(a.getUTCMonth(),j));"year"==p&&a.setUTCFullYear(r(a.getUTCFullYear(),j));a.setUTCMilliseconds(0);b>=h.minute&&a.setUTCSeconds(0);b>=h.hour&&a.setUTCMinutes(0);b>=h.day&&a.setUTCHours(0);b>=4*h.day&&a.setUTCDate(1);b>=h.year&&a.setUTCMonth(0);var c=0,f=Number.NaN,d;do if(d=f,f=a.getTime(),e.push(f),"month"==p)if(1>j){a.setUTCDate(1);
var H=a.getTime();a.setUTCMonth(a.getUTCMonth()+1);var g=a.getTime();a.setTime(f+c*h.hour+(g-H)*j);c=a.getUTCHours();a.setUTCHours(0)}else a.setUTCMonth(a.getUTCMonth()+j);else"year"==p?a.setUTCFullYear(a.getUTCFullYear()+j):a.setTime(f+b);while(f<n.max&&f!=d);return e};a=function(n,e){var a=new Date(n);if(null!=j.timeformat)return k.plot.formatDate(a,j.timeformat,j.monthNames);var p=e.tickSize[0]*h[e.tickSize[1]],b=e.max-e.min,c=j.twelveHourClock?" %p":"";fmt=p<h.minute?"%h:%M:%S"+c:p<h.day?b<2*
h.day?"%h:%M"+c:"%b %d %h:%M"+c:p<h.month?"%b %d":p<h.year?b<h.year?"%b":"%b %y":"%y";return k.plot.formatDate(a,fmt,j.monthNames)}}else{d=j.tickDecimals;var g=-Math.floor(Math.log(p)/Math.LN10);null!=d&&g>d&&(g=d);b=Math.pow(10,-g);f=p/b;if(1.5>f)a=1;else if(3>f){if(a=2,2.25<f&&(null==d||g+1<=d))a=2.5,++g}else a=7.5>f?5:10;a*=b;null!=j.minTickSize&&a<j.minTickSize&&(a=j.minTickSize);e.tickDecimals=Math.max(0,null!=d?d:g);e.tickSize=j.tickSize||a;b=function(n){var e=[],j=r(n.min,n.tickSize),a=0,p=
Number.NaN,b;do b=p,p=j+a*n.tickSize,e.push(p),++a;while(p<n.max&&p!=b);return e};a=function(n,e){return n.toFixed(e.tickDecimals)}}if(null!=j.alignTicksWithAxis){var q=("x"==e.direction?O:R)[j.alignTicksWithAxis-1];q&&(q.used&&q!=e)&&(b=b(e),0<b.length&&(null==j.min&&(e.min=Math.min(e.min,b[0])),null==j.max&&1<b.length&&(e.max=Math.max(e.max,b[b.length-1]))),b=function(n){var e=[],j,p;for(p=0;p<q.ticks.length;++p)j=(q.ticks[p].v-q.min)/(q.max-q.min),j=n.min+j*(n.max-n.min),e.push(j);return e},!e.mode&&
null==j.tickDecimals&&(p=Math.max(0,-Math.floor(Math.log(p)/Math.LN10)+1),f=b(e),1<f.length&&/\..*0$/.test((f[1]-f[0]).toFixed(p))||(e.tickDecimals=p)))}e.tickGenerator=b;e.tickFormatter=k.isFunction(j.tickFormatter)?function(n,e){return""+j.tickFormatter(n,e)}:a;a=e.options.ticks;p=[];null==a||"number"==typeof a&&0<a?p=e.tickGenerator(e):a&&(p=k.isFunction(a)?a(e):a);e.ticks=[];for(a=0;a<p.length;++a)f=null,d=p[a],"object"==typeof d?(b=+d[0],1<d.length&&(f=d[1])):b=+d,null==f&&(f=e.tickFormatter(b,
e)),isNaN(b)||e.ticks.push({v:b,label:f});p=e.ticks;e.options.autoscaleMargin&&0<p.length&&(null==e.options.min&&(e.min=Math.min(e.min,p[0].v)),null==e.options.max&&1<p.length&&(e.max=Math.max(e.max,p[p.length-1].v)));e.font=k.extend({},c,e.options.font);p=e.options;a=e.ticks||[];b=p.labelWidth||0;f=p.labelHeight||0;d=e.font;v.save();v.font=d.style+" "+d.variant+" "+d.weight+" "+d.size+"px '"+d.family+"'";for(g=0;g<a.length;++g){var w=a[g];w.lines=[];w.width=w.height=0;if(w.label){for(var s=w.label.replace(/<br ?\/?>|\r\n|\r/g,
"\n").split("\n"),l=0;l<s.length;++l){var u={text:s[l]},t=v.measureText(u.text);u.width=t.width;u.height=null!=t.height?t.height:d.size;u.height+=Math.round(0.15*d.size);w.width=Math.max(u.width,w.width);w.height+=u.height;w.lines.push(u)}null==p.labelWidth&&(b=Math.max(b,w.width));null==p.labelHeight&&(f=Math.max(f,w.height))}}v.restore();e.labelWidth=Math.ceil(b);e.labelHeight=Math.ceil(f)});for(n=j.length-1;0<=n;--n)F(j[n]);n=l.grid.minBorderMargin;var b={x:0,y:0};if(null==n)for(e=n=0;e<G.length;++e)n=
Math.max(n,2*(G[e].points.radius+G[e].points.lineWidth/2));b.x=b.y=Math.ceil(n);k.each(z(),function(n,e){var j=e.direction;e.reserveSpace&&(b[j]=Math.ceil(Math.max(b[j],("x"==j?e.labelWidth:e.labelHeight)/2)))});C.left=Math.max(b.x,C.left);C.right=Math.max(b.x,C.right);C.top=Math.max(b.y,C.top);C.bottom=Math.max(b.y,C.bottom);k.each(j,function(n,e){"x"==e.direction?(e.box.left=C.left-e.labelWidth/2,e.box.width=S-C.left-C.right+e.labelWidth):(e.box.top=C.top-e.labelHeight/2,e.box.height=T-C.bottom-
C.top+e.labelHeight)})}Z=S-C.left-C.right;X=T-C.bottom-C.top;k.each(p,function(e,n){var j=function(n){return n},p,a,b=n.options.transform||j,c=n.options.inverseTransform;"x"==n.direction?(p=n.scale=Z/Math.abs(b(n.max)-b(n.min)),a=Math.min(b(n.max),b(n.min))):(p=n.scale=X/Math.abs(b(n.max)-b(n.min)),p=-p,a=Math.max(b(n.max),b(n.min)));n.p2c=b==j?function(n){return(n-a)*p}:function(n){return(b(n)-a)*p};n.c2p=c?function(n){return c(a+n/p)}:function(n){return a+n/p}});a.find(".legend").remove();if(l.legend.show){p=
[];j=!1;n=l.legend.labelFormatter;for(var d,f=0;f<G.length;++f)if(e=G[f],d=e.label)0==f%l.legend.noColumns&&(j&&p.push("</tr>"),p.push("<tr>"),j=!0),n&&(d=n(d,e)),p.push('<td class="legendColorBox"><div style="border:1px solid '+l.legend.labelBoxBorderColor+';padding:1px"><div style="width:4px;height:0;border:5px solid '+e.color+';overflow:hidden"></div></div></td><td class="legendLabel">'+d+"</td>");j&&p.push("</tr>");0!=p.length&&(j='<table style="font-size:smaller;color:'+l.grid.color+'">'+p.join("")+
"</table>",null!=l.legend.container?k(l.legend.container).html(j):(p="",n=l.legend.position,e=l.legend.margin,null==e[0]&&(e=[e,e]),"n"==n.charAt(0)?p+="top:"+(e[1]+C.top)+"px;":"s"==n.charAt(0)&&(p+="bottom:"+(e[1]+C.bottom)+"px;"),"e"==n.charAt(1)?p+="right:"+(e[0]+C.right)+"px;":"w"==n.charAt(1)&&(p+="left:"+(e[0]+C.left)+"px;"),j=k('<div class="legend">'+j.replace('style="','style="position:absolute;'+p+";")+"</div>").appendTo(a),0!=l.legend.backgroundOpacity&&(n=l.legend.backgroundColor,null==
n&&(n=(n=l.grid.backgroundColor)&&"string"==typeof n?k.color.parse(n):k.color.extract(j,"background-color"),n.a=1,n=n.toString()),e=j.children(),k('<div style="position:absolute;width:'+e.width()+"px;height:"+e.height()+"px;"+p+"background-color:"+n+';"> </div>').prependTo(j).css("opacity",l.legend.backgroundOpacity))))}}function D(){v.clearRect(0,0,S,T);w(Q.drawBackground,[v]);var n=l.grid;n.show&&n.backgroundColor&&(v.save(),v.translate(C.left,C.top),v.fillStyle=ia(l.grid.backgroundColor,X,0,"rgba(255, 255, 255, 0)"),
v.fillRect(0,0,Z,X),v.restore());n.show&&!n.aboveData&&(K(),J());for(var p=0;p<G.length;++p){w(Q.drawSeries,[v,G[p]]);var j=G[p];j.lines.show&&ca(j);j.bars.show&&qa(j);j.points.show&&U(j)}w(Q.draw,[v]);n.show&&n.aboveData&&(K(),J())}function A(n,p){for(var j,e,a,b,c=z(),f=0;f<c.length;++f)if(j=c[f],j.direction==p&&(b=p+j.n+"axis",!n[b]&&1==j.n&&(b=p+"axis"),n[b])){e=n[b].from;a=n[b].to;break}n[b]||(j="x"==p?O[0]:R[0],e=n[p+"1"],a=n[p+"2"]);null!=e&&(null!=a&&e>a)&&(b=e,e=a,a=b);return{from:e,to:a,
axis:j}}function K(){var n;v.save();v.translate(C.left,C.top);var p=l.grid.markings;if(p){if(k.isFunction(p)){var j=I.getAxes();j.xmin=j.xaxis.min;j.xmax=j.xaxis.max;j.ymin=j.yaxis.min;j.ymax=j.yaxis.max;p=p(j)}for(n=0;n<p.length;++n){var j=p[n],e=A(j,"x"),a=A(j,"y");null==e.from&&(e.from=e.axis.min);null==e.to&&(e.to=e.axis.max);null==a.from&&(a.from=a.axis.min);null==a.to&&(a.to=a.axis.max);e.to<e.axis.min||(e.from>e.axis.max||a.to<a.axis.min||a.from>a.axis.max)||(e.from=Math.max(e.from,e.axis.min),
e.to=Math.min(e.to,e.axis.max),a.from=Math.max(a.from,a.axis.min),a.to=Math.min(a.to,a.axis.max),e.from==e.to&&a.from==a.to||(e.from=e.axis.p2c(e.from),e.to=e.axis.p2c(e.to),a.from=a.axis.p2c(a.from),a.to=a.axis.p2c(a.to),e.from==e.to||a.from==a.to?(v.beginPath(),v.strokeStyle=j.color||l.grid.markingsColor,v.lineWidth=j.lineWidth||l.grid.markingsLineWidth,v.moveTo(e.from,a.from),v.lineTo(e.to,a.to),v.stroke()):(v.fillStyle=j.color||l.grid.markingsColor,v.fillRect(e.from,a.to,e.to-e.from,a.from-a.to))))}}j=
z();p=l.grid.borderWidth;for(e=0;e<j.length;++e){a=j[e];n=a.box;var b=a.tickLength,c,f,d,h;if(a.show&&0!=a.ticks.length){v.strokeStyle=a.options.tickColor||k.color.parse(a.options.color).scale("a",0.22).toString();v.lineWidth=1;"x"==a.direction?(c=0,f="full"==b?"top"==a.position?0:X:n.top-C.top+("top"==a.position?n.height:0)):(f=0,c="full"==b?"left"==a.position?0:Z:n.left-C.left+("left"==a.position?n.width:0));a.innermost||(v.beginPath(),d=h=0,"x"==a.direction?d=Z:h=X,1==v.lineWidth&&(c=Math.floor(c)+
0.5,f=Math.floor(f)+0.5),v.moveTo(c,f),v.lineTo(c+d,f+h),v.stroke());v.beginPath();for(n=0;n<a.ticks.length;++n){var g=a.ticks[n].v;d=h=0;g<a.min||(g>a.max||"full"==b&&0<p&&(g==a.min||g==a.max))||("x"==a.direction?(c=a.p2c(g),h="full"==b?-X:b,"top"==a.position&&(h=-h)):(f=a.p2c(g),d="full"==b?-Z:b,"left"==a.position&&(d=-d)),1==v.lineWidth&&("x"==a.direction?c=Math.floor(c)+0.5:f=Math.floor(f)+0.5),v.moveTo(c,f),v.lineTo(c+d,f+h))}v.stroke()}}p&&(v.lineWidth=p,v.strokeStyle=l.grid.borderColor,v.strokeRect(-p/
2,-p/2,Z+p,X+p));v.restore()}function J(){v.save();k.each(z(),function(n,a){if(a.show&&0!=a.ticks.length){var j=a.box,e=a.font;v.fillStyle=a.options.color;v.font=e.style+" "+e.variant+" "+e.weight+" "+e.size+"px "+e.family;v.textAlign="start";v.textBaseline="middle";for(e=0;e<a.ticks.length;++e){var b=a.ticks[e];if(b.label&&!(b.v<a.min||b.v>a.max))for(var c,f,d=0,h,g=0;g<b.lines.length;++g)h=b.lines[g],"x"==a.direction?(c=C.left+a.p2c(b.v)-h.width/2,f="bottom"==a.position?j.top+j.padding:j.top+j.height-
j.padding-b.height):(f=C.top+a.p2c(b.v)-b.height/2,c="left"==a.position?j.left+j.width-j.padding-h.width:j.left+j.padding),f+=h.height/2+d,d+=h.height,k.browser.opera&&(c=Math.floor(c),f=Math.ceil(f-2)),v.fillText(h.text,c,f)}}});v.restore()}function ca(a){function b(a,n,e,c,j){var p=a.points,a=a.pointsize,f=null,d=null;v.beginPath();for(var h=a;h<p.length;h+=a){var g=p[h-a],l=p[h-a+1],s=p[h],u=p[h+1];if(!(null==g||null==s)){if(l<=u&&l<j.min){if(u<j.min)continue;g=(j.min-l)/(u-l)*(s-g)+g;l=j.min}else if(u<=
l&&u<j.min){if(l<j.min)continue;s=(j.min-l)/(u-l)*(s-g)+g;u=j.min}if(l>=u&&l>j.max){if(u>j.max)continue;g=(j.max-l)/(u-l)*(s-g)+g;l=j.max}else if(u>=l&&u>j.max){if(l>j.max)continue;s=(j.max-l)/(u-l)*(s-g)+g;u=j.max}if(g<=s&&g<c.min){if(s<c.min)continue;l=(c.min-g)/(s-g)*(u-l)+l;g=c.min}else if(s<=g&&s<c.min){if(g<c.min)continue;u=(c.min-g)/(s-g)*(u-l)+l;s=c.min}if(g>=s&&g>c.max){if(s>c.max)continue;l=(c.max-g)/(s-g)*(u-l)+l;g=c.max}else if(s>=g&&s>c.max){if(g>c.max)continue;u=(c.max-g)/(s-g)*(u-l)+
l;s=c.max}(g!=f||l!=d)&&v.moveTo(c.p2c(g)+n,j.p2c(l)+e);f=s;d=u;v.lineTo(c.p2c(s)+n,j.p2c(u)+e)}}v.stroke()}v.save();v.translate(C.left,C.top);v.lineJoin="round";var j=a.lines.lineWidth,e=a.shadowSize;if(0<j&&0<e){v.lineWidth=e;v.strokeStyle="rgba(0,0,0,0.1)";var c=Math.PI/18;b(a.datapoints,Math.sin(c)*(j/2+e/2),Math.cos(c)*(j/2+e/2),a.xaxis,a.yaxis);v.lineWidth=e/2;b(a.datapoints,Math.sin(c)*(j/2+e/4),Math.cos(c)*(j/2+e/4),a.xaxis,a.yaxis)}v.lineWidth=j;v.strokeStyle=a.color;if(e=ea(a.lines,a.color,
0,X)){v.fillStyle=e;for(var f=a.datapoints,e=a.xaxis,c=a.yaxis,d=f.points,f=f.pointsize,h=Math.min(Math.max(0,c.min),c.max),g=0,k=!1,q=1,r=0,w=0;!(0<f&&g>d.length+f);){var g=g+f,l=d[g-f],s=d[g-f+q],u=d[g],t=d[g+q];if(k){if(0<f&&null!=l&&null==u){w=g;f=-f;q=2;continue}if(0>f&&g==r+f){v.fill();k=!1;f=-f;q=1;g=r=w+f;continue}}if(!(null==l||null==u)){if(l<=u&&l<e.min){if(u<e.min)continue;s=(e.min-l)/(u-l)*(t-s)+s;l=e.min}else if(u<=l&&u<e.min){if(l<e.min)continue;t=(e.min-l)/(u-l)*(t-s)+s;u=e.min}if(l>=
u&&l>e.max){if(u>e.max)continue;s=(e.max-l)/(u-l)*(t-s)+s;l=e.max}else if(u>=l&&u>e.max){if(l>e.max)continue;t=(e.max-l)/(u-l)*(t-s)+s;u=e.max}k||(v.beginPath(),v.moveTo(e.p2c(l),c.p2c(h)),k=!0);if(s>=c.max&&t>=c.max)v.lineTo(e.p2c(l),c.p2c(c.max)),v.lineTo(e.p2c(u),c.p2c(c.max));else if(s<=c.min&&t<=c.min)v.lineTo(e.p2c(l),c.p2c(c.min)),v.lineTo(e.p2c(u),c.p2c(c.min));else{var z=l,B=u;s<=t&&s<c.min&&t>=c.min?(l=(c.min-s)/(t-s)*(u-l)+l,s=c.min):t<=s&&(t<c.min&&s>=c.min)&&(u=(c.min-s)/(t-s)*(u-l)+
l,t=c.min);s>=t&&s>c.max&&t<=c.max?(l=(c.max-s)/(t-s)*(u-l)+l,s=c.max):t>=s&&(t>c.max&&s<=c.max)&&(u=(c.max-s)/(t-s)*(u-l)+l,t=c.max);l!=z&&v.lineTo(e.p2c(z),c.p2c(s));v.lineTo(e.p2c(l),c.p2c(s));v.lineTo(e.p2c(u),c.p2c(t));u!=B&&(v.lineTo(e.p2c(u),c.p2c(t)),v.lineTo(e.p2c(B),c.p2c(t)))}}}}0<j&&b(a.datapoints,0,0,a.xaxis,a.yaxis);v.restore()}function U(a){function c(a,e,n,j,b,p,f,d){for(var h=a.points,a=a.pointsize,g=0;g<h.length;g+=a){var l=h[g],s=h[g+1];null==l||(l<p.min||l>p.max||s<f.min||s>f.max)||
(v.beginPath(),l=p.p2c(l),s=f.p2c(s)+j,"circle"==d?v.arc(l,s,e,0,b?Math.PI:2*Math.PI,!1):d(v,l,s,e,b),v.closePath(),n&&(v.fillStyle=n,v.fill()),v.stroke())}}v.save();v.translate(C.left,C.top);var j=a.points.lineWidth,e=a.shadowSize,b=a.points.radius,f=a.points.symbol;0<j&&0<e&&(e/=2,v.lineWidth=e,v.strokeStyle="rgba(0,0,0,0.1)",c(a.datapoints,b,null,e+e/2,!0,a.xaxis,a.yaxis,f),v.strokeStyle="rgba(0,0,0,0.2)",c(a.datapoints,b,null,e/2,!0,a.xaxis,a.yaxis,f));v.lineWidth=j;v.strokeStyle=a.color;c(a.datapoints,
b,ea(a.points,a.color),0,!1,a.xaxis,a.yaxis,f);v.restore()}function N(a,c,j,e,b,f,d,h,g,l,s,u){var k,q,r,w;s?(w=q=r=!0,k=!1,s=j,j=c+e,b=c+b,a<s&&(c=a,a=s,s=c,k=!0,q=!1)):(k=q=r=!0,w=!1,s=a+e,a+=b,b=j,j=c,j<b&&(c=j,j=b,b=c,w=!0,r=!1));if(!(a<h.min||s>h.max||j<g.min||b>g.max))if(s<h.min&&(s=h.min,k=!1),a>h.max&&(a=h.max,q=!1),b<g.min&&(b=g.min,w=!1),j>g.max&&(j=g.max,r=!1),s=h.p2c(s),b=g.p2c(b),a=h.p2c(a),j=g.p2c(j),d&&(l.beginPath(),l.moveTo(s,b),l.lineTo(s,j),l.lineTo(a,j),l.lineTo(a,b),l.fillStyle=
d(b,j),l.fill()),0<u&&(k||q||r||w))l.beginPath(),l.moveTo(s,b+f),k?l.lineTo(s,j+f):l.moveTo(s,j+f),r?l.lineTo(a,j+f):l.moveTo(a,j+f),q?l.lineTo(a,b+f):l.moveTo(a,b+f),w?l.lineTo(s,b+f):l.moveTo(s,b+f),l.stroke()}function qa(a){v.save();v.translate(C.left,C.top);v.lineWidth=a.bars.lineWidth;v.strokeStyle=a.color;var c;switch(a.bars.align){case "left":c=0;break;case "right":c=-a.bars.barWidth;break;case "center":c=-a.bars.barWidth/2;break;default:throw Error("Invalid bar alignment: "+a.bars.align);
}var b=a.datapoints,e=c;c+=a.bars.barWidth;for(var f=a.bars.fill?function(e,c){return ea(a.bars,a.color,e,c)}:null,d=a.xaxis,h=a.yaxis,g=b.points,b=b.pointsize,l=0;l<g.length;l+=b)null!=g[l]&&N(g[l],g[l+1],g[l+2],e,c,0,f,d,h,v,a.bars.horizontal,a.bars.lineWidth);v.restore()}function ea(a,c,b,e){var f=a.fill;if(!f)return null;if(a.fillColor)return ia(a.fillColor,b,e,c);a=k.color.parse(c);a.a="number"==typeof f?f:0.4;a.normalize();return a.toString()}function ja(a){l.grid.hoverable&&fa("plothover",
a,function(a){return!1!=a.hoverable})}function ka(a){l.grid.hoverable&&fa("plothover",a,function(){return!1})}function la(a){fa("plotclick",a,function(a){return!1!=a.clickable})}function fa(c,b,j){var e=V.offset(),d=b.pageX-e.left-C.left,h=b.pageY-e.top-C.top,g=f({left:d,top:h});g.pageX=b.pageX;g.pageY=b.pageY;var b=l.grid.mouseActiveRadius,s=b*b+1,u=null,k,q;for(k=G.length-1;0<=k;--k)if(j(G[k])){var r=G[k],w=r.xaxis,t=r.yaxis,z=r.datapoints.points,v=r.datapoints.pointsize,B=w.c2p(d),E=t.c2p(h),N=
b/w.scale,A=b/t.scale;w.options.inverseTransform&&(N=Number.MAX_VALUE);t.options.inverseTransform&&(A=Number.MAX_VALUE);if(r.lines.show||r.points.show)for(q=0;q<z.length;q+=v){var F=z[q],D=z[q+1];if(null!=F&&!(F-B>N||F-B<-N||D-E>A||D-E<-A))F=Math.abs(w.p2c(F)-d),D=Math.abs(t.p2c(D)-h),D=F*F+D*D,D<s&&(s=D,u=[k,q/v])}if(r.bars.show&&!u){w="left"==r.bars.align?0:-r.bars.barWidth/2;r=w+r.bars.barWidth;for(q=0;q<z.length;q+=v)if(F=z[q],D=z[q+1],t=z[q+2],null!=F&&(G[k].bars.horizontal?B<=Math.max(t,F)&&
B>=Math.min(t,F)&&E>=D+w&&E<=D+r:B>=F+w&&B<=F+r&&E>=Math.min(t,D)&&E<=Math.max(t,D)))u=[k,q/v]}}u?(k=u[0],q=u[1],v=G[k].datapoints.pointsize,j={datapoint:G[k].datapoints.points.slice(q*v,(q+1)*v),dataIndex:q,series:G[k],seriesIndex:k}):j=null;j&&(j.pageX=parseInt(j.series.xaxis.p2c(j.datapoint[0])+e.left+C.left),j.pageY=parseInt(j.series.yaxis.p2c(j.datapoint[1])+e.top+C.top));if(l.grid.autoHighlight){for(e=0;e<Y.length;++e)d=Y[e],d.auto==c&&(!j||!(d.series==j.series&&d.point[0]==j.datapoint[0]&&
d.point[1]==j.datapoint[1]))&&ma(d.series,d.point);j&&na(j.series,j.datapoint,c)}a.trigger(c,[g,j])}function da(){var a=l.interaction.redrawOverlayInterval;-1==a?oa():ba||(ba=setTimeout(oa,a))}function oa(){ba=null;M.save();M.clearRect(0,0,S,T);M.translate(C.left,C.top);var a,c;for(a=0;a<Y.length;++a)if(c=Y[a],c.series.bars.show)ra(c.series,c.point);else{var b=c.series,e=c.point;c=e[0];var e=e[1],f=b.xaxis,d=b.yaxis;if(!(c<f.min||c>f.max||e<d.min||e>d.max)){var h=b.points.radius+b.points.lineWidth/
2;M.lineWidth=h;M.strokeStyle=k.color.parse(b.color).scale("a",0.5).toString();h*=1.5;c=f.p2c(c);e=d.p2c(e);M.beginPath();"circle"==b.points.symbol?M.arc(c,e,h,0,2*Math.PI,!1):b.points.symbol(M,c,e,h,!1);M.closePath();M.stroke()}}M.restore();w(Q.drawOverlay,[M])}function na(a,c,b){"number"==typeof a&&(a=G[a]);if("number"==typeof c)var e=a.datapoints.pointsize,c=a.datapoints.points.slice(e*c,e*(c+1));e=pa(a,c);-1==e?(Y.push({series:a,point:c,auto:b}),da()):b||(Y[e].auto=!1)}function ma(a,c){null==
a&&null==c&&(Y=[],da());"number"==typeof a&&(a=G[a]);"number"==typeof c&&(c=a.data[c]);var b=pa(a,c);-1!=b&&(Y.splice(b,1),da())}function pa(a,c){for(var b=0;b<Y.length;++b){var e=Y[b];if(e.series==a&&e.point[0]==c[0]&&e.point[1]==c[1])return b}return-1}function ra(a,c){M.lineWidth=a.bars.lineWidth;M.strokeStyle=k.color.parse(a.color).scale("a",0.5).toString();var b=k.color.parse(a.color).scale("a",0.5).toString(),e="left"==a.bars.align?0:-a.bars.barWidth/2;N(c[0],c[1],c[2]||0,e,e+a.bars.barWidth,
0,function(){return b},a.xaxis,a.yaxis,M,a.bars.horizontal,a.bars.lineWidth)}function ia(a,c,b,e){if("string"==typeof a)return a;for(var c=v.createLinearGradient(0,b,0,c),b=0,f=a.colors.length;b<f;++b){var d=a.colors[b];if("string"!=typeof d){var h=k.color.parse(e);null!=d.brightness&&(h=h.scale("rgb",d.brightness));null!=d.opacity&&(h.a*=d.opacity);d=h.toString()}c.addColorStop(b/(f-1),d)}return c}var G=[],l={colors:["#edc240","#afd8f8","#cb4b4b","#4da74d","#9440ed"],legend:{show:!0,noColumns:1,
labelFormatter:null,labelBoxBorderColor:"#ccc",container:null,position:"ne",margin:5,backgroundColor:null,backgroundOpacity:0.85},xaxis:{show:null,position:"bottom",mode:null,font:null,color:null,tickColor:null,transform:null,inverseTransform:null,min:null,max:null,autoscaleMargin:null,ticks:null,tickFormatter:null,labelWidth:null,labelHeight:null,reserveSpace:null,tickLength:null,alignTicksWithAxis:null,tickDecimals:null,tickSize:null,minTickSize:null,monthNames:null,timeformat:null,twelveHourClock:!1},
yaxis:{autoscaleMargin:0.02,position:"left"},xaxes:[],yaxes:[],series:{points:{show:!1,radius:3,lineWidth:2,fill:!0,fillColor:"#ffffff",symbol:"circle"},lines:{lineWidth:2,fill:!1,fillColor:null,steps:!1},bars:{show:!1,lineWidth:2,barWidth:1,fill:!0,fillColor:null,align:"left",horizontal:!1},shadowSize:3},grid:{show:!0,aboveData:!1,color:"#545454",backgroundColor:null,borderColor:null,tickColor:null,margin:0,labelMargin:5,axisMargin:8,borderWidth:2,minBorderMargin:null,markings:null,markingsColor:"#f4f4f4",
markingsLineWidth:2,clickable:!1,hoverable:!1,autoHighlight:!0,mouseActiveRadius:10},interaction:{redrawOverlayInterval:1E3/60},hooks:{}},$=null,aa=null,V=null,v=null,M=null,O=[],R=[],C={left:0,right:0,top:0,bottom:0},S=0,T=0,Z=0,X=0,Q={processOptions:[],processRawData:[],processDatapoints:[],processOffset:[],drawBackground:[],drawSeries:[],draw:[],bindEvents:[],drawOverlay:[],shutdown:[]},I=this;I.setData=h;I.setupGrid=B;I.draw=D;I.getPlaceholder=function(){return a};I.getCanvas=function(){return $};
I.getPlotOffset=function(){return C};I.width=function(){return Z};I.height=function(){return X};I.offset=function(){var a=V.offset();a.left+=C.left;a.top+=C.top;return a};I.getData=function(){return G};I.getAxes=function(){var a={};k.each(O.concat(R),function(c,b){b&&(a[b.direction+(1!=b.n?b.n:"")+"axis"]=b)});return a};I.getXAxes=function(){return O};I.getYAxes=function(){return R};I.c2p=f;I.p2c=function(a){var c={},b,e,f;for(b=0;b<O.length;++b)if((e=O[b])&&e.used)if(f="x"+e.n,null==a[f]&&1==e.n&&
(f="x"),null!=a[f]){c.left=e.p2c(a[f]);break}for(b=0;b<R.length;++b)if((e=R[b])&&e.used)if(f="y"+e.n,null==a[f]&&1==e.n&&(f="y"),null!=a[f]){c.top=e.p2c(a[f]);break}return c};I.getOptions=function(){return l};I.highlight=na;I.unhighlight=ma;I.triggerRedrawOverlay=da;I.pointOffset=function(a){return{left:parseInt(O[q(a,"x")-1].p2c(+a.x)+C.left),top:parseInt(R[q(a,"y")-1].p2c(+a.y)+C.top)}};I.shutdown=function(){ba&&clearTimeout(ba);V.unbind("mousemove",ja);V.unbind("mouseleave",ka);V.unbind("click",
la);w(Q.shutdown,[V])};I.resize=function(){u();E($);E(aa)};I.hooks=Q;for(var ga=0;ga<c.length;++ga){var ha=c[ga];ha.init(I);ha.options&&k.extend(!0,l,ha.options)}k.extend(!0,l,g);null==l.xaxis.color&&(l.xaxis.color=l.grid.color);null==l.yaxis.color&&(l.yaxis.color=l.grid.color);null==l.xaxis.tickColor&&(l.xaxis.tickColor=l.grid.tickColor);null==l.yaxis.tickColor&&(l.yaxis.tickColor=l.grid.tickColor);null==l.grid.borderColor&&(l.grid.borderColor=l.grid.color);null==l.grid.tickColor&&(l.grid.tickColor=
k.color.parse(l.grid.color).scale("a",0.22).toString());for(g=0;g<Math.max(1,l.xaxes.length);++g)l.xaxes[g]=k.extend(!0,{},l.xaxis,l.xaxes[g]);for(g=0;g<Math.max(1,l.yaxes.length);++g)l.yaxes[g]=k.extend(!0,{},l.yaxis,l.yaxes[g]);l.xaxis.noTicks&&null==l.xaxis.ticks&&(l.xaxis.ticks=l.xaxis.noTicks);l.yaxis.noTicks&&null==l.yaxis.ticks&&(l.yaxis.ticks=l.yaxis.noTicks);l.x2axis&&(l.xaxes[1]=k.extend(!0,{},l.xaxis,l.x2axis),l.xaxes[1].position="top");l.y2axis&&(l.yaxes[1]=k.extend(!0,{},l.yaxis,l.y2axis),
l.yaxes[1].position="right");l.grid.coloredAreas&&(l.grid.markings=l.grid.coloredAreas);l.grid.coloredAreasColor&&(l.grid.markingsColor=l.grid.coloredAreasColor);l.lines&&k.extend(!0,l.series.lines,l.lines);l.points&&k.extend(!0,l.series.points,l.points);l.bars&&k.extend(!0,l.series.bars,l.bars);null!=l.shadowSize&&(l.series.shadowSize=l.shadowSize);for(g=0;g<l.xaxes.length;++g)s(O,g+1).options=l.xaxes[g];for(g=0;g<l.yaxes.length;++g)s(R,g+1).options=l.yaxes[g];for(var W in Q)l.hooks[W]&&l.hooks[W].length&&
(Q[W]=Q[W].concat(l.hooks[W]));w(Q.processOptions,[l]);W=a.children("canvas.flot-base");g=a.children("canvas.flot-overlay");0==W.length||0==g?(a.html(""),a.css({padding:0}),"static"==a.css("position")&&a.css("position","relative"),u(),$=t(!0,"flot-base"),aa=t(!1,"flot-overlay"),W=!1):($=W.get(0),aa=g.get(0),W=!0);v=$.getContext("2d");M=aa.getContext("2d");V=k(aa);W&&(a.data("plot").shutdown(),I.resize(),M.clearRect(0,0,S,T),V.unbind(),a.children().not([$,aa]).remove());a.data("plot",I);h(d);B();D();
l.grid.hoverable&&(V.mousemove(ja),V.mouseleave(ka));l.grid.clickable&&V.click(la);w(Q.bindEvents,[V]);var Y=[],ba=null}function r(a,b){return b*Math.floor(a/b)}k.plot=function(a,b,g){return new d(k(a),b,g,k.plot.plugins)};k.plot.version="0.7";k.plot.plugins=[];k.plot.formatDate=function(a,b,d){var c=function(a){a=""+a;return 1==a.length?"0"+a:a},k=[],h=!1,q=!1,r=a.getUTCHours(),f=12>r;null==d&&(d="Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "));-1!=b.search(/%p|%P/)&&(12<r?r-=12:0==
r&&(r=12));for(var s=0;s<b.length;++s){var t=b.charAt(s);if(h){switch(t){case "h":t=""+r;break;case "H":t=c(r);break;case "M":t=c(a.getUTCMinutes());break;case "S":t=c(a.getUTCSeconds());break;case "d":t=""+a.getUTCDate();break;case "m":t=""+(a.getUTCMonth()+1);break;case "y":t=""+a.getUTCFullYear();break;case "b":t=""+d[a.getUTCMonth()];break;case "p":t=f?"am":"pm";break;case "P":t=f?"AM":"PM";break;case "0":t="",q=!0}t&&q&&(t=c(t),q=!1);k.push(t);q||(h=!1)}else"%"==t?h=!0:k.push(t)}return k.join("")}})(jQuery);
(function(k){k.color={};k.color.make=function(d,a,b,g){var c={};c.r=d||0;c.g=a||0;c.b=b||0;c.a=null!=g?g:1;c.add=function(a,b){for(var d=0;d<a.length;++d)c[a.charAt(d)]+=b;return c.normalize()};c.scale=function(a,b){for(var d=0;d<a.length;++d)c[a.charAt(d)]*=b;return c.normalize()};c.toString=function(){return 1<=c.a?"rgb("+[c.r,c.g,c.b].join()+")":"rgba("+[c.r,c.g,c.b,c.a].join()+")"};c.normalize=function(){function a(c,b,d){return b<c?c:b>d?d:b}c.r=a(0,parseInt(c.r),255);c.g=a(0,parseInt(c.g),255);
c.b=a(0,parseInt(c.b),255);c.a=a(0,c.a,1);return c};c.clone=function(){return k.color.make(c.r,c.b,c.g,c.a)};return c.normalize()};k.color.extract=function(d,a){var b;do{b=d.css(a).toLowerCase();if(""!=b&&"transparent"!=b)break;d=d.parent()}while(!k.nodeName(d.get(0),"body"));"rgba(0, 0, 0, 0)"==b&&(b="transparent");return k.color.parse(b)};k.color.parse=function(r){var a,b=k.color.make;if(a=/rgb\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*\)/.exec(r))return b(parseInt(a[1],10),parseInt(a[2],
10),parseInt(a[3],10));if(a=/rgba\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]+(?:\.[0-9]+)?)\s*\)/.exec(r))return b(parseInt(a[1],10),parseInt(a[2],10),parseInt(a[3],10),parseFloat(a[4]));if(a=/rgb\(\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*\)/.exec(r))return b(2.55*parseFloat(a[1]),2.55*parseFloat(a[2]),2.55*parseFloat(a[3]));if(a=/rgba\(\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\s*\)/.exec(r))return b(2.55*
parseFloat(a[1]),2.55*parseFloat(a[2]),2.55*parseFloat(a[3]),parseFloat(a[4]));if(a=/#([a-fA-F0-9]{2})([a-fA-F0-9]{2})([a-fA-F0-9]{2})/.exec(r))return b(parseInt(a[1],16),parseInt(a[2],16),parseInt(a[3],16));if(a=/#([a-fA-F0-9])([a-fA-F0-9])([a-fA-F0-9])/.exec(r))return b(parseInt(a[1]+a[1],16),parseInt(a[2]+a[2],16),parseInt(a[3]+a[3],16));r=k.trim(r).toLowerCase();if("transparent"==r)return b(255,255,255,0);a=d[r]||[0,0,0];return b(a[0],a[1],a[2])};var d={aqua:[0,255,255],azure:[240,255,255],beige:[245,
245,220],black:[0,0,0],blue:[0,0,255],brown:[165,42,42],cyan:[0,255,255],darkblue:[0,0,139],darkcyan:[0,139,139],darkgrey:[169,169,169],darkgreen:[0,100,0],darkkhaki:[189,183,107],darkmagenta:[139,0,139],darkolivegreen:[85,107,47],darkorange:[255,140,0],darkorchid:[153,50,204],darkred:[139,0,0],darksalmon:[233,150,122],darkviolet:[148,0,211],fuchsia:[255,0,255],gold:[255,215,0],green:[0,128,0],indigo:[75,0,130],khaki:[240,230,140],lightblue:[173,216,230],lightcyan:[224,255,255],lightgreen:[144,238,
144],lightgrey:[211,211,211],lightpink:[255,182,193],lightyellow:[255,255,224],lime:[0,255,0],magenta:[255,0,255],maroon:[128,0,0],navy:[0,0,128],olive:[128,128,0],orange:[255,165,0],pink:[255,192,203],purple:[128,0,128],violet:[128,0,128],red:[255,0,0],silver:[192,192,192],white:[255,255,255],yellow:[255,255,0]}})(jQuery);
(function(k){k.plot.plugins.push({init:function(d){function k(){!b.locked&&-1!=b.x&&(b.x=-1,d.triggerRedrawOverlay())}function a(a){if(!b.locked)if(d.getSelection&&d.getSelection())b.x=-1;else{var c=d.offset();b.x=Math.max(0,Math.min(a.pageX-c.left,d.width()));b.y=Math.max(0,Math.min(a.pageY-c.top,d.height()));d.triggerRedrawOverlay()}}var b={x:-1,y:-1,locked:!1};d.setCrosshair=function(a){a?(a=d.p2c(a),b.x=Math.max(0,Math.min(a.left,d.width())),b.y=Math.max(0,Math.min(a.top,d.height()))):b.x=-1;
d.triggerRedrawOverlay()};d.clearCrosshair=d.setCrosshair;d.lockCrosshair=function(a){a&&d.setCrosshair(a);b.locked=!0};d.unlockCrosshair=function(){b.locked=!1};d.hooks.bindEvents.push(function(b,c){b.getOptions().crosshair.mode&&(c.mouseout(k),c.mousemove(a))});d.hooks.drawOverlay.push(function(a,c){var d=a.getOptions().crosshair;if(d.mode){var h=a.getPlotOffset();c.save();c.translate(h.left,h.top);-1!=b.x&&(c.strokeStyle=d.color,c.lineWidth=d.lineWidth,c.lineJoin="round",c.beginPath(),-1!=d.mode.indexOf("x")&&
(c.moveTo(b.x,0),c.lineTo(b.x,a.height())),-1!=d.mode.indexOf("y")&&(c.moveTo(0,b.y),c.lineTo(a.width(),b.y)),c.stroke());c.restore()}});d.hooks.shutdown.push(function(b,c){c.unbind("mouseout",k);c.unbind("mousemove",a)})},options:{crosshair:{mode:null,color:"rgba(170, 0, 0, 0.80)",lineWidth:1}},name:"crosshair",version:"1.0"})})(jQuery);
(function(k){k.plot.plugins.push({init:function(d){d.hooks.processDatapoints.push(function(d,a,b){if(null!=a.fillBetween){var g;a:{var d=d.getData(),c;for(c=0;c<d.length;++c)if(d[c].id==a.fillBetween){g=d[c];break a}"number"==typeof a.fillBetween?(c=a.fillBetween,g=0>c||c>=d.length?null:d[c]):g=null}if(g){d=b.pointsize;c=b.points;var k=g.datapoints.pointsize;g=g.datapoints.points;for(var h=[],q,z,f,s,t=a.lines.show,u=2<d&&b.format[2].y,E=t&&a.lines.steps,F=!0,B=0,D=0,A;!(B>=c.length);){A=h.length;
if(null==c[B]){for(m=0;m<d;++m)h.push(c[B+m]);B+=d}else if(D>=g.length){if(!t)for(m=0;m<d;++m)h.push(c[B+m]);B+=d}else if(null==g[D]){for(m=0;m<d;++m)h.push(null);F=!0;D+=k}else{q=c[B];z=c[B+1];a=g[D];f=g[D+1];s=0;if(q==a){for(m=0;m<d;++m)h.push(c[B+m]);s=f;B+=d;D+=k}else if(q>a){if(t&&0<B&&null!=c[B-d]){q=z+(c[B-d+1]-z)*(a-q)/(c[B-d]-q);h.push(a);h.push(q);for(m=2;m<d;++m)h.push(c[B+m]);s=f}D+=k}else{if(F&&t){B+=d;continue}for(m=0;m<d;++m)h.push(c[B+m]);t&&(0<D&&null!=g[D-k])&&(s=f+(g[D-k+1]-f)*
(q-a)/(g[D-k]-a));B+=d}F=!1;A!=h.length&&u&&(h[A+2]=s)}if(E&&A!=h.length&&0<A&&null!=h[A]&&h[A]!=h[A-d]&&h[A+1]!=h[A-d+1]){for(m=0;m<d;++m)h[A+d+m]=h[A+m];h[A+1]=h[A-d+1]}}b.points=h}}})},options:{series:{fillBetween:null}},name:"fillbetween",version:"1.0"})})(jQuery);
(function(k){function d(a,b,d){a=a.getPlotOffset();if(d.images&&d.images.show)for(var c=d.datapoints.points,k=d.datapoints.pointsize,h=0;h<c.length;h+=k){var q=c[h],r=c[h+1],f=c[h+2],s=c[h+3],t=c[h+4],u=d.xaxis,E=d.yaxis,F;if(q&&!(0>=q.width||0>=q.height))if(r>s&&(F=s,s=r,r=F),f>t&&(F=t,t=f,f=F),"center"==d.images.anchor&&(F=0.5*(s-r)/(q.width-1),r-=F,s+=F,F=0.5*(t-f)/(q.height-1),f-=F,t+=F),!(r==s||f==t||r>=u.max||s<=u.min||f>=E.max||t<=E.min)){var B=0,D=0,A=q.width,K=q.height;r<u.min&&(B+=(A-B)*
(u.min-r)/(s-r),r=u.min);s>u.max&&(A+=(A-B)*(u.max-s)/(s-r),s=u.max);f<E.min&&(K+=(D-K)*(E.min-f)/(t-f),f=E.min);t>E.max&&(D+=(D-K)*(E.max-t)/(t-f),t=E.max);r=u.p2c(r);s=u.p2c(s);f=E.p2c(f);t=E.p2c(t);r>s&&(F=s,s=r,r=F);f>t&&(F=t,t=f,f=F);F=b.globalAlpha;b.globalAlpha*=d.images.alpha;b.drawImage(q,B,D,A-B,K-D,r+a.left,f+a.top,s-r,t-f);b.globalAlpha=F}}}function r(a,b,d,c){b.images.show&&(c.format=[{required:!0},{x:!0,number:!0,required:!0},{y:!0,number:!0,required:!0},{x:!0,number:!0,required:!0},
{y:!0,number:!0,required:!0}])}k.plot.image={};k.plot.image.loadDataImages=function(a,b,d){var c=[],r=[],h=b.series.images.show;k.each(a,function(a,b){if(h||b.images.show)b.data&&(b=b.data),k.each(b,function(a,b){"string"==typeof b[0]&&(c.push(b[0]),r.push(b))})});k.plot.image.load(c,function(a){k.each(r,function(b,c){var d=c[0];a[d]&&(c[0]=a[d])});d()})};k.plot.image.load=function(a,b){var d=a.length,c={};0==d&&b({});k.each(a,function(a,h){var r=function(){--d;c[h]=this;0==d&&b(c)};k("<img />").load(r).error(r).attr("src",
h)})};k.plot.plugins.push({init:function(a){a.hooks.processRawData.push(r);a.hooks.drawSeries.push(d)},options:{series:{images:{show:!1,alpha:1,anchor:"corner"}}},name:"image",version:"1.1"})})(jQuery);
(function(k){function d(a){var q=this,z,f=a.data||{};if(f.elem)q=a.dragTarget=f.elem,a.dragProxy=w.proxy||q,a.cursorOffsetX=f.pageX-f.left,a.cursorOffsetY=f.pageY-f.top,a.offsetX=a.pageX-a.cursorOffsetX,a.offsetY=a.pageY-a.cursorOffsetY;else if(w.dragging||0<f.which&&a.which!=f.which||k(a.target).is(f.not))return;switch(a.type){case "mousedown":return k.extend(f,k(q).offset(),{elem:q,target:a.target,pageX:a.pageX,pageY:a.pageY}),g.add(document,"mousemove mouseup",d,f),b(q,!1),w.dragging=null,!1;case !w.dragging&&
"mousemove":if(Math.pow(a.pageX-f.pageX,2)+Math.pow(a.pageY-f.pageY,2)<f.distance)break;a.target=f.target;z=r(a,"dragstart",q);!1!==z&&(w.dragging=q,w.proxy=a.dragProxy=k(z||q)[0]);case "mousemove":if(w.dragging){z=r(a,"drag",q);c.drop&&(c.drop.allowed=!1!==z,c.drop.handler(a));if(!1!==z)break;a.type="mouseup"}case "mouseup":g.remove(document,"mousemove mouseup",d),w.dragging&&(c.drop&&c.drop.handler(a),r(a,"dragend",q)),b(q,!0),w.dragging=w.proxy=f.elem=!1}return!0}function r(a,c,b){a.type=c;c=k.event.handle.call(b,
a);return!1===c?!1:c||a.result}function a(){return!1===w.dragging}function b(a,c){a&&(a.unselectable=c?"off":"on",a.onselectstart=function(){return c},a.style&&(a.style.MozUserSelect=c?"":"none"))}k.fn.drag=function(a,c,b){c&&this.bind("dragstart",a);b&&this.bind("dragend",b);return!a?this.trigger("drag"):this.bind("drag",c?c:a)};var g=k.event,c=g.special,w=c.drag={not:":input",distance:0,which:1,dragging:!1,setup:function(c){c=k.extend({distance:w.distance,which:w.which,not:w.not},c||{});c.distance=
Math.pow(c.distance,2);g.add(this,"mousedown",d,c);this.attachEvent&&this.attachEvent("ondragstart",a)},teardown:function(){g.remove(this,"mousedown",d);this===w.dragging&&(w.dragging=w.proxy=!1);b(this,!0);this.detachEvent&&this.detachEvent("ondragstart",a)}};c.dragstart=c.dragend={setup:function(){},teardown:function(){}}})(jQuery);
(function(k){function d(a){var d=a||window.event,c=[].slice.call(arguments,1),r=0,h=0,q=0,a=k.event.fix(d);a.type="mousewheel";d.wheelDelta&&(r=d.wheelDelta/120);d.detail&&(r=-d.detail/3);q=r;void 0!==d.axis&&d.axis===d.HORIZONTAL_AXIS&&(q=0,h=-1*r);void 0!==d.wheelDeltaY&&(q=d.wheelDeltaY/120);void 0!==d.wheelDeltaX&&(h=-1*d.wheelDeltaX/120);c.unshift(a,r,h,q);return(k.event.dispatch||k.event.handle).apply(this,c)}var r=["DOMMouseScroll","mousewheel"];if(k.event.fixHooks)for(var a=r.length;a;)k.event.fixHooks[r[--a]]=
k.event.mouseHooks;k.event.special.mousewheel={setup:function(){if(this.addEventListener)for(var a=r.length;a;)this.addEventListener(r[--a],d,!1);else this.onmousewheel=d},teardown:function(){if(this.removeEventListener)for(var a=r.length;a;)this.removeEventListener(r[--a],d,!1);else this.onmousewheel=null}};k.fn.extend({mousewheel:function(a){return a?this.bind("mousewheel",a):this.trigger("mousewheel")},unmousewheel:function(a){return this.unbind("mousewheel",a)}})})(jQuery);
(function(k){k.plot.plugins.push({init:function(d){function r(a,c){var b=d.offset();b.left=a.pageX-b.left;b.top=a.pageY-b.top;c?d.zoomOut({center:b}):d.zoom({center:b})}function a(a,c){r(a,0>c);return!1}function b(a){if(1!=a.which)return!1;var c=d.getPlaceholder().css("cursor");c&&(w=c);d.getPlaceholder().css("cursor",d.getOptions().pan.cursor);h=a.pageX;q=a.pageY}function g(a){var c=d.getOptions().pan.frameRate;!z&&c&&(z=setTimeout(function(){d.pan({left:h-a.pageX,top:q-a.pageY});h=a.pageX;q=a.pageY;
z=null},1E3*(1/c)))}function c(a){z&&(clearTimeout(z),z=null);d.getPlaceholder().css("cursor",w);d.pan({left:h-a.pageX,top:q-a.pageY})}var w="default",h=0,q=0,z=null;d.zoomOut=function(a){a||(a={});a.amount||(a.amount=d.getOptions().zoom.amount);a.amount=1/a.amount;d.zoom(a)};d.zoom=function(a){a||(a={});var c=a.center,b=a.amount||d.getOptions().zoom.amount,h=d.width(),g=d.height();c||(c={left:h/2,top:g/2});var r=c.left/h,q=c.top/g,w={x:{min:c.left-r*h/b,max:c.left+(1-r)*h/b},y:{min:c.top-q*g/b,max:c.top+
(1-q)*g/b}};k.each(d.getAxes(),function(a,c){var b=c.options,d=w[c.direction].min,f=w[c.direction].max,h=b.zoomRange;if(!1!==h){d=c.c2p(d);f=c.c2p(f);if(d>f)var g=d,d=f,f=g;g=f-d;if(!h||!(null!=h[0]&&g<h[0]||null!=h[1]&&g>h[1]))b.min=d,b.max=f}});d.setupGrid();d.draw();a.preventEvent||d.getPlaceholder().trigger("plotzoom",[d])};d.pan=function(a){var c={x:+a.left,y:+a.top};isNaN(c.x)&&(c.x=0);isNaN(c.y)&&(c.y=0);k.each(d.getAxes(),function(a,b){var d=b.options,f,h,g=c[b.direction];f=b.c2p(b.p2c(b.min)+
g);h=b.c2p(b.p2c(b.max)+g);var k=d.panRange;!1!==k&&(k&&(null!=k[0]&&k[0]>f&&(g=k[0]-f,f+=g,h+=g),null!=k[1]&&k[1]<h&&(g=k[1]-h,f+=g,h+=g)),d.min=f,d.max=h)});d.setupGrid();d.draw();a.preventEvent||d.getPlaceholder().trigger("plotpan",[d])};d.hooks.bindEvents.push(function(d,h){var k=d.getOptions();k.zoom.interactive&&(h[k.zoom.trigger](r),h.mousewheel(a));k.pan.interactive&&(h.bind("dragstart",{distance:10},b),h.bind("drag",g),h.bind("dragend",c))});d.hooks.shutdown.push(function(d,h){h.unbind(d.getOptions().zoom.trigger,
r);h.unbind("mousewheel",a);h.unbind("dragstart",b);h.unbind("drag",g);h.unbind("dragend",c);z&&clearTimeout(z)})},options:{xaxis:{zoomRange:null,panRange:null},zoom:{interactive:!1,trigger:"dblclick",amount:1.5},pan:{interactive:!1,cursor:"move",frameRate:20}},name:"navigate",version:"1.3"})})(jQuery);
(function(k){var d={series:{pie:{show:!1,radius:"auto",innerRadius:0,startAngle:1.5,tilt:1,offset:{top:0,left:"auto"},stroke:{color:"#FFF",width:1},label:{show:"auto",formatter:function(d,a){return'<div style="font-size:x-small;text-align:center;padding:2px;color:'+a.color+';">'+d+"<br/>"+Math.round(a.percent)+"%</div>"},radius:1,background:{color:null,opacity:0},threshold:0},combine:{threshold:-1,color:null,label:"Other"},highlight:{opacity:0.5}}}};k.plot.plugins.push({init:function(r){function a(a){ca||
(ca=!0,s=a.getCanvas(),t=k(s).parent(),d=a.getOptions(),a.setData(b(a.getData())))}function b(a){for(var c=0;c<a.length;++c)if("number"==typeof a[c].data)a[c].data=[[1,a[c].data]];else if("undefined"==typeof a[c].data||"undefined"==typeof a[c].data[0])"undefined"!=typeof a[c].data&&"undefined"!=typeof a[c].data.label&&(a[c].label=a[c].data.label),a[c].data=[[1,0]];for(var c=a,b=0;b<c.length;++b){var f=parseFloat(c[b].data[0][1]);f&&(B+=f)}for(var b=c=0,f=d.series.pie.combine.color,h=[],g=0;g<a.length;++g)a[g].data[0][1]=
parseFloat(a[g].data[0][1]),a[g].data[0][1]||(a[g].data[0][1]=0),a[g].data[0][1]/B<=d.series.pie.combine.threshold?(c+=a[g].data[0][1],b++,f||(f=a[g].color)):h.push({data:[[1,a[g].data[0][1]]],color:a[g].color,label:a[g].label,angle:a[g].data[0][1]*2*Math.PI/B,percent:100*(a[g].data[0][1]/B)});0<b&&h.push({data:[[1,c]],color:f,label:d.series.pie.combine.label,angle:c*2*Math.PI/B,percent:100*(c/B)});return h}function g(a,b){function f(){ctx.clearRect(0,0,s.width,s.height);t.children().filter(".pieLabel, .pieLabelBackground").remove()}
function h(){function a(c,b,d){0>=c||isNaN(c)||(d?ctx.fillStyle=b:(ctx.strokeStyle=b,ctx.lineJoin="round"),ctx.beginPath(),1E-9<Math.abs(c-2*Math.PI)?ctx.moveTo(0,0):k.browser.msie&&(c-=1E-4),ctx.arc(0,0,f,r,r+c,!1),ctx.closePath(),r+=c,d?ctx.fill():ctx.stroke())}var b=Math.PI*d.series.pie.startAngle,f;f=1<d.series.pie.radius?d.series.pie.radius:u*d.series.pie.radius;ctx.save();ctx.translate(E,F);ctx.scale(1,d.series.pie.tilt);ctx.save();for(var r=b,q=0;q<g.length;++q)g[q].startAngle=r,a(g[q].angle,
g[q].color,!0);ctx.restore();if(0<d.series.pie.stroke.width){ctx.save();ctx.lineWidth=d.series.pie.stroke.width;r=b;for(q=0;q<g.length;++q)a(g[q].angle,d.series.pie.stroke.color,!1);ctx.restore()}c(ctx);if(d.series.pie.label.show)for(var q=1<d.series.pie.label.radius?d.series.pie.label.radius:u*d.series.pie.label.radius,w=0;w<g.length;++w){if(g[w].percent>=100*d.series.pie.label.threshold){var B=g[w],l=b,A=w;if(0!=B.data[0][1]){var z=d.legend.labelFormatter,N=void 0,v=d.series.pie.label.formatter,
N=z?z(B.label,B):B.label;v&&(N=v(N,B));z=(l+B.angle+l)/2;l=E+Math.round(Math.cos(z)*q);z=F+Math.round(Math.sin(z)*q)*d.series.pie.tilt;t.append('<span class="pieLabel" id="pieLabel'+A+'" style="position:absolute;top:'+z+"px;left:"+l+'px;">'+N+"</span>");A=t.children("#pieLabel"+A);N=z-A.height()/2;z=l-A.width()/2;A.css("top",N);A.css("left",z);if(0<0-N||0<0-z||0>s.height-(N+A.height())||0>s.width-(z+A.width()))D=!0;0!=d.series.pie.label.background.opacity&&(l=d.series.pie.label.background.color,null==
l&&(l=B.color),B="top:"+N+"px;left:"+z+"px;",k('<div class="pieLabelBackground" style="position:absolute;width:'+A.width()+"px;height:"+A.height()+"px;"+B+"background-color:"+l+';"> </div>').insertBefore(A).css("opacity",d.series.pie.label.background.opacity))}}b+=g[w].angle}ctx.restore()}if(t){ctx=b;J=t.children().filter(".legend").children().width();u=Math.min(s.width,s.height/d.series.pie.tilt)/2;F=s.height/2+d.series.pie.offset.top;E=s.width/2;E="auto"==d.series.pie.offset.left?d.legend.position.match("w")?
E+J/2:E-J/2:E+d.series.pie.offset.left;E<u?E=u:E>s.width-u&&(E=s.width-u);for(var g=a.getData(),r=0;D&&r<A;){D=!1;0<r&&(u*=K);r+=1;f();if(0.8>=d.series.pie.tilt){var q=1<d.series.pie.radius?d.series.pie.radius:u*d.series.pie.radius;if(!(q>=s.width/2-5||q*d.series.pie.tilt>=s.height/2-15||10>=q)){ctx.save();ctx.translate(5,15);ctx.globalAlpha=0.02;ctx.fillStyle="#000";ctx.translate(E,F);ctx.scale(1,d.series.pie.tilt);for(var w=1;10>=w;w++)ctx.beginPath(),ctx.arc(0,0,q,0,2*Math.PI,!1),ctx.fill(),q-=
w;ctx.restore()}}h()}r>=A&&(f(),t.prepend('<div class="error">Could not draw pie with labels contained inside canvas</div>'));a.setSeries&&a.insertLegend&&(a.setSeries(g),a.insertLegend())}}function c(a){0<d.series.pie.innerRadius&&(a.save(),innerRadius=1<d.series.pie.innerRadius?d.series.pie.innerRadius:u*d.series.pie.innerRadius,a.globalCompositeOperation="destination-out",a.beginPath(),a.fillStyle=d.series.pie.stroke.color,a.arc(0,0,innerRadius,0,2*Math.PI,!1),a.fill(),a.closePath(),a.restore(),
a.save(),a.beginPath(),a.strokeStyle=d.series.pie.stroke.color,a.arc(0,0,innerRadius,0,2*Math.PI,!1),a.stroke(),a.closePath(),a.restore())}function w(a){q("plothover",a)}function h(a){q("plotclick",a)}function q(a,c){var b=r.offset(),f=parseInt(c.pageX-b.left);a:{for(var b=parseInt(c.pageY-b.top),h=r.getData(),g=r.getOptions(),g=1<g.series.pie.radius?g.series.pie.radius:u*g.series.pie.radius,k=0;k<h.length;++k){var q=h[k];if(q.pie.show){ctx.save();ctx.beginPath();ctx.moveTo(0,0);ctx.arc(0,0,g,q.startAngle,
q.startAngle+q.angle,!1);ctx.closePath();x=f-E;y=b-F;if(ctx.isPointInPath){if(ctx.isPointInPath(f-E,b-F)){ctx.restore();f={datapoint:[q.percent,q.data],dataIndex:0,series:q,seriesIndex:k};break a}}else{p1X=g*Math.cos(q.startAngle);p1Y=g*Math.sin(q.startAngle);p2X=g*Math.cos(q.startAngle+q.angle/4);p2Y=g*Math.sin(q.startAngle+q.angle/4);p3X=g*Math.cos(q.startAngle+q.angle/2);p3Y=g*Math.sin(q.startAngle+q.angle/2);p4X=g*Math.cos(q.startAngle+q.angle/1.5);p4Y=g*Math.sin(q.startAngle+q.angle/1.5);p5X=
g*Math.cos(q.startAngle+q.angle);p5Y=g*Math.sin(q.startAngle+q.angle);arrPoly=[[0,0],[p1X,p1Y],[p2X,p2Y],[p3X,p3Y],[p4X,p4Y],[p5X,p5Y]];arrPoint=[x,y];for(var s=!1,w=-1,B=arrPoly.length,A=B-1;++w<B;A=w)(arrPoly[w][1]<=arrPoint[1]&&arrPoint[1]<arrPoly[A][1]||arrPoly[A][1]<=arrPoint[1]&&arrPoint[1]<arrPoly[w][1])&&arrPoint[0]<(arrPoly[A][0]-arrPoly[w][0])*(arrPoint[1]-arrPoly[w][1])/(arrPoly[A][1]-arrPoly[w][1])+arrPoly[w][0]&&(s=!s);if(s){ctx.restore();f={datapoint:[q.percent,q.data],dataIndex:0,series:q,
seriesIndex:k};break a}}ctx.restore()}}f=null}if(d.grid.autoHighlight)for(b=0;b<U.length;++b)h=U[b],h.auto==a&&!(f&&h.series==f.series)&&(h=h.series,null==h&&(U=[],r.triggerRedrawOverlay()),"number"==typeof h&&(h=series[h]),h=z(h),-1!=h&&(U.splice(h,1),r.triggerRedrawOverlay()));f&&(b=f.series,"number"==typeof b&&(b=series[b]),h=z(b),-1==h?(U.push({series:b,auto:a}),r.triggerRedrawOverlay()):a||(U[h].auto=!1));t.trigger(a,[{pageX:c.pageX,pageY:c.pageY},f])}function z(a){for(var c=0;c<U.length;++c)if(U[c].series==
a)return c;return-1}function f(a,b){var d=a.getOptions(),f=1<d.series.pie.radius?d.series.pie.radius:u*d.series.pie.radius;b.save();b.translate(E,F);b.scale(1,d.series.pie.tilt);for(i=0;i<U.length;++i){var h=U[i].series;0>=h.angle||isNaN(h.angle)||(b.fillStyle="rgba(255, 255, 255, "+d.series.pie.highlight.opacity+")",b.beginPath(),1E-9<Math.abs(h.angle-2*Math.PI)&&b.moveTo(0,0),b.arc(0,0,f,h.startAngle,h.startAngle+h.angle,!1),b.closePath(),b.fill())}c(b);b.restore()}var s=null,t=null,u=null,E=null,
F=null,B=0,D=!0,A=10,K=0.95,J=0,ca=!1,U=[];r.hooks.processOptions.push(function(c,b){b.series.pie.show&&(b.grid.show=!1,"auto"==b.series.pie.label.show&&(b.series.pie.label.show=b.legend.show?!1:!0),"auto"==b.series.pie.radius&&(b.series.pie.radius=b.series.pie.label.show?0.75:1),1<b.series.pie.tilt&&(b.series.pie.tilt=1),0>b.series.pie.tilt&&(b.series.pie.tilt=0),c.hooks.processDatapoints.push(a),c.hooks.drawOverlay.push(f),c.hooks.draw.push(g))});r.hooks.bindEvents.push(function(a,c){var b=a.getOptions();
b.series.pie.show&&b.grid.hoverable&&c.unbind("mousemove").mousemove(w);b.series.pie.show&&b.grid.clickable&&c.unbind("click").click(h)})},options:d,name:"pie",version:"1.0"})})(jQuery);
(function(k,d,r){function a(){c=d[w](function(){b.each(function(){var a=k(this),c=a.width(),b=a.height(),d=k.data(this,q);if(c!==d.w||b!==d.h)a.trigger(h,[d.w=c,d.h=b])});a()},g[z])}var b=k([]),g=k.resize=k.extend(k.resize,{}),c,w="setTimeout",h="resize",q=h+"-special-event",z="delay";g[z]=250;g.throttleWindow=!0;k.event.special[h]={setup:function(){if(!g.throttleWindow&&this[w])return!1;var c=k(this);b=b.add(c);k.data(this,q,{w:c.width(),h:c.height()});1===b.length&&a()},teardown:function(){if(!g.throttleWindow&&
this[w])return!1;var a=k(this);b=b.not(a);a.removeData(q);b.length||clearTimeout(c)},add:function(a){function c(a,d,f){var h=k(this),g=k.data(this,q);g.w=d!==r?d:h.width();g.h=f!==r?f:h.height();b.apply(this,arguments)}if(!g.throttleWindow&&this[w])return!1;var b;if(k.isFunction(a))return b=a,c;b=a.handler;a.handler=c}}})(jQuery,this);
(function(k){k.plot.plugins.push({init:function(d){function k(){var a=d.getPlaceholder();0==a.width()||0==a.height()||(d.resize(),d.setupGrid(),d.draw())}d.hooks.bindEvents.push(function(a){a.getPlaceholder().resize(k)});d.hooks.shutdown.push(function(a){a.getPlaceholder().unbind("resize",k)})},options:{},name:"resize",version:"1.0"})})(jQuery);
(function(k){k.plot.plugins.push({init:function(d){function r(a){f.active&&(w(a),d.getPlaceholder().trigger("plotselecting",[b()]))}function a(a){1==a.which&&(document.body.focus(),void 0!==document.onselectstart&&null==s.onselectstart&&(s.onselectstart=document.onselectstart,document.onselectstart=function(){return!1}),void 0!==document.ondrag&&null==s.ondrag&&(s.ondrag=document.ondrag,document.ondrag=function(){return!1}),c(f.first,a),f.active=!0,t=function(a){t=null;void 0!==document.onselectstart&&
(document.onselectstart=s.onselectstart);void 0!==document.ondrag&&(document.ondrag=s.ondrag);f.active=!1;w(a);z()?g():(d.getPlaceholder().trigger("plotunselected",[]),d.getPlaceholder().trigger("plotselecting",[null]))},k(document).one("mouseup",t))}function b(){if(!z())return null;var a={},c=f.first,b=f.second;k.each(d.getAxes(),function(d,f){if(f.used){var h=f.c2p(c[f.direction]),g=f.c2p(b[f.direction]);a[d]={from:Math.min(h,g),to:Math.max(h,g)}}});return a}function g(){var a=b();d.getPlaceholder().trigger("plotselected",
[a]);a.xaxis&&a.yaxis&&d.getPlaceholder().trigger("selected",[{x1:a.xaxis.from,y1:a.yaxis.from,x2:a.xaxis.to,y2:a.yaxis.to}])}function c(a,c){var b=d.getOptions(),h=d.getPlaceholder().offset(),g=d.getPlotOffset(),k=c.pageX-h.left-g.left,q=d.width();a.x=0>k?0:k>q?q:k;h=c.pageY-h.top-g.top;g=d.height();a.y=0>h?0:h>g?g:h;"y"==b.selection.mode&&(a.x=a==f.first?0:d.width());"x"==b.selection.mode&&(a.y=a==f.first?0:d.height())}function w(a){null!=a.pageX&&(c(f.second,a),z()?(f.show=!0,d.triggerRedrawOverlay()):
h(!0))}function h(a){f.show&&(f.show=!1,d.triggerRedrawOverlay(),a||d.getPlaceholder().trigger("plotunselected",[]))}function q(a,c){var b,f,h,g,k=d.getAxes(),q;for(q in k)if(b=k[q],b.direction==c&&(g=c+b.n+"axis",!a[g]&&1==b.n&&(g=c+"axis"),a[g])){f=a[g].from;h=a[g].to;break}a[g]||(b="x"==c?d.getXAxes()[0]:d.getYAxes()[0],f=a[c+"1"],h=a[c+"2"]);null!=f&&(null!=h&&f>h)&&(g=f,f=h,h=g);return{from:f,to:h,axis:b}}function z(){return 5<=Math.abs(f.second.x-f.first.x)&&5<=Math.abs(f.second.y-f.first.y)}
var f={first:{x:-1,y:-1},second:{x:-1,y:-1},show:!1,active:!1},s={},t=null;d.clearSelection=h;d.setSelection=function(a,c){var b,h=d.getOptions();"y"==h.selection.mode?(f.first.x=0,f.second.x=d.width()):(b=q(a,"x"),f.first.x=b.axis.p2c(b.from),f.second.x=b.axis.p2c(b.to));"x"==h.selection.mode?(f.first.y=0,f.second.y=d.height()):(b=q(a,"y"),f.first.y=b.axis.p2c(b.from),f.second.y=b.axis.p2c(b.to));f.show=!0;d.triggerRedrawOverlay();!c&&z()&&g()};d.getSelection=b;d.hooks.bindEvents.push(function(c,
b){null!=c.getOptions().selection.mode&&(b.mousemove(r),b.mousedown(a))});d.hooks.drawOverlay.push(function(a,c){if(f.show&&z()){var b=a.getPlotOffset(),d=a.getOptions();c.save();c.translate(b.left,b.top);b=k.color.parse(d.selection.color);c.strokeStyle=b.scale("a",0.8).toString();c.lineWidth=1;c.lineJoin="round";c.fillStyle=b.scale("a",0.4).toString();var b=Math.min(f.first.x,f.second.x),d=Math.min(f.first.y,f.second.y),h=Math.abs(f.second.x-f.first.x),g=Math.abs(f.second.y-f.first.y);c.fillRect(b,
d,h,g);c.strokeRect(b,d,h,g);c.restore()}});d.hooks.shutdown.push(function(c,b){b.unbind("mousemove",r);b.unbind("mousedown",a);t&&k(document).unbind("mouseup",t)})},options:{selection:{mode:null,color:"#e8cfac"}},name:"selection",version:"1.1"})})(jQuery);
(function(k){k.plot.plugins.push({init:function(d){d.hooks.processDatapoints.push(function(d,a,b){if(null!=a.stack){for(var g,d=d.getData(),c=null,k=0;k<d.length&&a!=d[k];++k)d[k].stack==a.stack&&(c=d[k]);if(g=c){d=b.pointsize;c=b.points;k=g.datapoints.pointsize;g=g.datapoints.points;var h=[],q,z,f,s,t,u,E=a.lines.show;s=a.bars.horizontal;var F=2<d&&(s?b.format[2].x:b.format[2].y),a=E&&a.lines.steps;f=!0;for(var B=s?1:0,D=s?0:1,A=0,K=0,J;!(A>=c.length);){J=h.length;if(null==c[A]){for(m=0;m<d;++m)h.push(c[A+
m]);A+=d}else if(K>=g.length){if(!E)for(m=0;m<d;++m)h.push(c[A+m]);A+=d}else if(null==g[K]){for(m=0;m<d;++m)h.push(null);f=!0;K+=k}else{q=c[A+B];z=c[A+D];s=g[K+B];t=g[K+D];u=0;if(q==s){for(m=0;m<d;++m)h.push(c[A+m]);h[J+D]+=t;u=t;A+=d;K+=k}else if(q>s){if(E&&0<A&&null!=c[A-d]){f=z+(c[A-d+D]-z)*(s-q)/(c[A-d+B]-q);h.push(s);h.push(f+t);for(m=2;m<d;++m)h.push(c[A+m]);u=t}K+=k}else{if(f&&E){A+=d;continue}for(m=0;m<d;++m)h.push(c[A+m]);E&&(0<K&&null!=g[K-k])&&(u=t+(g[K-k+D]-t)*(q-s)/(g[K-k+B]-s));h[J+
D]+=u;A+=d}f=!1;J!=h.length&&F&&(h[J+2]+=u)}if(a&&J!=h.length&&0<J&&null!=h[J]&&h[J]!=h[J-d]&&h[J+1]!=h[J-d+1]){for(m=0;m<d;++m)h[J+d+m]=h[J+m];h[J+1]=h[J-d+1]}}b.points=h}}})},options:{series:{stack:null}},name:"stack",version:"1.2"})})(jQuery);
(function(k){function d(d,a){var b={square:function(a,b,d,g){g=g*Math.sqrt(Math.PI)/2;a.rect(b-g,d-g,g+g,g+g)},diamond:function(a,b,d,g){g*=Math.sqrt(Math.PI/2);a.moveTo(b-g,d);a.lineTo(b,d-g);a.lineTo(b+g,d);a.lineTo(b,d+g);a.lineTo(b-g,d)},triangle:function(a,b,d,g,k){var g=g*Math.sqrt(2*Math.PI/Math.sin(Math.PI/3)),f=g*Math.sin(Math.PI/3);a.moveTo(b-g/2,d+f/2);a.lineTo(b+g/2,d+f/2);k||(a.lineTo(b,d-f/2),a.lineTo(b-g/2,d+f/2))},cross:function(a,b,d,g){g=g*Math.sqrt(Math.PI)/2;a.moveTo(b-g,d-g);
a.lineTo(b+g,d+g);a.moveTo(b-g,d+g);a.lineTo(b+g,d-g)}},g=a.points.symbol;b[g]&&(a.points.symbol=b[g])}k.plot.plugins.push({init:function(k){k.hooks.processDatapoints.push(d)},name:"symbols",version:"1.0"})})(jQuery);
(function(k){k.plot.plugins.push({init:function(d){function r(a,b,d,c,r){var h=d.pointsize,q,z,f,s,t=k.extend({},b);t.datapoints={points:[],pointsize:h,format:d.format};t.label=null;t.color=r;t.threshold=null;t.originSeries=b;t.data=[];var r=d.points,u=b.lines.show;threspoints=[];newpoints=[];for(b=0;b<r.length;b+=h){q=r[b];z=r[b+1];s=f;f=z<c?threspoints:newpoints;if(u&&s!=f&&null!=q&&0<b&&null!=r[b-h]){var E=(q-r[b-h])/(z-r[b-h+1])*(c-z)+q;s.push(E);s.push(c);for(m=2;m<h;++m)s.push(r[b+m]);f.push(null);
f.push(null);for(m=2;m<h;++m)f.push(r[b+m]);f.push(E);f.push(c);for(m=2;m<h;++m)f.push(r[b+m])}f.push(q);f.push(z);for(m=2;m<h;++m)f.push(r[b+m])}d.points=newpoints;t.datapoints.points=threspoints;0<t.datapoints.points.length&&a.getData().push(t)}d.hooks.processDatapoints.push(function(a,b,d){b.threshold&&(b.threshold instanceof Array?(b.threshold.sort(function(a,b){return a.below-b.below}),k(b.threshold).each(function(c,k){r(a,b,d,k.below,k.color)})):r(a,b,d,b.threshold.below,b.threshold.color))})},
options:{series:{threshold:null}},name:"threshold",version:"1.2"})})(jQuery);
